import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const BEACH_POSTS: Post[] = [
  {
    slug: "beach-engagement-photo-ideas",
    title: "Beach Engagement Photo Ideas: 10 Frames the Coast Gives You for Free",
    seoTitle: "Beach Engagement Photo Ideas: 10 Coastal Frames",
    seoDescription:
      "Beach engagement photo ideas built for the waterline: tide and light windows, wind and sand logistics, and the 10 frames the coast gives you for free.",
    excerpt:
      "A beach is the rare location where the light, the floor, and the background are all working for you at the same time — if you show up at the right hour. Miss the window and you get squinting, spray in the lens, and the same flat postcard the crowds are photographing. These are 10 frames the coast gives you for free, plus the tide-and-light math that makes them possible.",
    category: "locations",
    date: "2026-09-15",
    dateModified: "2026-09-15",
    featuredImage: IMAGES.galleryTwirl,
    featuredAlt: "beach engagement photo ideas, couple walking the wet waterline at golden hour with dress caught in the sea wind",
    tags: ["beach", "coast", "golden hour", "outdoor", "tide", "wind"],
    author: harper,
    primaryKeyword: "beach engagement photo ideas",
    cluster: "engagement-photo-locations",
    lsiKeywords: ["coastal engagement photos", "beach sunset session", "tide charts", "sea breeze", "waterline portraits", "pier"],
    searchIntent: "Informational",
    relatedPosts: ["outdoor-engagement-photo-locations", "mountain-engagement-photos", "spring-summer-engagement-outfits", "at-home-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "engagement photo ideas" },
      { url: "/engagement-photo-locations/outdoor-engagement-photo-locations", anchor: "outdoor engagement photo ideas" },
      { url: "/engagement-photo-outfits/spring-summer-engagement-outfits", anchor: "what to wear in warm weather" },
      { url: "/engagement-photo-locations/indoor-engagement-photos", anchor: "a warm indoor backup" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryTwirl, overlayText: "The Coast Does the Work", pinTitle: "Beach Engagement Photo Ideas: 10 Coastal Frames", pinDescription: "Waterline light, fog backdrops, pier leading lines and the timing math behind all of it — 10 beach frames that read as your session, not a stock photo. Save these." },
      { image: IMAGES.hero, overlayText: "Tide, Sun, Same Hour", pinTitle: "The Tide-and-Light Math for Beach Photos", pinDescription: "Low tide at golden hour is the whole secret — mirror-sand reflections, no crowds, and the walk that makes the frames move. Here's how to time a beach session. Pin it." },
      { image: IMAGES.galleryLaugh, overlayText: "The Wind Is a Second Photographer", pinTitle: "Stop Fighting the Sea Breeze in Your Photos", pinDescription: "Dress motion, hair chaos, scarves mid-air — the wind is doing what no assistant can. How to use it instead of losing the session to it. Save for your beach shoot." },
    ],
    blocks: [
      { type: "p", text: "The beach looks like the easiest outdoor session on earth and quietly isn't. Light moves off the water fast, the tide rewrites the location every two hours, and the wind has opinions about your hair. Nail the timing and the coast hands you frames no park or studio can: mirror-wet sand, fog that erases the background, a sun setting into the same water you're standing in. Most of these 10 beach ideas work because of one decision made before the session — show up at low tide during the last hour of light, or the first after sunrise. The rest is knowing what to look for." },
      { type: "keyTakeaways", items: [
        "Low tide plus golden hour is the entire cheat code — the wet-sand mirror only exists in that overlap.",
        "The wind is a collaborator: motion in hair and fabric is what makes beach photos feel like film.",
        "Fog and overcast days are upgrades, not rescues — the sky becomes a softbox and the background disappears.",
        "Scout the exits: which end of the beach empties first, where the wind blocks, where the sand is firm.",
        "Bring a towel, hair ties, and flat shoes — comfort is a visible ingredient in every frame.",
      ]},
      { type: "h2", id: "why-beaches-work", text: "Why Beach Frames Work (and When They Don't)" },
      { type: "p", text: "Beaches flatter because the water does two things no other location manages at once: it bounces light upward into faces like a giant reflector, and it keeps the background infinitely clean — horizon, water, sky, nothing at eye level to compete with. That's the whole mechanism. It stops working at high noon (overhead sun, bounce into eyes, everyone squinting) and in crowds, which on popular coasts means within fifty yards of every parking lot. Go at the edges of the day and the ends of the beach, and the location starts paying rent again." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "tide-light-math", text: "The Tide and Light Math" },
      { type: "p", text: "Three numbers decide a beach session: sunset time, sunrise time, and the tide window around them. When low tide lands within an hour of golden light, you get the mirror-sand — wet, packed, reflective — and the widest walking space on the whole coast. That overlap is maybe two or three afternoons a week, which is why regulars know their local tide chart like a TV schedule." },
      { type: "table", caption: "Beach conditions and what they give you", headers: ["Condition", "What it gives you", "What it takes"], rows: [
        ["Low tide + golden hour", "Mirror reflections, walking room, soft side light", "Nothing — book it"],
        ["High tide + golden hour", "Dramatic water behind you, wave action", "The wet-sand mirror, quiet space"],
        ["Overcast any time", "Even light, zero squint, moody grays", "Sunset color (use it for portraits)"],
        ["Fog", "Infinite soft background, film-like mood", "The horizon — faces carry the frame"],
        ["Midday sun", "Turquoise water color only", "Everything else; skip or shelter"],
      ]},
      { type: "h2", id: "the-10-frames", text: "The 10 Frames" },
      { type: "p", text: "Ten things the coast gives you for free, in the order a good session finds them — starting where the light is easiest and ending when the sand turns blue." },
      { type: "h3", id: "frame-waterline", text: "1. The Waterline Walk" },
      { type: "p", text: "The definitive beach frame and the first one you shoot. Walk together along the edge where the wave ends, look at each other instead of the lens, barefoot, train trailing behind you. The water draws the line; you two just walk it. Step into the wet band — packed sand holds reflections, and the mirror is the point." },
      { type: "h3", id: "frame-backlit", text: "2. The Backlit Silhouette" },
      { type: "p", text: "Once the sun is low enough to look near, put it directly behind you and expose for the sky. Faces go soft, edges go gold, and the frame stops being about you two and starts being about the shape of you two — which is, weirdly, more romantic. Shoot the set while she's mid-turn; fabric backlit is the whole subject." },
      { type: "h3", id: "frame-fog", text: "3. The Fog Softbox" },
      { type: "p", text: "If the morning is foggy, count it as a gift, not a rescue. Fog erases the horizon, kills the background noise, and turns the whole sky into a diffuser — the light that makes ordinary couples look like film stills. Move close; in fog, distance is the enemy and faces are everything." },
      { type: "h3", id: "frame-pier", text: "4. The Pier Leading Line" },
      { type: "p", text: "A pier is a built-in leading line with the ocean already staged behind it. Stand the couple at the rail where the posts converge and the frame assembles itself. Shoot up and down the pier at both ends of the hour — it's the most reliable beach frame there is." },
      { type: "h3", id: "frame-dunes", text: "5. The Dune Grass Foreground" },
      { type: "p", text: "Where the sand breaks and the dune grass starts, you get a foreground that adds depth and motion at once — sea oats sweeping the bottom of the frame while the couple stands above them. Shoot low through the grass and the whole coast feels layered. It's the one frame that looks more expensive than it is." },
      { type: "h3", id: "frame-wave", text: "6. The Wave Timing" },
      { type: "p", text: "Set the couple on the wet sand and let a single set come in behind them — not at them; read the pattern two waves early. Water frozen mid-sweep reads as motion; a blurred long wave reads as fog. Harper's Tip: at golden hour, 1/30 second freezes spray beautifully and smears the wave's tail. That shutter speed is a thing nobody outside photography knows and every beach couple should ask for." },
      { type: "h3", id: "frame-ring", text: "7. The Wet-Sand Ring Shot" },
      { type: "p", text: "Every engagement session earns one detail frame, and the beach's is the ring on packed wet sand with a soft wave behind it — the mirror surface doubles the glint. Do it in the gaps between the big frames, while she's walking ahead and he's holding the bag of shoes; the detail set never happens on command." },
      { type: "h3", id: "frame-overcast", text: "8. The Color-Pop Overcast" },
      { type: "p", text: "Flat gray sky is a painter's backdrop: put a camel coat or a deep red dress against it and the color does all the work. Overcast days are honestly my favorite for sweater-hour frames because nobody's squinting, skin renders evenly, and there's something cinematic about a warm person in a cold sky. Book the gray day with confidence." },
      { type: "h3", id: "frame-bluehour", text: "9. The Blue-Hour Sparkler" },
      { type: "p", text: "Twenty minutes after sunset, the sand turns blue-black and the world goes quiet — and that's when you light a sparkler and let it be the only source. The couple's faces glow amber, the beach disappears, and you get the frame that closes every gallery. Check local fire rules before you buy anything; some coasts ban them outright." },
      { type: "h3", id: "frame-trucktail", text: "10. The Truck-Tail Wrap" },
      { type: "p", text: "End the session where the story does: sitting on a tailgate or a cooler at the sand's edge, shoes off, hair ruined, sharing something from a bag. This frame photographs the relief after a good shoot, and across 400+ sessions it ranks with the frames couples actually print. Sand and all." },
      { type: "quote", text: "The beach is a collaborator, not a backdrop — the tide, the wind, and the fog all get a vote, and the couple who argues with them loses the afternoon.", cite: "Harper" },
      { type: "gallery", images: [
        { src: IMAGES.galleryTwirl, alt: "beach engagement photo ideas, dress trailing across mirror-wet sand at the waterline" },
        { src: IMAGES.gallerySilhouette, alt: "beach engagement photo ideas, backlit couple mid-turn as the sun drops toward the horizon" },
        { src: IMAGES.galleryLaugh, alt: "beach engagement photo ideas, amber sparkler glow on their faces during blue hour" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "logistics", text: "Wind, Sand, and the Logistics Nobody Posts" },
      { type: "p", text: "The unglamorous half of a beach session is what saves the glamorous half. Check the wind speed, not just the temperature — above fifteen knots and hair is the story (good), below three and fabric lies dead (less good). Arrive twenty minutes early and walk the beach's ends; the far side of a headland is usually empty and the near side never is. Bring a towel for sitting, hair ties, and flat shoes for the walk — heels are for the boardwalk. Bag the phones before the wave frames. And know the rules: some coasts require permits for professional equipment, and nearly all of them hate tripods in traffic. Finally, plan the exit before blue hour ends — parking lots after sunset on a good-beach night are a slow, dark parade." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They arrive at the most photographed stretch of coast because that's what they saw online, and spend the session framing themselves around strangers. They pick sunset, of course — and then high tide, because nobody checked, which deletes the wet sand entirely. They wear a hem that drags through the mirror and comes up salted, then hide it for the last hour. They apologize for the wind all session and never let it do anything. And they leave the second the sun drops, right as the blue hour opens into the best light of the day. The fix for all of it is twenty minutes of chart-checking before the drive: tide times, sunset time, wind, and which end of the beach is empty. That's the preparation." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "What most people miss about coastal light is how fast it's over. At the ocean the sun literally leaves the planet — the horizon is the deadline, and the good frames live in the last twenty minutes before it and the fifteen after. Beach sessions therefore fail on the clock, not the location. I start portrait frames twenty minutes earlier than the couple expects and I don't explain why; the gallery explains it." },
      { type: "p", text: "What I'd do differently after years of shooting coasts: I used to fight for the sunset itself — pointing couples at the fireball, racing it. Now the sun goes down behind them and I turn everyone around for the afterglow on their faces. The fireball is the postcard; the glow after it is the photo." },
      { type: "quote", text: "Texture is the most underrated element in outdoor photography — and the coast is texture on tap: wet sand, sea foam, dune grass, salt fog. A flat lawn can't compete.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What time of day is best for beach engagement photos?", a: "The last hour of daylight, with low tide if you can get it — that overlap gives you mirror-wet sand and side light on faces. First hour after sunrise is the quiet runner-up: same light, zero crowds, often better fog. Midday on a beach is the one genuinely bad option on the whole coast." },
        { q: "Should we go to the beach if it's foggy or overcast?", a: "Yes, with almost no hesitation. Fog and flat gray skies are the most flattering light the coast offers — the background erases, skin renders evenly, nobody squints. Move in closer than you would on a sunny day and let faces and fabric carry the frame. Only sideways wind-driven rain truly cancels." },
        { q: "What should we wear to a beach engagement session?", a: "Flow and texture: a dress long enough to trail across the wet sand, or nothing at all — jumpsuit, shorts, bare feet. Earth tones and one warm accent read beautifully against gray or gold water. Skip dragging hems, heels that die in sand, and anything you can't move freely in; the coast's gift is motion." },
        { q: "How do we deal with wind in beach photos?", a: "Use it, don't fight it. A sea breeze does what no assistant can: it gives the frame movement — dress trailing, hair lifted, a scarf mid-air. Face partly into the wind so hair flows backward, tie back what you don't want flying, and forget the apology every third gust invites." },
        { q: "Do we need a permit to photograph on the beach?", a: "For a couple and a handheld camera, usually no. Tripods, lighting, or an assistant cross into commercial-shoot territory on many coasts, and state beaches typically charge entry per vehicle. Rules vary by municipality more than by region, so check the specific beach's town website before you go — a five-minute lookup beats an awkward hour with a lifeguard." },
      ]},
      { type: "leadMagnet", title: "The Beach Session Timing Card", subtitle: "The tide-and-light window, the wind rules, and the 10 frames — one card before you drive to the coast.", bullets: ["How to find your low-tide golden-hour overlap", "Wind, hair, and fabric decisions made in advance", "The 10 frames, in shooting order"], cta: "Get the Beach Timing Card" },
      { type: "shop", section: "outfits", items: [
        { label: "Beach-flow maxi dress", store: "Etsy", href: "#" },
        { label: "Fold-flat canvas tote (sand kit)", store: "Amazon", href: "#" },
        { label: "Hair pins + sea-spray control kit", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The last beach session I shot was fogged in so thick the parking lot disappeared, and the couple arrived laughing because there was, genuinely, no one to be embarrassed in front of. We walked the waterline blind — they could hear the waves but not see them — and at minute forty the fog tore open for ten, gold pouring across the whole wet mirror, and closed again. They kept three frames from that window. They still tell people they shot the session with no ocean in it, and that it's the one where the light found them." },
      { type: "keepReading", items: [
        { label: "Outdoor Engagement Photo Locations", to: "/engagement-photo-locations/outdoor-engagement-photo-locations", note: "The light rules behind every coastal frame" },
        { label: "Spring & Summer Engagement Outfits", to: "/engagement-photo-outfits/spring-summer-engagement-outfits", note: "What to wear when the sand is the studio" },
        { label: "Indoor Engagement Photos", to: "/engagement-photo-locations/indoor-engagement-photos", note: "The warm backup when the coast closes in" },
      ]},
    ],
  },
];
