import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const CANDID_POSTS: Post[] = [
  {
    slug: "candid-engagement-photo-ideas",
    title: "Candid Engagement Photo Ideas: 12 Moments You Can't Pose, Only Set Up",
    seoTitle: "Candid Engagement Photo Ideas: 12 Unposed Moments",
    seoDescription:
      "Candid engagement photos aren't a style you ask for — they're moments you set up. 12 scenes with the exact prompts that make the camera disappear.",
    excerpt:
      "Candid engagement photos aren't a style you request — they're moments you arrange. A scene, a tiny task, and attention pointed somewhere other than the lens. These are 12 setups with the spoken prompts that make the camera disappear.",
    category: "ideas",
    date: "2026-09-10",
    dateModified: "2026-09-10",
    featuredImage: IMAGES.galleryLaugh,
    featuredAlt: "candid engagement photo ideas, couple caught mid genuine laugh during a session, neither looking at the camera",
    tags: ["candid", "unposed", "prompts", "session flow", "real reactions", "between the frames"],
    author: harper,
    primaryKeyword: "candid engagement photos",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["unposed engagement session", "spontaneous couple photos", "documentary style", "real reactions", "burst mode", "the in-between frames"],
    searchIntent: "Informational",
    relatedPosts: ["casual-engagement-photo-ideas", "unique-engagement-photo-ideas", "natural-engagement-photo-poses"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-poses/natural-engagement-photo-poses", anchor: "prompted poses that trigger real reactions" },
      { url: "/engagement-photo-ideas/casual-engagement-photo-ideas", anchor: "ideas built around something you already do" },
      { url: "/save-the-date-photos/surprise-proposal-ideas", anchor: "the candid proposal playbook" },
      { url: "/engagement-photo-ideas/unique-engagement-photo-ideas", anchor: "prop-driven sessions" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryLaugh, overlayText: "You Can't Ask for This", pinTitle: "12 Candid Engagement Photo Moments You Can Set Up", pinDescription: "Candid engagement photos aren't a style you request — they're moments you arrange. 12 scenes with the exact prompts that make the camera disappear. Save this for your session." },
      { image: IMAGES.casualCafe, overlayText: "Shoot the In-Between", pinTitle: "The Two Conditions Behind Every Candid Couple Photo", pinDescription: "Attention somewhere else, hands with a job. That's the whole mechanism — the 12 moments on this list are just the setups that make both true at once. Pin it before your shoot." },
      { image: IMAGES.hero, overlayText: "The Second Laugh Is Real", pinTitle: "Why Your First Fake Laugh Makes the Best Photo", pinDescription: "The performed laugh dies in about three seconds and the real one takes its place. Wait for it — it's the frame you'll print. 12 candid setups worth saving." },
    ],
    blocks: [
      { type: "p", text: "Candid engagement photos are the frames every couple says they want and no couple can simply request. You can't pose a real laugh. You can't choreograph the look he gives you when you're not watching the lens. What you can do is set the conditions and stand in them — a scene with a small task in it, timing that catches you before your face clocks in, and enough trust to keep the camera rolling through the messy parts. That's the whole trick: the candid isn't the absence of direction, it's direction pointed somewhere other than the camera. Here are 12 moments you can set up on your session, plus the two conditions every one of them depends on." },
      { type: "h2", id: "why-candid-wins", text: "Why the Candid Frame Beats the Posed One" },
      { type: "p", text: "A posed frame records compliance — it proves you held the shape while the shutter fired. A candid frame records the relationship itself: who checks on who, who breaks first, whose laugh arrives three seconds late. That's why candids age better and get printed. Across 400+ sessions, nine in ten frames a couple ends up printing are the ones nobody directed." },
      { type: "p", text: "There's a mechanism behind this. A camera is a social situation. The instant it's the most important object in the scene, both of you start performing for it — and performed joy reads as performed. Every setup that produces candids does one thing: it moves that object somewhere else. A joke, a collar that needs fixing, a name called from behind. The camera goes back to being a witness instead of an audience." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-conditions", text: "The Two Conditions Every Candid Frame Needs" },
      { type: "p", text: "Before the list, the short version: invent your own moments once these two conditions are true. Condition one: attention lives somewhere other than the lens. On each other, on a task, on a bad joke being whispered. Condition two: the hands have a job. An idle hand drifts to a pocket, then hair, then a pose, and the face follows it into performance. Give the hands a cup, a lapel, a shared walking pace, and the body stays honest." },
      { type: "keyTakeaways", items: [
        "The candid isn't the absence of direction — it's direction pointed away from the camera.",
        "Two conditions make every unposed frame: attention elsewhere, and a job for the hands.",
        "The performed laugh dies in about three seconds; the real one takes its place. Wait it out.",
        "The first five minutes and the last one belong to candids — faces aren't clocked in yet.",
        "Burst mode isn't cheating. It's how the in-between frames survive the shutter.",
      ]},
      { type: "h2", id: "the-12-moments", text: "The 12 Moments You Can Set Up" },
      { type: "p", text: "Each of these is a setup, not a pose — the shape of the frame depends on you two, and that's the point. In session order, because the moments have a natural arc: nervous energy first, tenderness in the middle, relief at the end." },
      { type: "h3", id: "m-first-five", text: "1. The First Five Minutes" },
      { type: "p", text: "The richest candid window of any session, and the one couples waste by \"getting ready to start.\" You've just arrived, the camera just came out, and your faces haven't picked their official expressions yet. Ask your photographer to shoot the walk from the car, the bag check, the \"did you bring the—\" panic. Harper's Tip: cover the arrival before you're in position — once you're in position, that door quietly closes." },
      { type: "h3", id: "m-whisper", text: "2. The Deadpan Whisper" },
      { type: "p", text: "One of you whispers something to the other, straight-faced, while the camera is on the listener. The whisperer's face has nothing to do with the joke — it's pure observation, and that's what sells the frame. The words don't matter; the worst joke you both know lands better than a funny one, because real jokes are also mean." },
      { type: "h3", id: "m-name-turn", text: "3. The Name Turn" },
      { type: "p", text: "You're facing away, and your name gets called off-camera, in whatever tone is normal for whoever's calling. The turn that follows isn't a pose, it's a reflex — the most natural head-movement in portrait photography. The version called by someone you actually love is better; that half-second of not-knowing-why reads like nothing else." },
      { type: "h3", id: "m-fix", text: "4. The Fix" },
      { type: "p", text: "\"Her collar's flipped; fix it\" is the oldest honest prompt in the book and still the sharpest caretaking frame there is. He straightens the collar and his face does the thing it always does checking his work on her — close, soft, faintly proud. Same setup with a tie or a strap. The hands have a job, and the camera goes invisible again." },
      { type: "h3", id: "m-second-laugh", text: "5. The Second Laugh" },
      { type: "p", text: "When you're told to laugh on command, the first one is fake and everyone knows it — and that shared recognition sets off the real one. So ask for the fake laugh on purpose and keep rolling. The real laugh lands about three seconds later, usually with her already leaning away. It's the most reproducible candid in a session; it has never once failed me." },
      { type: "ad", slot: "mid-article" },
      { type: "h3", id: "m-ring-handoff", text: "6. The Ring Handoff" },
      { type: "p", text: "She shows him the ring like she's only now really seeing it — hand lifted, eyes on his face instead of the stone. The frame is the exchange, not the jewelry. Most couples reverse this and shoot the hands while facing each other, which is the whole point of the prompt: the ring is the subject, his reaction is the photo." },
      { type: "h3", id: "m-coat-wrap", text: "7. The Coat Wrap" },
      { type: "p", text: "Set this up when it's not even needed — that's when it reads. His jacket goes around her shoulders, her fingers catch the lapel, and you stand like people sharing a coat for ten seconds. It's a pose disguised as a favor, the most reliable category of engagement photo there is. In Austin in September, do it at the moment you'd never do it on purpose." },
      { type: "h3", id: "m-light-wait", text: "8. The Light Wait" },
      { type: "p", text: "Golden hour means waiting, waiting means boredom, and boredom is candid gold. The slide down the wall, the chin on a shoulder, the phone shown to absolutely no one — these are two people killing time together, which is what an engagement actually is. Ask your shooter to keep the camera within reach during the wait; the good frames hide in the scheduling." },
      { type: "h3", id: "m-failed-pose", text: "9. The Failed Pose" },
      { type: "p", text: "Give the two of you something slightly undignified — a lift a half-step too high, a dip the floor won't commit to. Someone will say \"no, no, not like—\" and collapse laughing, and the recovery is worth more than the pose. It looks most like a mistake from the outside, which is exactly why it never photographs like one. Harper's Tip: tell your photographer the goal is the recovery, not the lift." },
      { type: "h3", id: "m-off-camera", text: "10. The Off-Camera Interruption" },
      { type: "p", text: "Someone speaks while the camera points the other way, and both heads turn at slightly different speeds — a phone ringing, a dog having a whole event three meters off, a comment about the parking. The shared \"are we seeing the same thing?\" is a two-person frame nothing posed can match: attention aimed at the world, and you happen to be standing in it together." },
      { type: "h3", id: "m-mid-walk", text: "11. The Mid-Walk Glance" },
      { type: "p", text: "Walking is the great candid machine — feet busy, so hands and faces stop performing. The trick isn't the walk but the glance: she looks at him mid-stride for no stated reason, and he doesn't notice for a full step. Shoot from the front so the look is caught coming, and don't announce it; a glance announced is a glance posed." },
      { type: "h3", id: "m-wrap-hug", text: "12. The Wrap Hug" },
      { type: "p", text: "The session's over, the camera technically isn't running, and the relief goes through you like a warm wave — shoes in hand, hair officially ruined. Every gallery I've ever delivered ends on this frame: the only moment you both stop doing anything. Keep the gear out for sixty seconds after \"we're done\"; that's the day's most honest photo." },
      { type: "quote", text: "Candid isn't a look you buy with a location or a lens. It's what's left when the two of you forget to perform — so the whole job is designing situations worth forgetting in.", cite: "Harper" },
      { type: "gallery", images: [
        { src: IMAGES.galleryLaugh, alt: "candid engagement photo ideas, her leaning away from a laugh that started as a fake one and stopped being fake" },
        { src: IMAGES.gallerySilhouette, alt: "candid engagement photo ideas, the wrap hug at the end of the session, camera technically off" },
        { src: IMAGES.casualCafe, alt: "candid engagement photo ideas, the light wait — two people killing time against a wall, no one performing" },
      ]},
      { type: "h2", id: "directing-not-posing", text: "Directing Without Posing: What to Ask For" },
      { type: "p", text: "Good candids are a collaboration, so it's fair to ask your photographer for the conditions that produce them. Three things do most of the work: a lens long enough that conversation stays normal; burst mode left on through the prompts — single frames catch poses, the rolls catch the seams where keepers live; and a shooter who gives instructions out loud instead of arranging you silently into a shape." },
      { type: "table", caption: "What to say, and the candid it produces", headers: ["The ask", "Why it works"], rows: [
        ["\"Can you shoot my arrival from the car?\"", "Catches the face before it clocks in — nervous energy reads as aliveness"],
        ["\"Give us a task, not a shape.\"", "Attention leaves the lens; the hands get a job; the body stops performing"],
        ["\"Keep the camera up after you call it.\"", "The wrap hug lives in the sixty seconds after the session is officially over"],
        ["\"Shoot through the failed pose.\"", "The recovery laugh is the frame; stopping at the stumble is stopping one photo early"],
        ["\"Whisper something to him, don't tell me what.\"", "Surprise is unrepeatable on command — the listener's face does the rest"],
      ]},
      { type: "p", text: "None of those asks are unusual, and any photographer worth booking will nod along to all five — candid direction is standard professional vocabulary now. (If one answers \"I just capture the moment, I don't direct,\" that's a style conversation to have before the session, not during it.)" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They book an hour, tick \"candid and natural\" on the intake form, then freeze the moment the camera appears — the form was read, the conditions weren't built. They apologize for laughing mid-prompt, which hands the room back to performance. They want the candid only after the \"real shots,\" so the honest window closes with the energy. And they trust the phone more than the moment: faces re-trained on the lens right when they'd started to forget it. Protect the conditions, and candids stop being luck." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "What nobody tells couples is that candids are loud. Quiet sessions produce quiet, careful faces; the good frames have an audio track — a laugh, a protest, a name shouted across gravel. So let the session be noisy: argue about the prompt, ruin it, repeat it until it's boring — boring is where the real face lives. My own keeper isn't the sunset portrait we planned for an hour. It's the frame where I'm mid-sentence about a parking ticket and he's looking at me like I'm the interesting part of the evening." },
      { type: "p", text: "What I'd do differently after all those sessions: I used to chase candids by hiding — longer lens, less talking, \"ignore the camera.\" But ignoring asks near-strangers to forget something huge in their hands. Now I direct toward candids openly: the whisper, the failed lift, the coat wrap, all announced. The performance doesn't disappear; it just has somewhere honest to go. Twelve moments, two conditions, and enough trust to keep rolling through the part where it feels silly — because that part is the photo." },
      { type: "quote", text: "The most romantic thing a camera can document isn't the couple looking at the lens — it's the couple looking at everything except it.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "How do you get candid engagement photos if I hate being photographed?", a: "The same way everyone else does — through tasks, not poses. Hate-of-cameras is actually an advantage: you already know how to stop performing, you just need somewhere to point the attention. Whispers, name-turns, and failed lifts work on skeptics first because the refusal to pose is exactly what makes the reaction honest. Bring a friend whose jokes land; it changes who the camera is a guest of." },
        { q: "Should we tell our photographer we want candid photos?", a: "Yes, in the intake conversation — and bring specifics. \"Candid\" can mean documentary to one shooter and gentle direction to another. Naming two or three moments from this list — arrival, whisper, wrap hug — turns a vibe into a plan. A good photographer will tell you what they need from you to make those work, which is the answer worth hearing before the session, not during it." },
        { q: "When in the session are candid photos easiest to get?", a: "The first five minutes and the last one. At the start your faces haven't gone on duty yet; at the end the relief makes everyone honest and the performance has simply run out of fuel. Mid-session candids are real too, but they're manufactured — set up through prompts like the coat wrap or the failed pose. Plan around the edges, direct through the middle, keep rolling after \"we're done.\"" },
        { q: "What's the difference between candid photos and just bad posing?", a: "Direction, and you can feel it while it's happening. Candid means attention somewhere honest — a joke, a task, a reaction — while the camera waits. Bad posing means the shape came first and you're holding it empty. Same shutter, opposite mechanism: one records you doing something, the other records you being photographed doing nothing." },
        { q: "Do we need burst mode, or will a photographer's timing be enough?", a: "Timing finds the good second; burst keeps the ones around it. Candid moments move through three or four frames — the inhale, the break, the lean — and no human thumb picks the right one every time. Every shooter I know who delivers honest galleries leaves the camera in burst through the prompts and edits down later. The rolls are the candid's shutter speed." },
      ]},
      { type: "leadMagnet", title: "The Candid Session Card", subtitle: "The 12 moments with their exact spoken prompts — one card for your photographer, and one for the two of you.", bullets: ["The arrival, the whisper, the wrap hug — in shooting order", "The two conditions to check when a frame goes stiff", "What to say when you realize the pose isn't working"], cta: "Get the Candid Session Card" },
      { type: "shop", section: "props", items: [
        { label: "Compact travel tripod with Bluetooth shutter (self-timer candids)", store: "Amazon", href: "#" },
        { label: "Wireless camera remote for off-camera direction", store: "Amazon", href: "#" },
        { label: "Soft blanket + safety pins (the coat-wrap insurance kit)", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "The last candid I ever shot professionally was almost the last frame in the file: a park path, camera down, a couple arguing gently about whether they'd been \"done\" for ten minutes or fifteen. She was mid-\"fifteen—\" and he'd started laughing at her certainty, and I lifted the camera without lifting my shoulders. They never noticed. They print that one. The light is a given; the moment just needs someone willing to keep the camera within reach." },
      { type: "keepReading", items: [
        { label: "Natural Engagement Photo Poses", to: "/engagement-photo-poses/natural-engagement-photo-poses", note: "The prompts behind the honest faces" },
        { label: "Casual Engagement Photo Ideas", to: "/engagement-photo-ideas/casual-engagement-photo-ideas", note: "Sessions built on things you already do" },
        { label: "Unique Engagement Photo Ideas", to: "/engagement-photo-ideas/unique-engagement-photo-ideas", note: "Props worth holding, games worth losing" },
      ]},
    ],
  },
];
