import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const COFFEE_POSTS: Post[] = [
  {
    slug: "coffee-shop-engagement-photo-ideas",
    title: "Coffee Shop Engagement Photos: 12 Setups in Someone Else's Living Room",
    seoTitle: "Coffee Shop Engagement Photos: 12 Setups",
    seoDescription:
      "Coffee shop engagement photos are the easiest-looking and hardest-run venue: 12 setups, the permission call, the mixed-light fix, and the weekday rule.",
    excerpt:
      "A café is a living room you rent with orders — warm, public and full of light that fights itself. Twelve setups inside the room and six at the door, plus the etiquette that keeps the door open.",
    category: "locations",
    date: "2026-10-29",
    dateModified: "2026-10-29",
    featuredImage: IMAGES.casualCafe,
    featuredAlt: "coffee shop engagement photos, the window booth at the quiet weekday hour, two mugs and one honest look between the light sources",
    tags: ["coffee shop", "café", "indoor", "window light", "permission", "mixed lighting"],
    author: harper,
    primaryKeyword: "coffee shop engagement photos",
    cluster: "engagement-photo-locations",
    lsiKeywords: ["café engagement session", "window booth portraits", "espresso bar glow", "chalkboard menu frame", "sidewalk table setup", "weekday morning crowd"],
    searchIntent: "Informational",
    relatedPosts: ["indoor-engagement-photos", "at-home-engagement-photo-ideas", "urban-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-locations", anchor: "the locations desk — scout by light first" },
      { url: "/engagement-photo-locations/indoor-engagement-photos", anchor: "the indoor chapter this room belongs to" },
      { url: "/engagement-photo-locations/at-home-engagement-photo-ideas", anchor: "the coffee version you can shoot for free" },
      { url: "/engagement-photo-locations/urban-engagement-photo-ideas", anchor: "the sidewalk half of this page" },
      { url: "/engagement-photo-ideas/casual-engagement-photo-ideas", anchor: "the coffee date as activity, not venue" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.casualCafe, overlayText: "Rent It With Orders", pinTitle: "12 Coffee Shop Engagement Photo Setups That Get Permission", pinDescription: "A café is someone else's living room — warm, public and light-tricky. Twelve setups inside, six at the door, the permission script and the mixed-light fix. Save before you book." },
      { image: IMAGES.gallerySilhouette, overlayText: "The Window Booth Wins", pinTitle: "The One Seat That Makes Coffee Shop Engagement Photos Work", pinDescription: "Every café has a window booth worth the whole session and two tables worth skipping. The light rule that finds it in ten seconds, plus twelve setups. Pin it." },
      { image: IMAGES.hero, overlayText: "Tuesday at Eight", pinTitle: "Why Your Café Engagement Shoot Should Happen Before the Rush", pinDescription: "Weekday mornings get you the room, the light and a barista who knows your names. Saturday gets you an apology tour. Twelve setups plus the etiquette. Save for planning." },
    ],
    blocks: [
      { type: "p", text: "Coffee shop engagement photos look like the easiest session on the calendar — a warm room, two mugs, a story you already live there — and they are the easiest venue to quietly ruin. The room belongs to someone else, the light comes from two sources fighting each other, and the crowd you want as texture becomes the problem the moment your elbows leave the table. Every setup below assumes the two real decisions are already made: permission from the owner, and the weekday hour when a café is still a room and not a queue. A coffee date shot as an activity is its own page of this desk; this is about the venue — the room, the light, the rules and the twelve frames it owes you." },
      { type: "h2", id: "easiest-hardest", text: "Why the Coziest Venue Is the Hardest to Run" },
      { type: "p", text: "A café is a living room you rent with orders — and like any borrowed room, everything works right up until you forget whose it is. The warmth that made you pick it runs on tungsten bulbs aimed at the espresso machine while the window behind you pours daylight onto the same table, so half the room wants one white balance and the other half wants its opposite." },
      { type: "p", text: "Then there's the working-space problem: a café at eleven on a Saturday is a business hosting your photos whether it agreed to or not. The same room at eight on a Tuesday is a set with a coffee bar. In roughly nine of ten café sessions I shot, the difference between the good gallery and the apology tour was a calendar day, not a lens." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-decisions", text: "Before You Book: Two Decisions" },
      { type: "p", text: "One: permission. Go in person on a slow weekday, buy something, ask the manager for a photo note — a two-line email to the owner beats a verbal maybe. Most independent shops say yes to a couple with a handheld camera; they say no to tripods, reflectors and people treating the line like a photo backdrop. Two: the booth. Every café has one window booth worth the whole session and two tables worth skipping; walk in, stand still for ten seconds, and find where the biggest light source is — that's the booth. The rest of the twelve setups are just ways to use that one seat honestly." },
      { type: "keyTakeaways", items: [
        "A café is a rented living room: permission and the hour decide the gallery.",
        "The window booth wins the whole session — find it in ten seconds, build around it.",
        "Two lights fighting (tungsten + daylight) is one white-balance decision away.",
        "Weekday morning beats golden Saturday: the room is the same, the crowd isn't.",
        "Buy the coffee, drink at least some of it, and let the regulars be your audience.",
      ]},
      { type: "h2", id: "six-inside", text: "The Six Setups Inside the Room" },
      { type: "p", text: "All six assume the booth or the light nearest it. Cup in hand, elbows low, faces toward the window." },
      { type: "list", items: [
        "The window booth — the whole session in one seat: two mugs, one honest look between the light sources, the street soft behind the glass; shoot from the dark side of the room so the window becomes the only light the faces know.",
        "The real order — you two at the counter ordering something you'll argue about later; the keeper isn't the transaction, it's the face you make when the barista asks what size.",
        "The chalkboard menu — the hand-lettered wall you pretend to read together; stand close enough that the lettering frames your heads, and let one of you point at something wrong on purpose.",
        "The cup pass — the barista's hands across the counter, yours receiving, coffee between the two of you like a ring shot; the hands have the job and the faces get to relax about nothing.",
        "The corner table — the one nobody wants because it faces the wall: turn the wall into negative space, shoot across the small table, and the room disappears into brown and window.",
        "The back stair or loft — if the shop has an upper landing, it's the only place in town where the ceiling lights can't reach you; the rail does for the café what the staircase does for elegance.",
      ]},
      { type: "h2", id: "six-at-door", text: "The Six Setups at the Door" },
      { type: "p", text: "The sidewalk is free of both the light problem and the crowd problem, and it's still the same address." },
      { type: "list", items: [
        "The sidewalk table — small bistro set, two cups, one knee; shoot it from across the street with the shop's window behind you and the whole scene becomes a painting of your morning.",
        "The bike rack — the most honest frame in café photography: one of you straddling it, bags on the handlebars, the other laughing at the logistics; it works because neither of you is posing at a bike.",
        "The OPEN sign — the neon in the door glass with two faces behind it, lit by the sign's own red or green; the glass adds the street back in for free.",
        "The fogged window — early morning, cold glass, a finger writing something dumb and one of you approving or correcting it; the fog does the background-blur job the lens usually has to fake.",
        "The queue window — you at the front, the line of the shop behind your shoulders; the depth is the composition and the regulars are the texture, once they've had time to be curious rather than annoyed.",
        "The closed door — before opening, the lights off inside, two mugs from the place next door held up like proof; the \"we're early\" energy is the warmest thing in this whole style, and it only lasts until the key turns.",
      ]},
      { type: "p", text: "Two setups inside, two at the door, done — the café is the appetizer course of a session, and cafés are at their warmest when nobody's hungry yet." },
      { type: "quote", text: "The room was already warm. The photographer's only job was to not break anything in it.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "the-light-problem", text: "The Light Problem, Solved by Sitting" },
      { type: "p", text: "Mixed light inside a café is not a camera failure, it's a seating choice. Face the window and the daylight owns your faces while the tungsten stays behind you as the glow — that's the frame everyone loves and few people understand, because the two sources never touch the same skin. Put yourself in the middle of the room instead and the two whites land on one face together, which is why the amateur café gallery has that orange-and-blue split across the nose. The fix lives in raw files and Kelvin, but the better fix is where your back is: window in front, room behind, and the color problem solves itself while the coffee solves the rest." },
      { type: "table", caption: "The café against the two venues it gets chosen over", headers: ["", "Coffee shop", "Restaurant", "At home"], rows: [
        ["Permission", "Ask the owner; usually yes, handheld only", "Often no daytime shoots; book a corner", "None needed — it's yours"],
        ["Light control", "One window booth, then you live with it", "Dark corners and overhead spots", "Any lamp, any time, no witnesses"],
        ["Crowd", "It's your texture and your timer", "It's your timer and your risk", "None but the household"],
        ["Cost", "Two drinks and a tip", "A meal or a private-hour fee", "Whatever was already in the pot"],
        ["Best for", "The couple whose story is already the walk there", "The long formal dinner feel", "The morning the photos feel real"],
      ]},
      { type: "h2", id: "etiquette", text: "The Etiquette That Keeps the Door Open" },
      { type: "p", text: "Shoot like a guest, not a production. Handheld beats tripod; four people beat six; forty minutes beats two hours; and buying drinks for the regulars at the next table costs less than one bad Yelp review about the couple who blocked the bathroom. Keep the aisle clear, the flash off, and the second location out the door — one room is the charm, which is why the twelve setups above are really four setups photographed from different seats. If the owner says a quiet word, you take it as a gift and you wrap. The shop that lets you photograph on Tuesday is also the one you're recommending for the wedding catering list, and that's worth more than the last frame." },
      { type: "h2", id: "goes-wrong", text: "When the Room Goes Wrong" },
      { type: "p", text: "Four ways, in order of how fixable they are. The rush arrives early and the aisle fills up: wrap the booth set and move to the door list. The window light dies behind a cloud and the tungsten turns everyone candle-colored: embrace it for one moody table and promise the faces a real window later. A stranger keeps photobombing from love: make them an ally — ask them to hold the cup for one frame and the room adopts you. And the worst, the couple that starts performing for the room: switch to the bike rack. When legs have a job and there's a ridiculous object involved, performance drops, because the scene is clearly too small to be famous in." },
      { type: "gallery", images: [
        { src: IMAGES.casualCafe, alt: "coffee shop engagement photos, the corner table with the wall as negative space and the room gone brown" },
        { src: IMAGES.indoor, alt: "coffee shop engagement photos, the chalkboard menu, one of them pointing at something wrong on purpose" },
        { src: IMAGES.gallerySilhouette, alt: "coffee shop engagement photos, the fogged window in early morning, one finger writing something dumb" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About the Café" },
      { type: "p", text: "They pick the busy one because it's the cute one, and a session is only cute after it's over. They plan three cafés across town to \"see which photographs better,\" which guarantees none of them feel regular, and the regular feel is the entire point. They bring props that turn the booth into a set — the banner, the matching flags — into a room that was already doing the work. And they forget the two mugs exist: hands empty at a café table is how you end up holding a pose, and a held pose in a public room is the one photograph where everyone watching feels bad for you first." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells couples is that the finest café gallery I ever delivered was shot by the second entrance, because the first couple I ever did there couldn't get a table and I had already made the drive. They leaned against the brick by the back door, drank two cups from next door held up like trophies, and had more fun waiting out the inconvenience than the booking would have given them. The lesson wasn't about backup locations. It was that the café was never the subject; the two people being late together was." },
      { type: "p", text: "What I'd do differently: I used to say yes to Saturday mornings and plan around the rush — shoot quick, dodge the line, apologize between frames. Now the rule is iron: weekdays, before ten, or the owner's quiet blessing in writing. The light doesn't change between Tuesday and Saturday, but the room's tolerance does, and a tolerance problem can't be fixed with a faster shutter. Twelve setups, two decisions, one seating rule — because a café shoots like a magazine when the couple behaves like regulars, and the regulars always sit in the booth." },
      { type: "quote", text: "Any room becomes a set the second you act like you belong to it. The trick is belonging without the deed.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "Can we take engagement photos at a coffee shop?", a: "Yes, when the owner agrees — ask in person or by a short email, and expect a yes for a couple with one handheld camera on a weekday morning. The usual no is for tripods, crews and anything that blocks the counter or the line. Independent shops tend to be glad; corporate cafés have a policy office, and a policy office has never once said yes before ten a.m." },
        { q: "What's the best time of day for café photos?", a: "The hour the shop opens, on a weekday. You get the window light before the crowds and a barista who can actually talk to you. Midday sun through glass goes hard and flattens faces; evening is tungsten soup with strangers everywhere. If Saturday is your only day, book the first ten minutes after opening — the room is still yours for that long." },
        { q: "Do we need permission from the coffee shop owner?", a: "For a phone camera, arguably no; for a real session with interchangeable lenses, yes — and it costs you nothing. The ask buys you the booth and the forty minutes nobody rushes. It also protects your photographer: a permission note in writing is the difference between a shoot and an incident. The shop that asks why you're there never had the conversation up front." },
        { q: "What should we wear for coffee shop photos?", a: "The thing you'd actually wear there, one level better. Café rooms run brown, cream and tungsten — so wear the contrast, not the camo: deep colors, one light piece near the face, no tiny patterns that moiré against the chalkboard. And skip anything that makes you careful; a room this small photographs every adjustment you make, and the keeper frames all come from the ten minutes before you noticed." },
        { q: "How long should a café engagement shoot last?", a: "Forty minutes is the whole session, and twenty of them are usable. More time means the crowd notices, the coffee goes cold and the booth loses its glow. Arrive with the shots picked — window, counter, door — shoot them in order, leave while the room still likes you. Couples who linger never print the extra frames; they just owe two more tables an apology." },
      ]},
      { type: "leadMagnet", title: "The Booth List", subtitle: "The permission script, the ten-second light walk, and the twelve setups — one card for you, one for your photographer.", bullets: ["The two-line email that gets the yes", "How to find the booth in ten seconds", "The forty-minute shooting order"], cta: "Get the Booth List" },
      { type: "shop", section: "location-accessories", items: [
        { label: "Pocket LED panel, warm/cool dial (for the back-loft corner)", store: "Amazon", href: "#" },
        { label: "Ceramic couple mugs, two different colors by design", store: "Etsy", href: "#" },
        { label: "Mini tripod, tabletop size (for the self-timer frame at the door)", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The last café session I ever shot professionally ended with the owner walking us out and pouring two more cups, because the couple had laughed at the chalkboard so hard that the regulars started reading it themselves. The gallery's keepers were all Tuesday: the fogged window, the cup pass, the back door with the borrowed cups held up like trophies. Coffee shop engagement photos are a favor the room grants you, and a favor is won the same way everywhere — arrive early, stay light, leave while they're still smiling. The window booth will be there on your anniversary." },
      { type: "keepReading", items: [
        { label: "Indoor Engagement Photos", to: "/engagement-photo-locations/indoor-engagement-photos", note: "The whole indoor chapter, light included" },
        { label: "At-Home Engagement Photo Ideas", to: "/engagement-photo-locations/at-home-engagement-photo-ideas", note: "The same coffee, no permission needed" },
        { label: "Urban Engagement Photo Ideas", to: "/engagement-photo-locations/urban-engagement-photo-ideas", note: "What the sidewalk does next" },
      ]},
    ],
  },
];
