import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const COZY_POSTS: Post[] = [
  {
    slug: "cozy-engagement-photos",
    title: "Cozy Engagement Photos: 12 Ways to Get Warm Without the Costume",
    seoTitle: "Cozy Engagement Photos: 12 Warm, Unposed Ways",
    seoDescription:
      "Cozy engagement photos that feel like being tucked in, not like a costume: soft light, honest textures, and closeness that never needs a snowstorm to work.",
    excerpt:
      "Cozy is the one look couples chase hardest and fake most often. They book a cabin, buy the matching blankets, and freeze. The photos that actually work had none of that — they had low light, a worn wool throw, and two people who forgot the camera was on. Here are 12 ways to get warm without the costume.",
    category: "ideas",
    date: "2026-10-06",
    dateModified: "2026-10-06",
    featuredImage: IMAGES.casualCafe,
    featuredAlt: "cozy engagement photos couple wrapped in a wool blanket by a window with soft warm light",
    tags: ["cozy", "winter", "indoor", "textures", "soft light", "intimate"],
    author: harper,
    primaryKeyword: "cozy engagement photos",
    cluster: "engagement-photo-ideas",
    relatedPosts: ["winter-engagement-photo-ideas", "holiday-engagement-photos", "pet-engagement-photos", "casual-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-ideas/winter-engagement-photo-ideas", anchor: "cold-weather shoots" },
      { url: "/engagement-photo-ideas/holiday-engagement-photos", anchor: "holiday sessions" },
      { url: "/engagement-photo-locations/indoor-engagement-photos", anchor: "shooting indoors" },
      { url: "/engagement-photo-locations/at-home-engagement-photo-ideas", anchor: "at-home sessions" },
      { url: "/engagement-photo-ideas/pet-engagement-photos", anchor: "involving a dog" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.casualCafe, overlayText: "Warm, Not Costumed", pinTitle: "Cozy Engagement Photos: 12 Warm, Unposed Ways", pinDescription: "Cozy doesn't need a snowstorm — it needs low light, honest texture, and two people who forget the camera. 12 ways to get warm without the costume. Save these." },
      { image: IMAGES.galleryRing, overlayText: "The Fabric Does It", pinTitle: "The Fabric Does the Cozy Work — Here's How", pinDescription: "Worn wool, cable knit, corduroy, a chipped mug. Texture is what reads as warm on camera — not fake snow or a matching blanket. Save the texture list." },
      { image: IMAGES.gallerySilhouette, overlayText: "Cozy Is a Light, Not a Season", pinTitle: "Cozy Is a Light, Not a Season", pinDescription: "The warmest photos I ever made were in August, in a dim room at golden hour. Here's how to find cozy light any time of year. Save this." },
    ],
    blocks: [
      { type: "p", text: "Cozy is the look everyone wants and almost no one gets, because most couples treat it as a set of props. A rented cabin, a bolt of fake snow, two brand-new matching blankets — and then they stand stiffly in the middle of it all, cold and self-conscious, and the photos come out looking like a catalogue for a living room. Here's the thing I learned across 400+ sessions: cozy isn't stuff. It's light and texture and the way two people actually sit together on a slow morning. The warmest frames I ever made were in August, in a dim room, at the last hour of sun. You don't need a snowstorm to get here. You need a low lamp, something worn and wool, and a reason to lean in." },
      { type: "keyTakeaways", items: [
        "Cozy is light and texture, not props — a cabin with no warmth still photographs cold.",
        "Low, warm light (a lamp, a window at dusk) does more than any blanket ever will.",
        "Worn beats new: a frayed throw and a chipped mug read as lived-in; costume pieces read as rented.",
        "Closeness is directed with a task (a shared mug, a book), not with the word 'snuggle'.",
      ]},
      { type: "h2", id: "why-cozy-turns-into-a-costume", text: "Why Cozy Photos Turn Into a Costume (and How Yours Won't)" },
      { type: "p", text: "Almost every failed cozy session makes the same three mistakes, and they're all fixable in planning. First, the props outrank the people: a set built entirely of blankets and cinnamon sticks has no one in it, and the couple looks like models who wandered onto someone else's shoot. Second, new reads as fake — a store-fresh cable and an unbroken white wall photograph as a showroom, not as a home. Third, and most importantly, couples wait for weather. They assume cozy requires snow, then cancel when Austin gives them a grey 45-degree morning, when that morning is closer to cozy than a bluebird sunny day will ever be. Cozy is a temperature you create on set, not a forecast. Bring low light, bring something worn, and give them a small shared task — and the season is beside the point." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "what-cozy-actually-is", text: "What 'Cozy' Actually Is — and Isn't" },
      { type: "p", text: "Cozy is the visual feeling of being warm on the inside of a frame: soft directional light, textures you can almost feel through the screen, and a body language that's turned toward the other person. None of those require cold weather, a cabin, or a single prop you bought for the occasion. Costumey is the opposite: warmth implied by objects (a blanket draped over a stranger, a mug held at arm's length for the camera) instead of felt by the people in it. If you can strip the props away and the two of them still look warm together, it's cozy. If the photo collapses without the throw blanket, it was always a costume." },
      { type: "table", caption: "The quick read: cozy that photographs vs. cozy that dates", headers: ["Element", "Reads as cozy", "Reads as costume"], rows: [
        ["Light", "Low, warm, directional (a lamp, dusk)", "Bright, flat, overhead"],
        ["Fabric", "Worn wool, cable, corduroy — fraying welcome", "New, stiff, matching sets"],
        ["Objects", "One or two lived-in things (a chipped mug)", "A whole styled vignette"],
        ["Body language", "Leaning in, foreheads, a shared book", "Holding props at arm's length"],
        ["Weather", "Any — cozy is made, not waited for", "Only if it snows"],
      ]},
      { type: "h2", id: "the-12-ways", text: "The 12 Ways" },
      { type: "p", text: "Twelve conditions that make a frame feel warm — light, texture, and small shared tasks. None of them need a cabin, and only one of them needs weather." },
      { type: "h3", id: "last-hour-window", text: "1. The Last-Hour Window" },
      { type: "p", text: "Position them beside a window in the final hour of daylight and turn everything else off. The low sun through glass is the single cheapest warm light there is — it wraps around a face and turns a plain wall gold. It's where I shot a couple on a Tuesday afternoon and they thought I'd lit the whole thing. I hadn't. The sun did." },
      { type: "h3", id: "one-lamp-only", text: "2. One Lamp, Nothing Else" },
      { type: "p", text: "Kill the overheads and light the room with a single warm lamp. A bare bulb around 2700K pools light on the two of them and lets the rest of the room fall into shadow, which is exactly the hush cozy lives in. Overhead light flattens a face; one lamp carves it." },
      { type: "h3", id: "worn-wool", text: "3. A Worn Wool Throw" },
      { type: "p", text: "Not a new blanket. A real one — the fringe a little frayed, the color faded soft from years of wash. Drape it over both of them or let her pull it around her shoulders, and shoot the texture close. The eye can feel wool through a photograph, and worn wool feels lived-in in a way showroom fabric never does." },
      { type: "h3", id: "shared-mug", text: "4. The Shared Mug" },
      { type: "p", text: "Give them each something warm to hold — coffee, cocoa, tea in a chipped ceramic mug — because hands holding a cup stop fidgeting and faces soften around the steam. Ask them to actually drink it. A real sip with eyes half-closed is worth fifty posed smiles for reading warm." },
      { type: "h3", id: "foreheads-not-kisses", text: "5. Foreheads, Not Kisses" },
      { type: "p", text: "The most intimate frame in cozy photography isn't a kiss — it's foreheads together, eyes closed, nothing happening. It's quieter and it's truer, and it works when a couple is too camera-shy for public affection. Ask them to just rest there while I breathe out. That exhale is when the shoulders finally drop." },
      { type: "h3", id: "cable-knit-on-one", text: "6. Cable Knit on One of Them" },
      { type: "p", text: "One person in a chunky sweater beats two — it gives the frame a texture anchor without tipping into the matching-sweater bit. The raised cable catches the window light and throws tiny shadows, so a still person looks like there's movement going on. Let the other stay simple so the knit reads." },
      { type: "h3", id: "a-real-book", text: "7. A Real Book, Open" },
      { type: "p", text: "Hand them a book they're actually reading and shoot the two heads close over one page. It solves the 'what do we do with our hands' problem instantly and it's inherently cozy — no prop in the world reads more like a lazy morning than a shared book. Bonus: they look down and forget the lens entirely." },
      { type: "h3", id: "bare-feet-couch", text: "8. Bare Feet on the Couch" },
      { type: "p", text: "Shoes off. Ankles crossed over the arm of a couch, socked or bare feet in frame. It's the small body detail that says this is home, not a set, and couples loosen up the second they take their shoes off. I keep my own camera bag behind the door — out of sight, off the story." },
      { type: "h3", id: "steam-and-sidelight", text: "9. Steam, Backlit" },
      { type: "p", text: "A kettle, a hot shower's fogged mirror, a mug of cocoa — put a light behind the steam and it glows. Backlit vapor is one of the most reliably warm things a photographer can find indoors, and it costs nothing. If you can make a drink during the session, make it in front of the window." },
      { type: "h3", id: "floor-not-furniture", text: "10. On the Floor, Not the Furniture" },
      { type: "p", text: "Set them on the floor with their backs against the sofa, pillows loose around them. It drops everyone to the same low level, closes the physical gap between them, and takes the 'sitting for a portrait' stiffness right out of a frame. Floors are also the most underrated warm texture: wood, rug, old tile — all of them." },
      { type: "h3", id: "the-dog-on-the-blanket", text: "11. The Dog on the Blanket" },
      { type: "p", text: "If they have a dog, get it on the throw with them — a dog settles the room faster than any direction I can give a nervous couple, and a head resting on a warm flank is cozy no one can fake. I've watched a session go from stiff to undone the minute a dog jumped up between them. For more on working around a four-legged guest, see how I handle involving a dog." },
      { type: "h3", id: "dusk-not-daylight", text: "12. Dusk, Not Daylight" },
      { type: "p", text: "When all else fails, shoot at dusk with a single lamp and let the window go blue outside. Cool dusk glass against warm indoor light is the whole mood in one frame — it's the visual of being inside while it gets cold out there. The contrast between the two temperatures is what makes the warmth feel earned." },
      { type: "gallery", images: [
        { src: IMAGES.gallerySilhouette, alt: "cozy engagement photos couple silhouetted against a warm window at dusk" },
        { src: IMAGES.galleryLaugh, alt: "cozy engagement photos couple laughing together under a worn wool blanket" },
        { src: IMAGES.galleryTwirl, alt: "cozy engagement photos one partner in a chunky cable knit sweater at home" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They buy the costume instead of building the conditions. A brand-new matching knit set, a basket of pinecones, a blanket still creased from the store — and then they stand in the doorway stiff and disappointed, because none of it made them warm; it just decorated the room. The second miss is waiting for weather: couples postpone their shoot until it snows, which in Texas is never, and cozy was available the whole time in a dim kitchen. The third is lighting the room for work instead of for mood — every overhead on, every blind open, and the softness drains right out. If you can only fix one thing, fix the light: turn everything off, keep one warm source low, and half the job is done before anyone changes clothes." },
      { type: "quote", text: "Cozy is not a season you wait for — it's a temperature you set. Turn one lamp on, and August can look like December.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "harpers-tips-cozy", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Here's the one direction I give every couple who wants cozy: forget the camera and give me something to do together. Warm hands around a mug, a book between two heads, a dog on the blanket — a small shared task melts the performance faster than any 'now be affectionate' I could give you. I shoot the doing, not the cuddling, and the cuddle is what shows up on its own." },
      { type: "p", text: "And here's what I'd do differently after all these years: I used to bring the blankets. Now I ask the couple to bring the one they already own and already love, fraying and all. It's never the right color. It's always the right photo, because it's theirs." },
      { type: "quote", text: "The coziest sessions I ever shot were in a too-small apartment on an August evening, with one lamp and a dog. Nobody was trying. That's the recipe.", cite: "Harper" },
      { type: "faq", items: [
        { q: "Do cozy engagement photos need snow or cold weather?", a: "No — cozy is made on set, not waited for in the forecast. The warmest photos I've shot were in August, in a dim room with one lamp at last light. Low warm light, a worn texture, and two people leaning in create the whole feeling. Cold weather helps a story, but it's the least necessary ingredient." },
        { q: "What should we wear for cozy engagement photos?", a: "One person in a chunky cable knit, the other simple so the texture reads. Worn beats new every time — a faded wool throw, a soft collar, fringes welcome. Stick to two or three warm tones you share rather than a matching set, and take your shoes off the second you're on the couch. It's closer to what to wear for a lazy Sunday than to a costume." },
        { q: "How do we look cozy if we're camera shy?", a: "Skip the kissing and give your hands a job. A shared mug, a book between two heads, foreheads together with eyes closed — all of them read as intimate without asking you to perform affection on command. Camera-shy couples look warmest when they're doing something and forget the lens is up. A dog helps more than any direction will." },
        { q: "How do you get cozy light indoors?", a: "Turn everything off and keep one warm source low. A single lamp around 2700K, or the last hour of sun through a window, pools light on your faces and lets the room fall into shadow — and that shadow is the quiet cozy lives in. Overhead light flattens a face; one low warm lamp carves it. The blue outside at dusk against the warm inside does the rest." },
        { q: "Should we use a cabin or our own home?", a: "Your own home almost always wins, because lived-in is the whole point and a rental is someone else's living room. A messy counter, a worn sofa, the mug you actually drink from read as real in a way a styled cabin never does. If you love a cabin for the story, go — but bring the frayed blanket from home so the frame has something true in it. The same logic is why at-home sessions photograph so warm." },
        { q: "What props actually make a photo cozy?", a: "One or two, not a vignette. A chipped mug with real steam, a worn wool throw, a book that's open to a page you're on. Props you'd genuinely reach for that morning are the ones that read as warmth; props arranged for the camera are the ones that read as a set. Backlight a little steam and it glows for free. If a prop doesn't get touched by hand, it doesn't belong in the frame." },
      ]},
      { type: "leadMagnet", title: "The Cozy Session Style Card", subtitle: "The one-lamp rule, the worn-texture list, and the three tasks that melt a stiff couple — one card for your shoot.", bullets: ["The one-lamp light setup, dialled in", "Worn-vs-new texture checklist to build from", "Three shared tasks that beat 'now snuggle'"], cta: "Get the Cozy Session Style Card" },
      { type: "shop", section: "props", items: [
        { label: "Warm-glow LED bulb (2700K)", store: "Home store", href: "#" },
        { label: "Worn wool throw", store: "Thrift / home", href: "#" },
        { label: "Chunky cable-knit sweater", store: "Clothing", href: "#" },
      ]},
      { type: "p", text: "It's a grey Saturday and nobody's bothered to turn on the lights. She's got his grandmother's blanket pulled up around her shoulders, his feet are crossed on the arm of the couch, and there's a half-finished book somewhere under their hands. I take a frame and neither of them looks up — that's the one. They'll see it later and say it looks like that Sunday, which is exactly the point. It didn't take a cabin or a snowstorm. It took a lamp and a morning they already had." },
      { type: "keepReading", items: [
        { label: "Winter Engagement Photo Ideas", to: "/engagement-photo-ideas/winter-engagement-photo-ideas", note: "Cozy's cold-weather cousin — layers and low sun" },
        { label: "Indoor Engagement Photos", to: "/engagement-photo-locations/indoor-engagement-photos", note: "Where to find the small spaces that feel big" },
        { label: "At-Home Engagement Photos", to: "/engagement-photo-locations/at-home-engagement-photo-ideas", note: "The lived-in room that always beats a set" },
      ]},
    ],
  },
];
