import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const CUTE_POSTS: Post[] = [
  {
    slug: "cute-engagement-photo-ideas",
    title: "Cute Engagement Picture Ideas: 12 Small Gestures That Read as You Two",
    seoTitle: "Cute Engagement Picture Ideas: 12 Small Gestures",
    seoDescription:
      "Cute engagement pictures aren't posed — they're allowed. 12 small gestures with the exact prompt for each, plus the line where cute turns cheesy.",
    excerpt:
      "Cute is affection small enough for the camera to catch. Twelve gestures — the forehead rest, the hand hug, the goodbye wave — with the prompt that lands each one and the line where cute turns cheesy.",
    category: "ideas",
    date: "2026-09-24",
    dateModified: "2026-09-24",
    featuredImage: IMAGES.galleryTwirl,
    featuredAlt: "cute engagement picture ideas, caught mid-giggle on his back at the end of the session, both of them looking ridiculous and happy",
    tags: ["cute", "affection", "small gestures", "closeness", "cheese line", "session flow"],
    author: harper,
    primaryKeyword: "cute engagement picture ideas",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["affection shown small", "forehead touch", "closeness on camera", "sweet couple frames", "tender gestures", "the goodbye wave"],
    searchIntent: "Informational",
    relatedPosts: ["fun-engagement-photo-ideas", "candid-engagement-photo-ideas", "cozy-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-ideas/fun-engagement-photo-ideas", anchor: "when the day needs more energy" },
      { url: "/engagement-photo-ideas/candid-engagement-photo-ideas", anchor: "how cute survives the camera" },
      { url: "/engagement-photo-poses/natural-engagement-photo-poses", anchor: "frames built like these" },
      { url: "/engagement-photo-ideas/pet-engagement-photos", anchor: "when the dog is half the story" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryTwirl, overlayText: "Allowed, Not Posed", pinTitle: "12 Cute Engagement Picture Ideas That Read as You Two", pinDescription: "Cute isn't a pose — it's affection small enough for the camera to catch. The forehead rest, the hand hug, the goodbye wave: 12 gestures with the exact prompt for each. Save this for your session." },
      { image: IMAGES.galleryRing, overlayText: "The Stone Is the Pretext", pinTitle: "The Ring Kiss and 5 More Close Frames for Your Engagement Shoot", pinDescription: "He kisses her hand at the ring and keeps his eyes down — the frame is the tenderness, not the stone. Six quiet gestures worth shooting before the light goes. Pin it before you book." },
      { image: IMAGES.gallerySilhouette, overlayText: "End on the Wave", pinTitle: "The Cutest Engagement Photo Is the Goodbye Wave", pinDescription: "The session ends, the car starts, and the wave through the window is the frame every couple prints. Twelve small gestures and the line where cute turns cheesy — save this list." },
    ],
    blocks: [
      { type: "p", text: "Cute engagement pictures are the frames that make other people say \"okay, that's them\" — the camera caught affection at a size smaller than performance. A full dip is a pose; his chin dropping onto her shoulder mid-sentence is a fact. The twelve gestures below all work at that small scale, each with the exact prompt that lands it, because cute is the one thing on a shoot list you can't ask for — you can only make room for it. For the noise-and-motion half of a playful day there's fun engagement photos; this page is the quiet half, and a good session runs both." },
      { type: "h2", id: "what-makes-cute", text: "What Actually Makes an Engagement Picture Cute" },
      { type: "p", text: "Cute is affection shown at a scale too small to pose. Big gestures — the dramatic dip, the sweeping lift — are aimed at the camera, so they read as performance. Small gestures are aimed at each other, and the camera catches them from behind: the forehead rest, the hand squeeze, the face he makes at her ring." },
      { type: "p", text: "Here at Tender Light we say the cutest frame is always a private one photographed by accident. Across my 400-plus sessions, in nine of ten galleries the printed save-the-date was a quiet closeness frame — and rarely the couple's own pick beforehand. They always chose the big smile. They always changed their minds." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-questions", text: "Before You Pick: Two Questions" },
      { type: "p", text: "One: could you do this on your own street in public? It will read on camera — cute borrowed from a mood board dies faster than a bad pose. Two: is it the size of what you actually are? Loud couples should be carrying each other; quiet couples are the hand-hug frame. Match the gesture to your real closeness, and the camera does the rest." },
      { type: "keyTakeaways", items: [
        "Cute is affection at a scale too small to pose — aimed at each other, caught from behind.",
        "Could you do this on your own street? If not, it reads on camera. Always.",
        "Match the gesture to your real volume — loud couples carry, quiet couples hold hands.",
        "Prompt the gesture, never the smile: the face is the echo, not the target.",
        "End the session with the goodbye wave — it's the frame everyone prints.",
      ]},
      { type: "h2", id: "the-12-gestures", text: "The 12 Cute Engagement Pictures You Can Set Up" },
      { type: "p", text: "Each one is a prompt, not a position — the shape belongs to you two. Six quiet ones first, then six that need one small prop or one extra pair of legs." },
      { type: "h3", id: "g-forehead", text: "1. The Forehead Rest" },
      { type: "p", text: "Foreheads together, eyes open, nothing said for three seconds. The frame is what happens at second four: someone's face goes soft before they can catch it. A pose tells bodies where to be; this tells them where to stop. Harper's Tip: don't hold it; when she feels herself posing it, she'll blink it away, and that blink is the keeper." },
      { type: "h3", id: "g-chin", text: "2. The Chin Rest" },
      { type: "p", text: "His chin lands on her shoulder from behind, mid-conversation, while she keeps talking about something else entirely. The frame is her face doing the talking and his face doing the loving — two honest expressions in one photograph. No one can chin-rest at a camera. It only works when the conversation is real, so the prompt is the conversation." },
      { type: "h3", id: "g-handhug", text: "3. The Hand Hug" },
      { type: "p", text: "His hands cover hers at her mid-chest, both faces above his arms like a frame around a picture. Her chin lifts off; his cheeks get pressed by her hair. A ring shot that includes the marriage instead of just the stone — nobody has to look at the lens." },
      { type: "h3", id: "g-cheek", text: "4. The Cheek Press" },
      { type: "p", text: "Cheek to cheek, both faces angled away from the lens. The reason it works is physics: pressed cheeks lift eyebrows slightly, and lifted brows read as adoration — which is why the frame survives being asked for. A full kiss is romantic; the press is cute, because it looks like the pause before one." },
      { type: "h3", id: "g-ringkiss", text: "5. The Ring Kiss" },
      { type: "p", text: "He kisses her hand at the ring and keeps his eyes down a half-second past the moment. The stone is the pretext; the face he makes afterward is the photograph. Most couples reverse it — hands, lens, smile — so rehearse the not-looking. Her watchful face at the ceremony is what makes strangers grin." },
      { type: "h3", id: "g-lean", text: "6. The Mid-Sentence Lean" },
      { type: "p", text: "She's saying something, he leans in to listen better than the room requires, and the camera takes the second where she notices and forgets the rest of the sentence. The prompt is real: tell her to actually finish a story, in her own words, badly. Whispered jokes work, but him listening to something genuinely uninteresting beats it — that's the frame that says he'd listen to all of it, for sixty years." },
      { type: "ad", slot: "mid-article" },
      { type: "h3", id: "g-piggyback", text: "7. The Piggyback Report" },
      { type: "p", text: "She carries him twenty steps and narrates the route as if for a tour bus that isn't coming — \"on our left, the parking meter, very historic.\" The legs go up, the laugh goes full-height, and the frame reads as joy instead of showing it. He can carry; the narrating gives her face something other than the camera. This one is a game in disguise; the games list lives on the fun side of the desk." },
      { type: "h3", id: "g-chalk", text: "8. The Sidewalk Chalk Heart" },
      { type: "p", text: "One heart, drawn together at your feet — her left half, his right half, the camera straight down. The frame is four hands and two faces peering in, because the drawing is bad, and a bad drawing made jointly always wins. A $3 box of chalk is the most reliable prop on this list; shoot it on the walk, before it becomes official." },
      { type: "h3", id: "g-dessert", text: "9. The Two-Spoon Dessert" },
      { type: "p", text: "One dessert, two spoons, one honest fight about the crust. The keeper isn't the feeding — it's the three seconds where each of you is defending your claim with custard still on your face. Eating together photographs well because the mouths are busy for a reason other than the camera. Skip the feed-to-each-other version; that's where the cheese line lives." },
      { type: "h3", id: "g-socks", text: "10. The Sock Reveal" },
      { type: "p", text: "Shoes up on a bench, socks matching-but-not — the inside joke printed on cotton, caught by a camera pointed at the floor. It works because it hides the faces at first: shoot the socks, let the couple look down laughing at their own gag, and only then bring the lens up. The joke exists in the photo, not in front of it." },
      { type: "h3", id: "g-dog", text: "11. The Third Wheel" },
      { type: "p", text: "The small dog between you two, both of you ignoring the camera to negotiate with the dog. Every pet session has the frame — the moment the couple becomes the staff of one very small animal — whether you plan it or not. A bandana is optional; the negotiation is the frame. The full playbook lives on the pet side of the desk." },
      { type: "h3", id: "g-wave", text: "12. The Goodbye Wave" },
      { type: "p", text: "The session is over, one of you gets in the car, the other waves — and the driver waves back with two fingers while pretending not to be crying. Relief makes people honest and goodbye makes them sincere, and cute only needs one of those. Harper's Tip: never announce this one. Ask your photographer to keep rolling while you pack; the wave happens on its own." },
      { type: "quote", text: "You can pose a couple. You can set up a game. Cute is the only one of the three you can't build — you just have to stop making it afraid.", cite: "Harper" },
      { type: "h2", id: "cute-not-cheesy", text: "The Cheese Line: Where Cute Turns" },
      { type: "p", text: "Every gesture on this list has a cheesy version, and the line is in one place: which way the faces point. Aimed at each other, the same action is cute; aimed at the lens, it's a stock photo. The two-spoon feed is the canonical crossing — eating together reads, performing the feeding doesn't. The fix is structural: change the prompt, not the couple. Point the attention back at each other and cute reappears on the very next frame." },
      { type: "table", caption: "Where the cute line sits, against its two neighbors", headers: ["The frame", "Aimed at", "What it says"], rows: [
        ["The dip, the full kiss", "The lens", "\"Look at us\" — that's the romantic desk's job, not this one"],
        ["The two-spoon feed, performed", "The lens", "Cheesy: the same affection pointed the wrong way"],
        ["The cheek press, the forehead rest", "Each other", "\"We forgot you were there\" — cute lives on this side of the line"],
        ["The chase tag, the balloon battle", "The game", "Fun: noise and motion, a different page of the same day"],
      ]},
      { type: "p", text: "The technical half of why cute works at all: these are close gestures, and close gestures want an open aperture — a 50mm around f/2 keeps the hand-hug sharp while the street behind it goes to watercolor. Background clutter reads as noise; a soft one reads as a room with two people in it." },
      { type: "h2", id: "where-when", text: "Where and When Cute Lands" },
      { type: "p", text: "Golden hour and your own front step — that's the whole answer. Soft light flatters closeness the way hard light flatters architecture, and home ground (the stoop, the kitchen floor, the bench outside your bakery) lets small gestures look like the way you already stand. Shoot the quiet six in the last hour of light where you actually live." },
      { type: "h2", id: "when-stiff", text: "When It Feels Stiff" },
      { type: "p", text: "The moment someone says \"this is adorable,\" it's over — self-awareness is the only disease cute has. The recovery is not encouragement; it's a change of gear. Drop from a quiet gesture to a noisy one: the piggyback, the chalk heart, anything that needs two hands and no face. In eight of ten sessions the self-conscious wave lasts two minutes, and the keeper follows the bad frame. Keep rolling through the flat part." },
      { type: "gallery", images: [
        { src: IMAGES.galleryRing, alt: "cute engagement picture ideas, the ring kiss, his eyes staying down a half second past the moment" },
        { src: IMAGES.classicDip, alt: "cute engagement picture ideas, the piggyback report, her narrating the route at full height on his back" },
        { src: IMAGES.indoor, alt: "cute engagement picture ideas, the chin rest on the kitchen floor mid story, two honest faces in one frame" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Cute" },
      { type: "p", text: "They list twenty gestures and try all of them; none land. Cute is a frequency you tune into, not a checklist you finish. They smile at the lens to sell the moment, which is exactly when the moment stops being theirs. They save the quiet ones for last, when the light and the energy are gone. And they borrow each other's couple, shooting someone else's piggyback on a street that isn't theirs. Pick three gestures your real closeness already contains, at the size you actually talk, on ground that's yours." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells couples is that a camera is closer to a recording than a portrait — it keeps whatever was happening the instant it fired. So the whole job is happening. My favorite frame from 400-plus sessions: a couple mid-hand-hug on their own porch steps, his face saying the quiet part out loud, sprinkles still on her chin from the two-spoon dessert." },
      { type: "p", text: "What I'd do differently: I used to hand couples a list of twenty cute gestures and cut them one by one as they died — the day ended on the one that hadn't failed. Now I choose three before the session, matched to the couple's actual volume, and protect the last hour of light for the quiet ones and the goodbye. The performance doesn't disappear; it just gets bored of itself and leaves. Twelve gestures, two questions, one wave at the end — because the small frame is the one that's true." },
      { type: "quote", text: "Big poses are aimed at the camera. Cute is what the camera finds when the two of you forget it's there.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What's the difference between cute and romantic engagement photos?", a: "Romance is aimed outward; cute is aimed at each other. The dip and the full kiss say \"look at us\" — they belong on the romantic side of the desk. The forehead rest and the hand hug announce nothing; same affection, smaller scale. Cute is romantic minus the audience." },
        { q: "How do we look cute without it feeling cheesy?", a: "Point the faces at each other, never at the lens, and keep the prompt real — a story she's actually telling, a joke he actually knows. The cheese line is crossed the instant the gesture is performed for the camera, and it's recoverable in one frame: change the attention, not the couple. Never announce the goodbye wave; make it happen by packing up." },
        { q: "What are the cutest engagement pictures for shy couples?", a: "The two quietest frames here: the hand-hug hides her face behind his arms, and the cheek press hides both faces from the lens. Shy couples actually shoot cuter than confident ones — holding still all day leaves more relief to be caught when you finally stop. Start with the chin rest and stay there." },
        { q: "Do we need props for cute engagement photos?", a: "Only for the back six, and the prop budget is about three dollars: a box of chalk, plus two spoons, mismatched socks, and a dog you already own. The front six need nothing but two people standing close, which is why the quiet half of this list works anywhere — a parking lot included." },
        { q: "How many cute pictures should we plan for a session?", a: "Three, plus the goodbye wave at the end — that's four, and four is what ninety minutes can honestly hold. The arc runs quiet-to-loud-to-quiet: one closeness frame to open the heart of the day, one silly one for the energy, one back to small for golden hour. Pick them before you arrive." },
      ]},
      { type: "leadMagnet", title: "The Cute Card", subtitle: "Twelve gestures, their exact prompts and the one line where each turns cheesy — one side for you two, one side for your photographer.", bullets: ["The quiet six, in shooting order", "The cheese test for every gesture on the list", "How to land the goodbye wave without announcing it"], cta: "Get the Cute Card" },
      { type: "shop", section: "props", items: [
        { label: "Jumbo sidewalk chalk set (the $3 heart, every color)", store: "Amazon", href: "#" },
        { label: "Personalized \"his & hers, roughly\" match-not-matching socks", store: "Etsy", href: "#" },
        { label: "Mini chalkboard sign + chalk pens (the inside-joke reveal)", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The last session I ever shot professionally ended on its own: a driveway, a car that needed to leave, and a wave with two fingers from a woman who absolutely was not crying. I delivered that frame last in the file and it was the first one printed. The whole exercise is one instruction: let the affection be smaller than the camera, and it will show you what an engagement looks like from the inside. That's what cute engagement pictures are made of." },
      { type: "keepReading", items: [
        { label: "Fun Engagement Photo Ideas", to: "/engagement-photo-ideas/fun-engagement-photo-ideas", note: "The noise-and-motion half of a playful day" },
        { label: "Candid Engagement Photo Ideas", to: "/engagement-photo-ideas/candid-engagement-photo-ideas", note: "How small gestures survive the lens" },
        { label: "Cozy Engagement Photos", to: "/engagement-photo-ideas/cozy-engagement-photos", note: "Cute, but with a blanket and a fire" },
      ]},
    ],
  },
];
