import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const EDITING_POSTS: Post[] = [
  {
    slug: "engagement-photo-editing",
    title: "Engagement Photo Editing: 7 Edits That Survive the Trip to Paper",
    seoTitle: "Engagement Photo Editing: 7 Edits That Survive Print",
    seoDescription:
      "Engagement photo editing for print, not for your screen: why bright monitors lie, the seven edits that survive paper, and how to send files a lab can use.",
    excerpt:
      "You edited them on a glowing screen and they looked true — then the prints came back darker, flatter, and slightly off. That's not a bad lab or bad edits; it's the gap every screen puts between you and paper. Here are the seven edits that survive the trip, and the file prep to send so your prints match your memory.",
    category: "tips",
    date: "2026-10-27",
    dateModified: "2026-10-27",
    featuredImage: IMAGES.galleryRing,
    featuredAlt: "engagement photo editing for print with a calibrated monitor and printed proof beside it",
    tags: ["editing", "print", "color", "soft proof", "file prep", "monitor"],
    author: harper,
    primaryKeyword: "engagement photo editing",
    cluster: "engagement-photo-prints",
    relatedPosts: ["glossy-or-matte-prints", "photo-print-sizes-guide", "true-digital-prints", "border-prints"],
    internalLinks: [
      { url: "/engagement-photo-prints/glossy-or-matte-prints", anchor: "glossy and matte papers" },
      { url: "/engagement-photo-prints/photo-print-sizes-guide", anchor: "print sizes and crops" },
      { url: "/engagement-photo-prints/true-digital-prints", anchor: "sending files to a lab" },
      { url: "/engagement-photo-prints/border-prints", anchor: "print borders" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryRing, overlayText: "Edit for Paper", pinTitle: "Engagement Photo Editing: 7 Edits That Survive Print", pinDescription: "Your screen is lying to you. Here are the seven edits that actually survive the trip to paper — and the file prep to send so prints match the memory. Save these." },
      { image: IMAGES.casualCafe, overlayText: "Brighten, Then Proof", pinTitle: "The Screen-vs-Paper Cheat Sheet", pinDescription: "Prints come back darker, flatter, and more muted than your monitor shows. Fix for it in the edit, not in the reprint. Save the cheat sheet." },
      { image: IMAGES.classicDip, overlayText: "sRGB, Not the Rest", pinTitle: "How to Export Photos a Print Lab Will Get Right", pinDescription: "sRGB, correct ratio, output sharpening, no upscaling — the file settings that stop a lab from guessing. Save before you hit order." },
    ],
    blocks: [
      { type: "p", text: "Almost every reprint I've ordered on someone's behalf traced back to the same cause: the edit was done on a bright, cool, over-saturated screen and never checked against paper. Monitors glow; prints reflect. A screen can push a file far more luminous than any piece of paper will ever be, and your eye happily believes the lie while you edit. Then the box arrives and everything is a shade darker, a touch flatter, a little muddy in the skin. The fix isn't to stop editing or to blame the lab — it's to make a handful of deliberate corrections that account for the screen-to-paper gap before you ever click order. Do these seven and your prints will look like the photos you fell in love with, not like a faded copy of them." },
      { type: "keyTakeaways", items: [
        "Screens glow and prints reflect — a bright monitor almost always reads darker on paper.",
        "Lift exposure slightly and cut saturation a touch; both survive paper better than the screen version.",
        "Crop to the print's real ratio up front, not after the lab trims your photo.",
        "Export sRGB at the true size with output sharpening — never let a lab upscale.",
      ]},
      { type: "h2", id: "why-prints-look-wrong", text: "Why Your Prints Look Wrong (When Nothing Is)" },
      { type: "p", text: "Nothing is broken in your file or your lab. The mismatch is physics: a monitor is a light source shining at your face, while a print only bounces whatever light is in the room. That difference skews three things you can't see while you're editing. Brightness reads high on a screen, so paper comes back darker. Saturation and vibrance pop on a backlit display and dull on matte stock. And cool monitor white-balance warms differently under the yellowish household bulbs you'll actually view the print under. You can outsource a calibration tool or a $300 monitor for the deep version of this — but for a handful of prints, a few deliberate on-screen corrections and one cheap test print solve ninety percent of it without spending a cent." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "screen-vs-paper", text: "The Screen-to-Paper Gap, Quantified" },
      { type: "p", text: "The gap is predictable, which is exactly why it's fixable. If you know the direction everything drifts, you can nudge the opposite way before you order. This is the short version of what a soft proof does for you automatically, and what your eye does badly for free." },
      { type: "table", caption: "How a typical screen edit drifts on paper", headers: ["Channel", "Screen shows", "Paper returns", "Pre-emptive fix"], rows: [
        ["Brightness", "Luminous, punchy", "Darker, ~½–1 stop", "Lift exposure before export"],
        ["Saturation", "Rich, vivid", "Flatter, muted", "Pull saturation back slightly"],
        ["Whites", "Cool, blue-white", "Neutral to warm", "Neutralize white balance"],
        ["Contrast", "Deep blacks", "Crushed or lifted (paper)", "Proof for the finish"],
        ["Detail", "Sharp at 100%", "Softer at print size", "Output-sharpen for size"],
      ]},
      { type: "h2", id: "the-7-edits", text: "The 7 Edits That Survive the Trip" },
      { type: "p", text: "Seven deliberate moves that make a screen edit behave on paper. Done in order, they turn a faded reprint into one you don't have to re-order." },
      { type: "h3", id: "soft-proof-first", text: "1. Soft-Proof Before Anything Else" },
      { type: "p", text: "Turn on soft-proofing in your editor and pick the lab's paper profile — or the closest generic profile — and view the image through it. This one toggle shows you the print before it exists, and every other adjustment on this list is really just doing, by eye, what soft-proofing does in software. If you only do one thing today, do this. It reframes the whole edit from 'what my monitor shows' to 'what the paper will show.'" },
      { type: "h3", id: "lift-exposure", text: "2. Lift Exposure a Half-Stop" },
      { type: "p", text: "Because prints come back darker, nudge the exposure up slightly — about a half-stop, less for glossy papers that already hold light — and check it against your soft proof, not your raw screen. The goal isn't a bright image; it's a bright image that survives being put on paper. Do it conservatively: too far and paper whites go flat and lifeless, which is the opposite failure and just as annoying." },
      { type: "h3", id: "skin-tones-first", text: "3. Nail Skin Tones Before Anything Else" },
      { type: "p", text: "A viewer's eye forgives a slightly odd sky long before it forgives a sickly face. Set the couple's skin first in your soft proof, get it warm and true, and then let the rest of the frame follow from it. On paper, cool-magenta skin reads as bad printing even when the lab did everything right, so pull skin toward neutral-warm slightly more than your glowing monitor tells you to." },
      { type: "h3", id: "tame-saturation", text: "4. Pull Saturation Back a Touch" },
      { type: "p", text: "Screens flatter color; paper, especially matte, mutes it. What looks richly saturated on your display can come back garish or, the opposite way, muddy once the finish is set. Reduce global saturation by a small amount and let the print's richness live in texture and light rather than in pushed color. Your cheapest safety net here is a single test print — order one small 4×6 and see how your favorite frame actually behaves." },
      { type: "h3", id: "match-the-finish", text: "5. Edit for the Finish You Chose" },
      { type: "p", text: "Glossy and matte are not the same file. Glossy holds deeper blacks and brighter whites, so you can lean into contrast; matte flattens and scatters, so a contrast-heavy edit comes back dull and a gentler one comes back soft. If you're torn between the two, the choice itself is its own decision, and it changes your edits more than most people realize, so settle it before you color rather than after." },
      { type: "h3", id: "crop-for-the-ratio", text: "6. Crop to the Real Print Ratio" },
      { type: "p", text: "Your camera shoots 3:2; an 8×10 print is 4:5; a square is 1:1. If you leave the crop for the lab, it decides what gets cut — and it will cut something you cared about. Lock your aspect ratio to the actual size you're ordering, recompose with intent, and keep faces and the ring away from the edges. This pairs directly with knowing the sizes, so settle the paper dimensions first and crop inside them, not around them." },
      { type: "h3", id: "sharpen-for-output", text: "7. Sharpen for Print Size, Not Screen" },
      { type: "p", text: "The amount of sharpening a photo needs depends on the size it's printed and the paper it's printed on. On a glossy sheet at 8×10 you want less; on a soft matte or a large enlargement you want more, because paper absorbs edge detail. Apply output sharpening at the export size rather than judging sharpness zoomed in at 100% on a monitor, where almost everything looks crisp and nothing is honest about the final dimensions." },
      { type: "gallery", images: [
        { src: IMAGES.classicDip, alt: "engagement photo editing soft proof on a calibrated monitor beside a printed test strip" },
        { src: IMAGES.gallerySilhouette, alt: "engagement photo editing skin tones corrected to read warm on matte paper" },
        { src: IMAGES.galleryTwirl, alt: "engagement photo editing cropped to a 4:5 print ratio keeping faces off the edge" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "file-prep", text: "The File Prep That Stops a Lab Guessing" },
      { type: "p", text: "Half of a good print is just a file the lab can't misread. Export as sRGB JPEG (or TIFF if the lab prefers) — never Adobe RGB, because most consumer labs don't color-manage and an Adobe RGB file arrives looking washed out. Set the pixel dimensions to the true print size at 300 pixels per inch; do not let the lab stretch a small file to fill a big print, because an upscaled print is soft and there's no edit that recovers it. Flatten, keep a 250–300 ppi resolution, and match the file's aspect to the order. Send a lab a clean, correctly sized sRGB file and it will print what you see far more often than it'll rescue a confused one." },
      { type: "quote", text: "A print lab is only as good as the file you hand it. Most 'bad prints' were really a good lab reading a bad export.", cite: "Harper, from 400+ sessions" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They edit to their monitor and never once consider the paper — then judge the whole batch by the first box that comes back off. They push saturation and vibrance because a backlit display loves that look, and wonder why the prints feel heavy. They order 8×10s from uncropped 3:2 frames and let the lab's auto-crop amputate a hand or a chin. They send tiny web-sized files to be blown up to an album page. And when the first prints come back off, they reprint at full price instead of ordering one cheap test first. Every one of these is preventable at the edit, for free, in the five minutes before you hit order." },
      { type: "quote", text: "I never judge an edit by the screen anymore. I judge it by a single small test print — that's the honest copy, and the monitor is only the rehearsal.", cite: "Harper" },
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "harpers-tips-editing", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Order one test print before you order the set. A single 4×6 or 5×7 from your lab is the cheapest correction you can make in this entire process — it shows your screen bias, your paper, and the lab's color all at once, for a couple of dollars. I've re-ordered a whole album's worth of prints because I skipped that test; don't." },
      { type: "p", text: "And here's the shift that changed how I hand files to a lab: I stopped trusting my eyes at midnight on a glowing display and started trusting a soft proof under room lights. The picture that reads well in soft proof is the picture that survives. Edit for the object, not the light behind it." },
      { type: "faq", items: [
        { q: "Why do my printed photos look different from my screen?", a: "A screen is a light shining at your face; a print only reflects the room. That gap makes paper come back darker, flatter, and slightly warmer than the luminous version you edited to. Nothing is wrong with your file or the lab — it's the same physics every time. Compensate in the edit with a soft proof and you'll close most of it before you order." },
        { q: "Should I edit in sRGB or Adobe RGB for prints?", a: "Use sRGB for almost every consumer lab. Most don't color-manage their workflow, so an Adobe RGB file arrives at the lab and gets displayed as if it were sRGB — which reads as faded, washed-out color. Unless your lab explicitly asks for Adobe RGB or TIFF with a profile, export sRGB and the print will match what you intended." },
        { q: "How sharp should I sharpen for engagement photo prints?", a: "Sharpen for the print's real size and its paper, not for the screen. A glossy 4×6 needs a light touch; a large matte enlargement needs noticeably more because paper absorbs edge detail. Avoid judging sharpness zoomed to 100% on a monitor, where nearly every file looks crisp regardless of the final dimensions it'll actually be printed at." },
        { q: "Do I edit matte and glossy prints the same way?", a: "No — the finish changes the file. Glossy holds deeper blacks and brighter whites, so it can carry more contrast. Matte scatters light and flattens, so the same contrast-heavy edit comes back dull. If you're torn between the two, settle that first, then adjust contrast downward for matte and upward for glossy. It's a bigger difference than most people expect." },
        { q: "How do I crop for an 8×10 without losing part of the photo?", a: "Decide the print size before you crop, then lock your editor's aspect ratio to that size (8×10 is 4:5, a square is 1:1, your camera's native 3:2 is neither). Recompose with the crop in control of your hands — keep faces and the ring off the edges you're about to lose. If you skip this, the lab auto-crops for you and cuts something you meant to keep." },
        { q: "Can I just send the lab my camera RAW files?", a: "No, send a finished export instead. RAW files aren't viewed consistently across labs, and the lab will apply its own guesses for white balance and contrast. Export the edited file as an sRGB JPEG at true print size and 300 ppi — that's the whole point of doing the seven edits yourself. When you're sending files to a lab, the cleaner the export, the less they have to decide for you." },
      ]},
      { type: "leadMagnet", title: "The Print-Ready File Checklist", subtitle: "The screen-to-paper fixes, the export settings, and the one-test-print rule — one card before you hit order.", bullets: ["The 7 edits that survive paper, in order", "Export settings a lab can't misread (sRGB, 300ppi, ratio)", "The cheap test-print step that saves a full re-order"], cta: "Get the Print-Ready Checklist" },
      { type: "shop", section: "prints", items: [
        { label: "Calibration target (print test strip)", store: "Photo lab", href: "#" },
        { label: "Soft-proof monitor hood", store: "Photo gear", href: "#" },
        { label: "Matte & glossy sample pack", store: "Photo lab", href: "#" },
      ]},
      { type: "p", text: "The album arrives and she turns to the first page and goes quiet in the good way — the faces are warm, not muddy, the whites are clean, the crop kept her hand where she wanted it. She looks up and says it looks just like the night, and that's the sentence every edit is chasing. It didn't happen because the monitor told the truth; monitors never do. It happened because we corrected for the paper before we trusted the screen, and printed the memory instead of the rehearsal." },
      { type: "keepReading", items: [
        { label: "Glossy or Matte Prints", to: "/engagement-photo-prints/glossy-or-matte-prints", note: "The finish you pick changes the edits you make" },
        { label: "Photo Print Sizes Guide", to: "/engagement-photo-prints/photo-print-sizes-guide", note: "The real ratios to crop your file inside" },
        { label: "True Digital Prints", to: "/engagement-photo-prints/true-digital-prints", note: "How to send a lab a file it can't misread" },
      ]},
    ],
  },
];
