import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const ELEGANT_POSTS: Post[] = [
  {
    slug: "elegant-engagement-photo-ideas",
    title: "Elegant Engagement Photos: 12 Frames Built on Restraint, Not Stiffness",
    seoTitle: "Elegant Engagement Photos: 12 Frames of Restraint",
    seoDescription:
      "Elegant engagement photos come from what a frame leaves out: 12 setups on space and stillness, the light-and-airy habit, and staying warm while formal.",
    excerpt:
      "Elegance is subtraction — space, stillness, one decision fewer. Twelve frames built on what the photograph leaves out, plus the exposure habit behind every light-and-airy gallery.",
    category: "ideas",
    date: "2026-10-15",
    dateModified: "2026-10-15",
    featuredImage: IMAGES.classicDip,
    featuredAlt: "elegant engagement photos, the slow walk in frame under a colonnade, nothing held, nothing performed, shoulders down",
    tags: ["elegant", "formal", "restraint", "staircases", "negative space", "light and airy"],
    author: harper,
    primaryKeyword: "elegant engagement photos",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["formal engagement session", "light and airy portraits", "negative space composition", "staircase portraits", "understated couple photos", "clean lines"],
    searchIntent: "Informational",
    relatedPosts: ["classic-engagement-photos", "black-and-white-engagement-photos", "candid-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-ideas/classic-engagement-photos", anchor: "the timeless cousin of this look" },
      { url: "/engagement-photo-ideas/candid-engagement-photo-ideas", anchor: "the warmth that keeps formal honest" },
      { url: "/engagement-photo-outfits/casual-engagement-photo-outfits", anchor: "what to wear when the frame is this clean" },
      { url: "/engagement-photo-ideas/black-and-white-engagement-photos", anchor: "the edit elegant frames love" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.classicDip, overlayText: "Subtraction, Not Stiffness", pinTitle: "12 Elegant Engagement Photo Frames Built on Restraint", pinDescription: "Elegance isn't a pose you hold — it's what the frame leaves out. Twelve setups built on space and stillness, and the one exposure habit behind light-and-airy galleries. Save this." },
      { image: IMAGES.gallerySilhouette, overlayText: "The Staircase Does Half the Work", pinTitle: "Elegant Engagement Photos: The Six Places That Frame You for Free", pinDescription: "Staircases, colonnades, long hallways — some architecture composes the couple for you. Twelve elegant setups, plus how to stay warm inside a formal frame. Pin it before you scout." },
      { image: IMAGES.hero, overlayText: "Shoulders Down", pinTitle: "Why Formal Engagement Photos Go Stiff (And the Two-Minute Fix)", pinDescription: "Stiffness is what happens when faces hold and bodies wait. The fix isn't loosening up — it's slower walking and a longer breath. Twelve elegant frames that stay warm. Save for your shoot." },
    ],
    blocks: [
      { type: "p", text: "Elegant engagement photos are the ones people call fancy and photographers call simple: it's the frame with things taken out of it. Empty wall instead of busy street, one slow movement instead of a dozen fidgets, a single decision about light instead of five about props. That's the whole mechanism, and it's why elegance and stiffness get confused so often — stiffness is what happens when the subtraction goes too far and nobody in the frame is allowed to move. Twelve setups below keep the space and the stillness and lose the chill, split between frames where architecture composes you and frames where the couple does it themselves." },
      { type: "h2", id: "what-elegant-is", text: "What Elegant Actually Is" },
      { type: "p", text: "Elegance in a photograph is a subtraction count. Every element removed — the clutter, the second joke, the third location change — gives the eye one place left to go, and that place becomes the faces. This is why an elegant frame and a fancy one are unrelated: fancy adds, and addition reads as effort." },
      { type: "p", text: "The reason couples freeze at the word is a false equation: formal doesn't mean still, it means held. A walk down a staircase is motion; a couple mid-correction about a hem is a reaction. What's formal is the tempo — everything in an elegant gallery happens one beat slower than in your other photos. Across the 400-plus sessions I shot, the couples who understood tempo ended up warmer than the casual shooters, because warmth with nowhere noisy to go reads as presence." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-questions", text: "Before You Book: Two Questions" },
      { type: "p", text: "One: can you walk slowly for ninety seconds without laughing at yourselves? Half the elegance is tempo discipline, and couples who giggle at their own slowness should know it now, not at the staircase. Two: is the location doing the formal work? A colonnade frames you whether you perform or not; a plain wall does nothing, and then it's all posture and no architecture. If your day already has a staircase — a library, a museum before opening, a hotel lobby with permission — the style is halfway yours." },
      { type: "keyTakeaways", items: [
        "Elegance is subtraction: every element removed gives the eye one place left to go.",
        "Formal means held, not still — the whole style runs one beat slower.",
        "Architecture does half the composing. Pick the staircase, then relax.",
        "The exposure habit behind light-and-airy: overexpose slightly, shoot soft window light.",
        "A warm elegant gallery keeps exactly one candid — the frame proves humans held it.",
      ]},
      { type: "h2", id: "six-architecture", text: "The Six Frames Architecture Composes" },
      { type: "p", text: "These are the locations that build the frame around you — you just walk through it at half speed." },
      { type: "list", items: [
        "The staircase descent — one hand on the rail, the other offered, walk it down like the stairs are longer than they are; the camera shoots from below, where the whole line of steps is the composition.",
        "The colonnade walk — columns repeat and the eye follows them to you; walk between two of them and stop mid-stride, because the frame is built by the architecture and held by your patience.",
        "The open door — a doorway you just came through or are about to, one hand on the frame; thresholds read as moments, and this one is free.",
        "The long hallway — you at the far end, walking toward a low camera; distance plus repetition plus one shared pace is an entire genre of photograph with no posing at all.",
        "The atrium glass — big windows, small figures, the sky doing the coloring; the trick is scale, so stand far from the glass and let the light be the subject you happen to share.",
        "The balcony high-line — shot from across the way or from the floor above, the rail a horizontal line under two faces; architecture gives you the horizon and the ledge.",
      ]},
      { type: "h2", id: "six-restraint", text: "The Six Frames the Couple Composes" },
      { type: "p", text: "When the location is plain, restraint does the composing: fewer moving parts, slower motion, one point of contact." },
      { type: "list", items: [
        "The slow walk in frame — full profile, nothing facing the camera, hands loose; a couple walking at half-speed against an empty wall is the most formal photograph a street can give.",
        "The seated line — two chairs or one step, shoulders touching, neither looking at the other; contact without embrace is the elegance version of closeness.",
        "The turned head — backs to the camera, one face over one shoulder; the frame has two directions in it, which is what makes it feel composed instead of arranged.",
        "The hem correction — she lifts the skirt, he steps over it, both faces annoyed at the train; a small problem solves the biggest formal problem, which is what to do with hands.",
        "The hand at the waist — his hand resting, hers on his forearm, zero embrace above the shoulder; restraint reads as intimacy at exactly this size.",
        "The mirror frame — a lobby mirror, the couple reflected with the room behind them in the reflection too; one photograph that contains the whole venue, and nobody has to hold a shape.",
      ]},
      { type: "p", text: "Twelve frames and one rule over all of them: an elegant gallery keeps exactly one candid — the laugh that breaks the tempo. One, not none: it's the frame that proves the rest were held by humans." },
      { type: "quote", text: "A frame is elegant to the exact number of things it leaves out. Everything else is just budget.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "light-and-airy", text: "The Light-and-Airy Truth" },
      { type: "p", text: "The phrase everyone uses for an elegant look is a habit, not a preset: shoot soft light and expose slightly for the highlights — about two-thirds of a stop over, then pull back at edit. That's why hotel lobbies and north-facing windows \"feel\" light-and-airy; they hand you large soft sources and white walls to bounce them. The mistake is doing it in hard midday sun and fixing it in post, because blown highlights stay blown and skin goes chalky at exactly the moment you think you're being flattering. Ask your photographer how they meter a formal frame — \"expose right, protect the whites\" is the sentence that tells you they've shot the look before." },
      { type: "table", caption: "Elegant against the three styles it gets confused with", headers: ["Style", "It borrows", "The tell"], rows: [
        ["Elegant", "Formality — tempo, space, subtraction", "One slow beat, everything held, the wall left bare"],
        ["Classic", "Nothing — it dodges dated choices", "Ages slowly; no decade visible either way"],
        ["Romantic", "Directness — the kiss, the embrace", "Faces pointed at the feeling, not the frame"],
        ["Moody", "Shadow — dark light, heavy contrast", "The background disappears into black, not into white"],
      ]},
      { type: "h2", id: "what-it-costs", text: "What the Look Costs" },
      { type: "p", text: "Nothing, if you aim at the public architecture most towns already own: the library staircase, the museum before it opens (that hour is yours for a coffee's price and a smile), the courthouse portico, the hotel lobby with one honest email about permission. What costs money is only the shortcut — a venue package that sells you the staircase already found. The clothes can stay in the wardrobe you own: one dark piece each, clean lines, no busy pattern, because the frame is doing the decorating." },
      { type: "h2", id: "goes-cold", text: "When Elegant Goes Cold" },
      { type: "p", text: "Coldness arrives in the first ten seconds of every staircase and goes away in minute two — the faces stop holding and start happening, and the photographer's job is to still be shooting at minute three. The structural fixes: give the couple something to do slowly (walk, not pose), keep contact small (a hand at the waist beats an arm around the shoulder for warmth — counterintuitive, true), and end each formal set with one real laugh to reset the shoulders. A cold gallery isn't a location problem; it's a set that ended before the couple got in. Keep the tempo, wait for the faces to catch up to it." },
      { type: "gallery", images: [
        { src: IMAGES.gallerySilhouette, alt: "elegant engagement photos, the long hallway at half speed, distance and repetition composing the couple for free" },
        { src: IMAGES.hero, alt: "elegant engagement photos, the atrium glass frame, small figures in big light with the sky doing the coloring" },
        { src: IMAGES.indoor, alt: "elegant engagement photos, the seated line on a staircase landing, shoulders touching and nobody looking at anyone" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Elegant" },
      { type: "p", text: "They dress up and stop moving, and stillness with good clothes on is just a portrait of tension. They clear the whole day for the formal hour and then hold every frame like it's fragile — an elegant photo survives being human; it's the third forced smile that kills it. They chase the busy version of grand (fountains, chandeliers, a staircase with a hundred people on it) when the style is a quiet staircase at 8 a.m. And they refuse the one candid, convinced it breaks the look — it's the frame that makes all the held ones believable. Formal is the container. The couple is the content, and the camera can always tell which one is on fire." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells couples is that elegant photographs are made by exhaling on the shutter. Shoulders ride up when a camera appears — it's the same reflex in a ballroom or a backyard — and a formal frame with raised shoulders is just a costume holding its breath. So the real prompt is physical: breathe out, keep the walk going, don't fix your hair. My own favorite gallery I ever delivered was a hotel staircase at eight in the morning, before the breakfast rush, where the couple forgot the lobby existed by the second flight." },
      { type: "p", text: "What I'd do differently: I used to chase elegance with direction — chin, shoulders, hands, repeat — and produced elegant mannequins with a living couple hidden inside. Now the architecture gets the assignment and the couple gets one instruction: slower. The restraint holds itself, and the warmth that comes after the first minute is the whole product. Twelve frames, one tempo, one candid kept on purpose — because elegance you can hear breathing is the only kind worth printing." },
      { type: "quote", text: "Stiff is what happens when a couple stops moving. Elegant is what happens when they slow down — the camera can tell, and so can everyone looking at the print.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "Are elegant engagement photos the same as formal ones?", a: "Elegant is the look; formal is one way to get there. A staircase at half speed is both. The difference is intent: formal describes the clothes and the setting, elegant describes what the frame leaves out. Plenty of couples shoot elegant photos in jeans against a long white wall — the subtraction is the style." },
        { q: "How do we look elegant if we're awkward in dressy clothes?", a: "Stop the walk before you start the shoot. Spend the first ten minutes in the outfit moving — stairs, doors, a real lap of the location — so the clothes become the evening instead of the costume. Awkwardness lives at the shoulder line, and it leaves when the feet get a slow job. Then the hem-correction frame is yours anyway; a small problem is the warmest thing in this style." },
        { q: "Do we need a fancy location for elegant engagement photos?", a: "You need a quiet one with lines. A library staircase at opening, a museum before the crowds, one honest email for a hotel lobby — the architecture composes you whether you're fancy or not. What kills the look is a grand location doing a tourist-hour shuffle; a public fountain with forty people in it costs an elegant gallery the entire frame." },
        { q: "What makes a photo look light and airy?", a: "A big soft light source and a slight overexposure — about two-thirds of a stop — pulled back at edit. North-facing windows, white walls, open shade on a bright day; the bounce is doing what the phrase is selling. Hard sun and a filter won't make it; size of light plus one deliberate stop up is the whole trick, and it's a photographer decision, not a location one." },
        { q: "Should our elegant photos include laughing?", a: "One set, kept on purpose. A gallery with zero laughter reads as a couple visiting a museum of themselves, and the eye knows it. The rule from a hundred galleries: two minutes of held warmth for every frame of genuine noise, and end the day on the noise — the relief frame at the wrap makes every held one believable." },
      ]},
      { type: "leadMagnet", title: "The Restraint Card", subtitle: "The twelve frames, the one-tempo rule and the exposure note for your photographer — on one card.", bullets: ["The six architecture frames, with scouting notes", "The minute-two rule for when coldness arrives", "The one candid: which set to end on and why"], cta: "Get the Restraint Card" },
      { type: "shop", section: "outfits", items: [
        { label: "Men's charcoal overcoat, clean-line cut (the one dark piece)", store: "Amazon", href: "#" },
        { label: "Hem weights / fashion tape kit (the small-problem insurance)", store: "Amazon", href: "#" },
        { label: "Tailored wool wrap, solid and untextured (for the stair rail hand)", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "The last elegant gallery I ever delivered closed the way all the good ones did: staircase held to minute three, the couple laughing at the ninth step because her shoe had come off, and the photographer — me, in the old life — still shooting. That frame was in the save-the-date. The held frames made the print room; the one candid made the people. That's the whole arithmetic of elegant engagement photos, and it adds up the same way at every wedding you'll be invited to this year." },
      { type: "keepReading", items: [
        { label: "Classic Engagement Photos", to: "/engagement-photo-ideas/classic-engagement-photos", note: "Timeless without the tempo rule" },
        { label: "Candid Engagement Photo Ideas", to: "/engagement-photo-ideas/candid-engagement-photo-ideas", note: "The one frame an elegant gallery keeps" },
        { label: "Black & White Engagement Photos", to: "/engagement-photo-ideas/black-and-white-engagement-photos", note: "The edit that finishes the look" },
      ]},
    ],
  },
];
