import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const ENGAGEMENT_CHECKLIST_POSTS: Post[] = [
  {
    slug: "engagement-photo-checklist",
    title: "The Engagement Photo Checklist: 12 Boxes to Tick Before You Shoot",
    seoTitle: "Engagement Photo Checklist: 12 Boxes to Tick",
    seoDescription:
      "An engagement photo checklist for the whole shoot: booking lead time, written permission, the run-of-show, and the boxes to tick after the cameras.",
    excerpt:
      "An engagement shoot fails quietly — a missed save-the-date deadline, a location that won't allow tripods, a couple that skipped lunch. Twelve boxes across four phases, from the booking to the file you print the cards off.",
    category: "ideas",
    date: "2026-11-19",
    dateModified: "2026-11-19",
    featuredImage: IMAGES.galleryRing,
    featuredAlt: "engagement photo checklist, the printed shot list beside two rings and the session date, worked through on a kitchen table",
    tags: ["engagement photo checklist", "booking lead time", "location permission", "the run-of-show", "save-the-date deadline", "what to bring"],
    author: harper,
    primaryKeyword: "engagement photo checklist",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["engagement session plan", "booking lead time", "location permission note", "the day-of run sheet", "save-the-date turnaround", "what to bring to a shoot"],
    searchIntent: "Informational",
    relatedPosts: ["elegant-engagement-photo-ideas", "romantic-engagement-photo-ideas", "save-the-date-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the ideas desk this planning sheet feeds" },
      { url: "/engagement-photo-locations", anchor: "the locations desk — book the room before you love the light" },
      { url: "/save-the-date-photos/save-the-date-photo-ideas", anchor: "why your shoot date is really a deadline problem" },
      { url: "/wedding-day-logistics/wedding-photo-checklist", anchor: "the wedding-day sibling of this list" },
      { url: "/engagement-photo-ideas/romantic-engagement-photo-ideas", anchor: "the frames your shot list should name" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryRing, overlayText: "12 Boxes, 4 Phases", pinTitle: "The Engagement Photo Checklist: 12 Boxes to Tick", pinDescription: "Booking lead time, written location permission, the day-of run-of-show, and the boxes to tick after the cameras — the whole engagement shoot planned in twelve lines. Save before you book." },
      { image: IMAGES.hero, overlayText: "Book Two Dates", pinTitle: "Why You Need a Rain Date Before You Need a Photographer", pinDescription: "Nobody's engagement gallery is ruined by the light; it's ruined by a rain date nobody held. The lead-time math, the permission note, and twelve checklist boxes. Pin it." },
      { image: IMAGES.indoor, overlayText: "Feed the Cards", pinTitle: "How Far Out Should You Book Engagement Photos?", pinDescription: "Work backward from the save-the-date deadline, not the wedding. The real lead-time math, what to bring, and the turnaround to confirm in writing. Save for planning." },
    ],
    blocks: [
      { type: "p", text: "An engagement shoot rarely fails loudly. It fails the way a card arrives two weeks late for the print shop, the way a beloved courtyard turns you away at the door over a tripod, the way one of you goes pale because nobody ate before the first frame. None of that is a talent problem; it's an unassigned box. This is the hidden checklist for the whole thing — twelve boxes across four phases, from booking the date to the file you actually print the save-the-dates off. The list is deliberately unglamorous, because the glamorous version is what the photographer does; the list is how you make sure there's a shoot to show up to." },
      { type: "h2", id: "how-far-out", text: "How Far Out to Start" },
      { type: "p", text: "Work backward from the save-the-date deadline, not from the wedding. If the cards go out six to nine months before the day, and the printer wants two weeks with files, and the photographer wants three to four weeks to edit, then the shoot itself needs to happen about two months before you hit send on the cards. That means booking the photographer six to eight weeks before you want to stand in front of the camera, because good photographers hold Saturdays months out. Couples who start from \"we should get some engagement pictures sometime\" book four days before they need the files, and then pay a rush fee to a printer who can't help them." },
      { type: "p", text: "The number that matters is the one on the back of the card's print order, not the one on your calendar. Do the arithmetic once, at the kitchen table, and the whole lead time falls out of it. In the 400-plus sessions I shot, the couples who did that math up front were the ones who never once asked me for a rushed set." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-things", text: "The Two Things That Sink a Shoot" },
      { type: "p", text: "Only two failures are common enough to build a list around, and both are preventable with a single email. The first is weather with no backup: you booked one date in one season and a storm has nowhere to move you, so the whole shoot and everything downstream slides. The fix is to hold two dates with the location before you tell anyone you're engaged to the world. The second is access: you fall for a shop, a park, or a rooftop, and show up to find it doesn't allow tripods, or needs a permit, or simply says no to a session on a Saturday. The fix is a written yes from the owner or the parks office, filed before the day. Everything else on this list is comfort; those two are survival." },
      { type: "keyTakeaways", items: [
        "Book 6–8 weeks ahead and work backward from the save-the-date print deadline.",
        "Hold two dates — a primary and a rain date — before you announce anything.",
        "Get the location's yes in writing; tripods and permits need a paper trail.",
        "Eat before the shoot; a lightheaded couple photographs as one, not two.",
        "Confirm the edit turnaround in writing so the cards can actually print.",
      ]},
      { type: "h2", id: "booking", text: "Boxes to Tick: Booking & Lead Time" },
      { type: "p", text: "The three decisions that have to be made in weeks, not hours." },
      { type: "list", items: [
        "Lock the photographer roughly 6–8 weeks before you want the shoot, and six to nine months out if the day is a peak Saturday.",
        "Choose two dates — the primary and the backup — and make sure the location will honor both.",
        "Get the session length and the edit turnaround in writing, so the finished files land before your cards are due.",
      ]},
      { type: "p", text: "The middle box — two dates — is the one people skip and the one that quietly guarantees the other eleven. A held backup costs nothing and takes weather off the list of things that can end your shoot, which is why it belongs in the booking phase and not the day-of scramble. Decide the rain date while you still care about the difference." },
      { type: "h2", id: "logistics", text: "Boxes to Tick: Logistics & Access" },
      { type: "p", text: "This is where a shoot lives or dies, and none of it happens on the day." },
      { type: "list", items: [
        "Send a short email for written permission — a couple with one camera is usually a yes; tripods, reflectors, and crews are a different ask.",
        "Scout at your real hour, not the golden internet hour, so you know the crowds and the light you'll actually have.",
        "Sort parking and pack the bag the night before, so the morning of has zero decisions left in it.",
      ]},
      { type: "p", text: "On the permission note, write like a guest and not a production: one handheld camera, forty quiet minutes, two drinks for the trouble. That sentence gets a yes at places a tripod and a tripod-bargain never would. The parks office is the exception worth chasing down early, since many public spaces want an inexpensive permit for anything that looks like a shoot, and learning that at the door is the priciest surprise on the whole list." },
      { type: "h2", id: "day", text: "Boxes to Tick: The Day Itself" },
      { type: "p", text: "Small, boring, and the difference between a gallery and a slideshow of discomfort." },
      { type: "list", items: [
        "Eat a real meal an hour out; hunger reads on the face long before it reads on the stomach.",
        "Bring the shot list, steamed outfits, a hair tie, water, snacks, and one backup of anything that can fail.",
        "Keep the final twenty minutes un-photographed for a plain walk, so the day ends on the two of you instead of on a pose.",
      ]},
      { type: "p", text: "The bag and the meal are the least glamorous boxes and the ones that most change the gallery. A hungry couple goes quiet and stiff inside ten minutes, and no amount of good light fixes a low-blood-sugar face. So eat something with protein, drink water you'll forget you're drinking, and let a packed bag mean the morning is only about arriving — the shooting itself is the photographer's burden, not the day's." },
      { type: "h2", id: "after", text: "Boxes to Tick: After the Cameras" },
      { type: "p", text: "The shoot isn't over when the camera does; the cards still have to exist." },
      { type: "list", items: [
        "Back up the proofs the day they arrive and tag the keepers before you try to choose anything.",
        "Order the save-the-dates off the confirmed edit, never off raw previews you'll later wish you hadn't printed.",
        "Write down what actually worked — the hour, the location, the order — because you'll rebuild this same list for the wedding day.",
      ]},
      { type: "p", text: "Tagging the keepers before choosing is the box that saves you from decision fatigue. Proofs arrive as a wall of near-identical frames, and reaching for the final set immediately tends to produce twelve safe, forgettable images. Mark the ones you'd put on a wall first, sit with that short list for a day, then cut down — the cards that come out of that pace look chosen rather than merely selected." },
      { type: "quote", text: "A save-the-date card has a print deadline folded into the back of it. That deadline, not your calendar, is the real reason the shoot date exists.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "order", text: "The Order of Operations" },
      { type: "p", text: "The twelve boxes only work in sequence, because each one buys the next. Here is the whole thing as one run-of-show, end to end, so you can see why the booking box is really a print-deadline box in disguise." },
      { type: "table", caption: "The engagement shoot, start to finish", headers: ["When", "The move", "Who owns it"], rows: [
        ["8–12 weeks out", "Book the photographer and hold two dates", "You both"],
        ["2 weeks out", "Written permission from the location; send the shot list", "One of you"],
        ["The night before", "Steam the outfits, pack the bag, charge everything", "You both"],
        ["The hour before", "Eat, park, find the light, breathe", "You both"],
        ["The week after", "Back up proofs, tag keepers, then order the cards", "You both"],
      ]},
      { type: "h2", id: "goes-sideways", text: "When the Plan Goes Sideways" },
      { type: "p", text: "It will, at least a little, and the checklist is what keeps a wobble from becoming a loss. Rain rolls in: that's the second date, not a crisis, and you'll wish you'd brought it if you didn't. The location changes its mind at the door: that's the written yes, and the reason you asked an owner rather than a barista. The light dies behind cloud: that's the scout-at-your-hour note, because you already know the room reads warm on gray days. And the couple goes cold and stiff in minute one: that's the meal, the bag, and the twenty un-photographed minutes at the end — the whole list exists to buy you permission to relax. The shoot that survives its own bad day is the one where the plan already accounted for it." },
      { type: "gallery", images: [
        { src: IMAGES.indoor, alt: "engagement photo checklist, the packed shoot bag with steamed outfits, water, snacks and the printed shot list" },
        { src: IMAGES.galleryLaugh, alt: "engagement photo checklist working, a couple relaxed at the last-minute scouting walk in their real session hour" },
        { src: IMAGES.casualCafe, alt: "engagement photo checklist, the lead-time math done at a kitchen table beside two dates and a print deadline" },
      ]},
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells couples is that the box everyone skips is the boring one: the written turnaround promise. Everyone remembers to hire a photographer and choose an outfit; almost no one gets in writing when the files are coming back, and that single blank is where save-the-date deadlines quietly die. So my first note on any engagement shoot is to email the photographer a sentence — \"we need finished files by the 14th for our cards\" — and let them reply yes or no. If it's a no, the whole plan shifts two weeks and nobody's heart breaks at a print shop." },
      { type: "p", text: "What I'd do differently: I used to plan sessions around the prettiest light and call it disciplined, then watch rain and crowds undo the whole morning. Now the list gets written first and the flattering light is a nice-to-have, not the load-bearing wall. Book two dates. Ask the owner in writing. Eat. Confirm the files. Keep the last twenty minutes for yourselves. Twelve boxes, and the shoot stops being a gamble and becomes an appointment you're glad you kept." },
      { type: "quote", text: "Nobody's engagement gallery is ruined by the light. It's ruined by a rain date nobody booked and a permission nobody asked for.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "How far in advance should we book engagement photos?", a: "Book the photographer six to eight weeks before you want to actually shoot, and hold your date with the location on top of that. If your save-the-dates go out six to nine months before the wedding, work backward from their print deadline, not the wedding itself. The shoot needs to finish, and the edit needs to land, weeks before the cards are due — that deadline is the whole schedule." },
        { q: "What happens if it rains on our engagement shoot day?", a: "If you planned for it, nothing — you use the second date. That's the entire fix: book a primary and a backup with the location before you tell anyone, and hold a room you could shoot in indoors if both dates turn. Couples who book one date gamble the whole downstream plan on the forecast. A rain date costs nothing to hold and saves everything that depends on the shoot." },
        { q: "Do we need permission to take engagement photos at a location?", a: "Usually yes, and it costs you one short email. Independent shops, parks, and rooftops each draw the line differently — most say yes to a couple with a handheld camera and no to tripods, reflectors, or a crew. Get the owner's written yes, check whether a public park needs a permit, and file it before the day. A verbal maybe from a barista is not permission." },
        { q: "What should we bring to an engagement photo shoot?", a: "The boring insurance: two steamed outfits, a hair tie, comfortable backup shoes, water, snacks, a lint roller, and a printed shot list. Charge anything that lights or plays music, and pack the bag the night before so the morning has no decisions left. Eat a real meal an hour out, because hunger shows on the face far sooner than it shows anywhere else." },
        { q: "How long until we get our engagement photos back?", a: "Plan on three to four weeks and confirm the number in writing before the shoot, because that turnaround is what lets your save-the-dates print on time. Ask for a few sneak-peak frames within days if you want to post the news sooner, but order cards off the finished, color-corrected edit rather than raw previews. A promised date in writing keeps the whole card deadline honest." },
      ]},
      { type: "leadMagnet", title: "The Engagement Shoot Checklist", subtitle: "All twelve boxes, the lead-time math, and the permission email you can copy — on one printable page for the two of you.", bullets: ["The 12 boxes, sorted by the four phases", "The backward math from your card deadline", "The two-line email that gets the location yes"], cta: "Get the Checklist" },
      { type: "shop", section: "props", items: [
        { label: "Handheld garment steamer, travel size (the night-before box)", store: "Amazon", href: "#" },
        { label: "Tabbed shot-list notebook, to run the day from", store: "Etsy", href: "#" },
        { label: "Insulated bottle and snack tin (the lightheaded-couple insurance)", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The most satisfying engagement gallery I ever shot was, on paper, the least likely to happen at all — booked late, over a storm season, at a rooftop that had said maybe and then, on a written follow-up, yes. We held a rain date, ate lunch early, packed a bag, and stood in a thin drizzle for the first ten minutes while the second date waited in reserve. It cleared, the light came soft, and the cards printed on time because we'd pinned the turnaround in an email nobody had to chase. That gallery wasn't won by the camera. It was won by twelve boxes ticked in the right order, months before anyone lifted a lens. The pretty frames are the photographer's job; showing up to a shoot that could actually happen is entirely yours." },
      { type: "keepReading", items: [
        { label: "Wedding Photo Checklist", to: "/wedding-day-logistics/wedding-photo-checklist", note: "The bigger list you'll rebuild from this one" },
        { label: "Save the Date Photo Ideas", to: "/save-the-date-photos/save-the-date-photo-ideas", note: "The deadline the whole list runs backward from" },
        { label: "Romantic Engagement Photo Ideas", to: "/engagement-photo-ideas/romantic-engagement-photo-ideas", note: "The frames to load onto the shot list" },
      ]},
    ],
  },
];
