import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const ANNOUNCEMENT_POSTS: Post[] = [
  {
    slug: "engagement-announcement-photo-ideas",
    title: "Engagement Announcement Photos: 12 Reveal Frames That Tell Everyone for You",
    seoTitle: "Engagement Announcement Photos: 12 Reveal Frames",
    seoDescription:
      "An engagement announcement is a message to everyone who wasn't there. 12 reveal frames, the ring-angle trick that fires a stone, and the who-first order.",
    excerpt:
      "The announcement is the one photo on this desk that looks straight at the camera, because you're showing it to people who weren't there. Twelve reveal frames, the trick that makes a ring actually sparkle, and the order to tell people in.",
    category: "ideas",
    date: "2026-11-12",
    dateModified: "2026-11-12",
    featuredImage: IMAGES.galleryRing,
    featuredAlt: "engagement announcement photos, the hand to the camera with the ring dead center and the room gone soft behind it",
    tags: ["engagement announcement", "ring reveal", "newly engaged", "just engaged", "the ring angle", "the who-first rule"],
    author: harper,
    primaryKeyword: "engagement announcement photos",
    cluster: "save-the-date-photos",
    lsiKeywords: ["newly engaged announcement", "just engaged reveal", "ring to camera frame", "the two-ring stack", "announcement flat-lay", "how to photograph a ring"],
    searchIntent: "Informational",
    relatedPosts: ["save-the-date-photo-ideas", "proposal-poses", "surprise-proposal-ideas"],
    internalLinks: [
      { url: "/save-the-date-photos", anchor: "the save-the-date desk this page belongs to" },
      { url: "/save-the-date-photos/save-the-date-photo-ideas", anchor: "the card you mail later, not the post you make now" },
      { url: "/save-the-date-photos/proposal-poses", anchor: "where the yes actually got captured" },
      { url: "/save-the-date-photos/surprise-proposal-ideas", anchor: "the secret that set this photo up" },
      { url: "/engagement-photo-ideas/romantic-engagement-photo-ideas", anchor: "the opposite brief — faces turned away from the lens" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryRing, overlayText: "Tell Everyone For You", pinTitle: "12 Engagement Announcement Photos That Do The Telling", pinDescription: "The announcement is the one photo that looks straight at the camera — you're showing people who weren't there. Twelve reveal frames, the ring-angle trick, and the who-first rule. Save it for the day you have news." },
      { image: IMAGES.galleryTwirl, overlayText: "One Ring Frame, One Face Frame", pinTitle: "The Announcement Post That Outperforms (And Why)", pinDescription: "Two frames tell it all: the ring aimed at us, and the two of you. Skip the forty angles. Twelve announcement setups plus the light that makes a stone sparkle instead of dot. Pin before you post." },
      { image: IMAGES.hero, overlayText: "Tell Mom Before The Feed", pinTitle: "The Announcement Etiquette Nobody Warns You About", pinDescription: "Parents first, in person or by phone, before a single story goes up — the ring angle and the who-first order. Twelve reveal frames plus what to caption. Save for planning." },
    ],
    blocks: [
      { type: "p", text: "An engagement announcement photo is the one image on this whole desk that is allowed — required, in fact — to look straight at the camera. Everything else here is about turning toward each other; this is about turning toward everyone who wasn't in the room. It's a message with a delivery target: your feed, your group chat, the relatives who want the picture before they ask what happened. That single fact decides every frame below. You're not catching a private moment; you're composing a public one, which means the ring points at the viewer, the faces read to the lens, and the whole photograph has to make sense to a stranger scrolling in a second. Twelve setups split between the frames that show the ring and the frames that show the two of you, plus the one light trick that makes a stone sparkle instead of a grey dot." },
      { type: "h2", id: "what-it-is", text: "What an Announcement Photo Actually Is" },
      { type: "p", text: "It's a broadcast, not a portrait. The difference is who the photograph is talking to. A portrait is for the couple; an announcement is for everyone else, and the couple is the subject of a message aimed outward. That's why the instinct to shoot it like any other engagement session produces an artful photo nobody can read — the ring is buried in a profile, the faces are turned at each other, and the actual news is invisible. In the hundreds of feeds I've watched, the announcements that land share one move: within a fraction of a second, a stranger knows what to say congratulations about." },
      { type: "p", text: "The good news is that the constraint makes the shoot easier. Once the job is legibility, you can stop chasing mood and start arranging the tell: a hand to the lens, two ring fingers together, the ring resting on whatever just happened. Every frame is a sentence that has to read small, on a phone, at a scroll's speed." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-decisions", text: "Before You Post: Two Decisions" },
      { type: "p", text: "One: what you're actually revealing. A ring-to-camera gallery and a couple-with-the-news gallery are different announcements — the first says the thing that happened, the second says the people it happened to, and the strongest post does both in two frames, never twelve of one. Two: the order you tell people. This is the decision that isn't even about photography and is the one that gets couples in trouble: the parents and the closest friends hear it first, in person or by phone, and the announcement goes out to everyone else after. Grandparents who find out from a story feel it for a year; the photo doesn't matter next to that." },
      { type: "keyTakeaways", items: [
        "The announcement is a broadcast, not a portrait — the camera is the audience, on purpose.",
        "A stranger should read the news in a second: the ring points at the viewer.",
        "One ring frame and one face frame out-post a dozen of either.",
        "Tell parents and closest friends first, by voice; the feed goes out after.",
        "A ring needs a 45° angle to the light and no flash, or it photographs as a dot.",
      ]},
      { type: "h2", id: "six-ring", text: "The Six Frames That Show the Ring" },
      { type: "p", text: "These are the tell-it-plain shots, aimed straight at whoever's reading. The news has to be unmistakable, so the ring is the subject and the background is allowed to disappear." },
      { type: "list", items: [
        "The hand to the camera — hers extended toward the lens, his over it, the ring dead center and everything behind soft; this is THE announcement image because the viewer is the one being shown.",
        "The two-ring stack — both hands' ring fingers pressed together, four hands entering the frame and no faces; the whole message is in two matching stones.",
        "The receipt — the ring resting on the check for the dinner it happened at, a corner of the date showing; the paperwork of the night makes the reveal specific.",
        "The dashboard — the ring on the dash, a seatbelt cutting the frame, the parking-lot glow; the most ordinary stage sells that it just happened.",
        "The gag mug — the ring hooked on a handle reading something ridiculous, shot flat toward the camera; the news and a wink in one frame.",
        "The envelope — the ring on a card with a date or a single word on it, the lettering aimed at us; the announcement addressed, literally, to whoever's looking.",
      ]},
      { type: "h2", id: "six-couple", text: "The Six Frames That Show the Two of You" },
      { type: "p", text: "The ring tells the news; the faces make someone care about it. These smuggle the reveal into a real moment, so the post reads as a couple and not a jewelry ad." },
      { type: "list", items: [
        "The facing-outward hold — foreheads together but the ring hand raised between them toward the camera; the intimate and the announcement in one frame.",
        "The toast to the lens — two glasses clinked straight at us, the ring hand unmistakable, a quiet cheer you can post with one line.",
        "The back hug, arms up — his arms around her waist, her hands lifted into the top of the frame with the ring catching the light; the reveal folded into an embrace.",
        "The sidewalk spin — caught mid-twirl, one hand flung up to the camera; the kinetic version of the word yes.",
        "The doorway reaction — the moment a parent or a best friend sees it, hands framing the ring, faces doing the job; the announcement witnessed, then posted.",
        "The flat-lay of the day — the ring, the phone, the napkin, the flowers, the note, laid out top-down; the no-face announcement, the group-chat screenshot made physical.",
      ]},
      { type: "p", text: "Twelve frames, one rule over the set: an announcement post is not a gallery, it's a headline with a byline. One ring frame and one face frame say everything, and the rest of the day's photos are for the two of you, not the feed." },
      { type: "quote", text: "A save-the-date is a letter to your guests. The announcement is a shout to everyone who wasn't in the room — different photograph, different volume.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "the-ring-angle", text: "The One Trick That Makes a Ring Sparkle" },
      { type: "p", text: "A ring photographed straight-on reads as a grey smudge, because you're seeing the flat face of the setting with no light coming off the stone. The fix is angles and light, and it takes ten seconds: turn the finger so it catches the biggest light in the scene at roughly 45°, pull the background a few feet back so it melts, shoot wide open for a shallow focus, and never — ever — use the flash, which flattens the very facet you're trying to fire. Keep the arm crossing the frame so the eye travels along it to the stone, and wipe the ring first; a smudged rock sparkles at nobody. In most of the 400-plus sessions I shot, the single strongest ring frame was made by angling the hand, not by finding a better location." },
      { type: "table", caption: "The announcement against the three photos it gets mixed up with", headers: ["Photo", "It's a message to", "The tell"], rows: [
        ["Announcement", "The world — your feed, your group chats", "Legible in a second; the ring is aimed at whoever's scrolling"],
        ["Save-the-date card", "Guests, months out", "Room for names and a date; it's printed and mailed, not posted"],
        ["Proposal photo", "The couple, and the story", "One knee, one yes, shot to remember it"],
        ["Portrait session", "The two of you", "Faces turned at each other instead of at the lens"],
      ]},
      { type: "h2", id: "goes-wrong", text: "When the Reveal Goes Wrong" },
      { type: "p", text: "Four ways, and the first is the one that hurts. You post before the people who matter have heard it — that's not a photo problem, it's an apology waiting to happen, and no ring angle fixes a mother who learned from a comment thread. Then the ring-obsessed gallery: twenty frames of one hand, which reads as an ad for the stone and not news about the couple; the answer is the face frame. Third, the over-produced reveal — garland, a matching banner, a ring box staged like a product shot — which can look like you rehearsed the engagement; keep exactly one of these and shoot the rest loose. And last, the ring that goes soft because the phone focused on the face instead of the hand: tap to focus on the stone, or shoot the ring frames on their own pass while the light's right." },
      { type: "gallery", images: [
        { src: IMAGES.galleryRing, alt: "engagement announcement photos, the two-ring stack, four hands and no faces, the whole message in two matching stones" },
        { src: IMAGES.classicDip, alt: "engagement announcement photos, the toast to the lens, two glasses and a ring hand aimed straight at the camera" },
        { src: IMAGES.hero, alt: "engagement announcement photos, the doorway reaction, a parent's hands framing the ring as the news lands" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About the Announcement" },
      { type: "p", text: "They aim it at the wrong audience — shooting it like a romantic session when the job is to be legible to strangers on a phone. They hide the news in a profile or a wide landscape, then wonder why the post gets \"wait, what happened?\" comments. They treat it like the wedding photo and over-invest, when a good announcement is honestly one afternoon and one good phone frame away. And, most of all, they let the calendar slip past the people: the urge to post the second it's real overrides the phone call that should come first. The photo can wait an hour. A grandmother finding out from a screen can't be undone." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells you is that the announcement photo and the ring photo are usually two different frames, and couples who force one image to do both end up with neither. So I separate the pass: give me ten minutes of just the ring — the hand to the lens, the two-ring stack, the ring on whatever it happened on — and then put the camera away from the stone entirely and shoot the two of you with the news on your faces. The post that outperforms is always one from each column: a ring a stranger can read, and a face a stranger can feel. My favorite announcement I ever shot was one clean ring frame and one blurry, laughing, badly-framed hug; the ring got the likes, the hug got the comments." },
      { type: "p", text: "What I'd do differently: I used to over-direct the reveal hand — chin, fingers, tilt, repeat — and produced a polished, dead product shot. Now I aim the light instead of the fingers, set the couple down with the ring near a window, and let them handle it; the small adjustments a person makes while showing a ring to another person are the whole spark, and they never look directed. Twelve frames, one 45-degree trick, and one phone call before the post — because an announcement is the shortest photograph to make and the easiest to regret, and the only one where who-told-whom-first matters more than how it looks." },
      { type: "quote", text: "You don't post a kiss. You post the ring that proves it, and the face that proves you meant it.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What's the difference between an engagement announcement photo and a save-the-date photo?", a: "The audience and the timing. An announcement is a message to everyone who wasn't in the room, posted within days, and it aims the ring at the camera. A save-the-date is a card for your invited guests, mailed months out, with room for names and a date. Shoot the announcement to be legible on a phone; design the save-the-date to be printed. Same couple, completely different volume." },
        { q: "Do we have to show the ring to announce our engagement?", a: "No, but it's the fastest read a stranger gets. Without a ring in frame, the post has to carry a caption or a prop to explain itself, and people scroll past a happy couple guessing at the news. The strongest announcements pair one ring frame with one face frame, so the fact and the feeling both come through." },
        { q: "Who should we tell before posting the announcement?", a: "Parents, siblings, grandparents and close friends — by voice, not in a group text — before anything goes up. The order is immediate family first, then the people you'd be hurt to reach later, then the feed, ideally with a day's buffer. A great photo is small next to a parent learning of your engagement from a comment thread." },
        { q: "How do you photograph a ring so it actually sparkles?", a: "Angle the finger about 45° toward the biggest soft light so a facet catches it, focus on the stone and not the face, shoot wide open to blur the background, and skip the flash, which flattens the sparkle you're chasing. Wipe the ring clean, and let the arm lead the eye to it. It's the angle and light that make the fire, not the carat weight." },
        { q: "What should we write on an engagement announcement?", a: "Keep it shorter than you want to. A date, the two words we're engaged, or a single honest line about the answer does more than a paragraph, because the photo is already telling the story. Resist explaining the whole proposal in the caption — that's for the comments and the wedding. One clean line, one good ring frame, one face frame, and press post." },
      ]},
      { type: "leadMagnet", title: "The Reveal Kit", subtitle: "The twelve frames, the 45-degree ring note for your photographer, and the who-first order — one card, one caption.", bullets: ["The six ring frames and six couple frames", "The light-and-angle trick that fires a stone", "The tell-family-first order, before the feed"], cta: "Get the Reveal Kit" },
      { type: "shop", section: "props", items: [
        { label: "Matte \"Just Engaged\" or \"She Said Yes\" hand card, one color", store: "Etsy", href: "#" },
        { label: "Two champagne flutes (for the toast-to-the-lens frame)", store: "Amazon", href: "#" },
        { label: "Letterpress date card, to lay beside the ring in the flat-lay", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "My favorite announcement gallery I ever delivered was almost nothing: a single hand to the camera by a window, the ring catching one clean spark, then a phone frame of the two of them laughing too close to the lens. They'd posted the ring and captioned it with a date, and a hundred people, most of them strangers, said the same word back. That's the whole job. Point the news at whoever's watching, put one real face beside it so they care, and make the phone call before the post. The picture does the telling; the order you tell people in is the part you'll still be glad about in a year." },
      { type: "keepReading", items: [
        { label: "Save the Date Photo Ideas", to: "/save-the-date-photos/save-the-date-photo-ideas", note: "The card you mail months from now" },
        { label: "Ring Engagement Photo Poses", to: "/engagement-photo-poses/ring-engagement-photo-poses", note: "The hand-to-camera, in pose form" },
        { label: "Romantic Engagement Photo Ideas", to: "/engagement-photo-ideas/romantic-engagement-photo-ideas", note: "The opposite brief — faces away from the lens" },
      ]},
    ],
  },
];
