import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const FIRST_LOOK_POSTS: Post[] = [
  {
    slug: "first-look-photos",
    title: "First Look Photos: 10 Frames That Make the Quiet Minute Land",
    seoTitle: "First Look Photos: 10 Frames That Actually Land",
    seoDescription:
      "First look photos that feel like the first look: who to include, the 10-minute timeline, where to stand, and the 10 frames that make the quiet minute land.",
    excerpt:
      "The first look lasts about ten real minutes, and the photographs you'll treasure from it come down to how those minutes are set up — not posed. I've shot dozens of them, and the ones that land all share the same skeleton: a private place, a clean sightline, a plan for the hands, and twenty minutes of buffer nobody schedules against. Here are 10 frames, the timeline, and the logistics that make the quiet minute read on camera.",
    category: "tips",
    date: "2026-09-08",
    dateModified: "2026-09-08",
    featuredImage: IMAGES.classicDip,
    featuredAlt: "first look photos, groom covering his face as the bride-to-be drops her hands behind him",
    tags: ["first look", "wedding day", "candid", "timeline", "logistics", "ceremony prep"],
    author: harper,
    primaryKeyword: "first look photos",
    cluster: "wedding-day-logistics",
    lsiKeywords: ["wedding first look", "first look timeline", "day of photo plan", "groom reaction", "private moment", "ceremony day logistics"],
    searchIntent: "Informational",
    relatedPosts: ["wedding-photo-checklist", "engagement-photo-albums", "camera-shy-engagement-poses"],
    internalLinks: [
      { url: "/wedding-day-logistics/wedding-photo-checklist", anchor: "the full day-of timeline" },
      { url: "/engagement-photo-poses/camera-shy-engagement-poses", anchor: "camera-shy" },
      { url: "/engagement-photo-ideas", anchor: "engagement photo ideas" },
      { url: "/engagement-photo-prints/engagement-photo-albums", anchor: "the album it earns" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.classicDip, overlayText: "Ten Minutes, One Look", pinTitle: "First Look Photos: 10 Frames That Land", pinDescription: "The private place, the 10-minute timeline, and the exact frames — including the two people usually forget to photograph. Save this before your wedding morning planning call." },
      { image: IMAGES.galleryRing, overlayText: "His Face Is the Photo", pinTitle: "The Groom Reaction Shot: How to Actually Get It", pinDescription: "Where the photographer stands, where the best man goes, and why you rehearse the hands-over-eyes but never the moment. The first look reaction, engineered. Save it." },
      { image: IMAGES.hero, overlayText: "Quiet Beats Pretty", pinTitle: "Pick Your First Look Spot by Sound, Not Views", pinDescription: "A dead-end corridor with no audience beats a grand staircase with one. The logistics rule behind every great first look photo. Pin this for your venue walk-through." },
    ],
    blocks: [
      { type: "p", text: "Here's the thing about first look photos: the moment is ten minutes long, and almost all of it can be scheduled. Not the feelings — nobody controls those, thank God — but everything around them. The place, the sightline, who stands where, what the hands do in the first three seconds. In roughly six of ten weddings I shot, the couple told me afterward that the first look was the calmest moment of their entire day. The photographs prove it, because calm is photogenic. This page is the setup: a private spot, a tight timeline, and 10 frames that make the quiet minute land on camera." },
      { type: "keyTakeaways", items: [
        "The first look is a logistics problem: pick the spot by sound and sightlines, not by scenery.",
        "Give it a real 20-minute block — 10 minutes of buffer, 10 minutes of moment.",
        "Photograph both faces. The bride's reaction is the frame most first looks lose.",
        "Decide who's included before the day: just the two of you, or a family peek after.",
        "End it on purpose — with a walk, not a drift — so the ceremony still feels like a reveal.",
      ]},
      { type: "h2", id: "why-logistics", text: "Why the First Look Is a Logistics Decision" },
      { type: "p", text: "A first look works when the setup protects it. The whole point is privacy — two people seeing each other before the aisle without an audience — and privacy is a scheduling and floor-plan problem. A gorgeous courtyard with a café wall beside it fills with guests, vendors, and one very determined uncle in ninety seconds; a boring corridor with a closed door at each end stays empty all morning. Choose the spot by how quiet it can be, not by how pretty it photographs; the emotion is the picture, and it doesn't need scenery." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "who-is-included", text: "Who Should Be in the First Look" },
      { type: "p", text: "Default answer: just the two of you, photographer at a distance. The moment is fragile and every added face changes how people perform. That said, two variants are worth planning deliberately if they fit your family." },
      { type: "list", items: [
        "Just the couple — the standard. Rawest reactions, cleanest frames, easiest to schedule.",
        "Couple + immediate family peek — 10 minutes of private reaction first, then parents come around for a group frame. This is the compromise that almost never goes wrong.",
        "Split first looks — each person sees their parents first, then the couple. Beautiful, but budget an extra fifteen minutes.",
      ]},
      { type: "h2", id: "setting-the-scene", text: "Setting the Scene: Where, When, and Where Everyone Stands" },
      { type: "p", text: "Three decisions make the frame: the spot, the sightline, and the position of every human on set. The bride stands with her back to where the groom will approach — with a clean wall or greenery behind her shoulders, not a dumpster. The groom stops at a marked spot (literally chalk it, or plant a bag) far enough back that the walk toward her is part of the shot. The photographer shoots from over the groom's shoulder so her face arrives in frame as his does." },
      { type: "table", caption: "First look spot: what to check on the walk-through", headers: ["Check", "Pass", "Fail"], rows: [
        ["Sound", "Doors at both ends, no foot traffic", "Lobby, café wall, catering path"],
        ["Sightline", "10–20 ft of clear approach", "Corners, stairs, anything you must dodge"],
        ["Background", "Plain or greenery behind shoulders", "Signage, bins, mirrors"],
        ["Light", "Open shade or soft window", "Hard overhead noon sun"],
        ["Backup", "Second quiet spot 60 sec away", "One option and a weather risk"],
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "the-10-frames", text: "The 10 Frames" },
      { type: "p", text: "Ten frames that fill a first look in real order — from the setup to the walk away. They're not poses; they're moments you can guarantee if you plan the ten minutes around them." },
      { type: "h3", id: "frame-cover", text: "1. The Cover" },
      { type: "p", text: "She arrives, hands go up to cover his eyes, and the camera gets the two of them already a team. It's the only frame with zero performance pressure — they're busy, not aware. Harper's Tip: let her cover his eyes herself instead of the photographer doing it. Her hands on his face is the story." },
      { type: "h3", id: "frame-turn", text: "2. The Turn" },
      { type: "p", text: "He turns around and the world ends for about four seconds. Shoot continuous here — the micro-sequence (the blink, the jaw, the smile breaking) is where the photo lives. I keep this frame at 70mm or tighter on my body so the couple never has to perform for a wide lens." },
      { type: "h3", id: "frame-his-face", text: "3. His Face, Held" },
      { type: "p", text: "After the initial reaction there's usually a second where his face does something truer than surprise — pride, disbelief, a wobble. Most photographers are already panning to her. Stay a beat longer. This is the frame grooms cry at." },
      { type: "h3", id: "frame-her-face", text: "4. Her Face Too" },
      { type: "p", text: "The frame everyone forgets: she's been watching him watch her, and when she finally sees her own effect, that's its own reaction. Step in front and get it before the hug swallows the scene. Half of first look coverage is equal opportunity faces." },
      { type: "h3", id: "frame-hug", text: "5. The Hug" },
      { type: "p", text: "Wide, this time. The full bodies collapsing together tell the story — her train fanning, his hands finding her back. Let it last as long as it lasts; it's the longest single sound on the wedding day, usually. No direction, no words." },
      { type: "h3", id: "frame-details", text: "6. The Detail Handoff" },
      { type: "p", text: "While they talk it out, drop to the small stuff: the cufflinks his mom pressed on him, her grandmother's earrings catching light, the ring hand resting on the ring hand. These frames carry the family logistics your checklist spent weeks placing — now they photograph." },
      { type: "h3", id: "frame-family", text: "7. The Family Peek" },
      { type: "p", text: "If you planned one, this is when parents come around. Do it after the couple has had their ten minutes, never before — and pre-position exactly where each person stands so the moment is hugs and frames, not choreography." },
      { type: "h3", id: "frame-quiet", text: "8. The Quiet After" },
      { type: "p", text: "Sit them down — steps, a bench, a wall — for two minutes of just being married already. The fidgeting drops, the shoes come off in frame, and you get the calmest portraits of the entire day. This is my favorite frame and it costs nothing but a bench." },
      { type: "h3", id: "frame-laugh", text: "9. The Laugh" },
      { type: "p", text: "By minute eight, the tension has flipped to giggles — a bad joke, a smeared lip gloss, the absurdity of the morning. Chase it. The laughing frame is what makes the album feel like your day instead of a styled shoot." },
      { type: "h3", id: "frame-walk", text: "10. The Walk-Away" },
      { type: "p", text: "End on purpose: they walk off together toward the ceremony and the camera catches backs of heads and a train. A deliberate exit protects the aisle later — the ceremony still reads as a reveal for your guests, because you closed the private chapter before opening the public one." },
      { type: "quote", text: "You don't schedule a first look to get photos. You get photos because you scheduled everything else and let the moment be unscheduled.", cite: "Harper, from 400+ sessions" },
      { type: "gallery", images: [
        { src: IMAGES.classicDip, alt: "first look photos of the groom mid-turn, hands still up, eyes finding her for the first time" },
        { src: IMAGES.galleryRing, alt: "first look photos detail frame, cufflinks his mother pinned catching window light" },
        { src: IMAGES.hero, alt: "first look photos, the couple seated on quiet steps, heads together after the hug" },
      ]},
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "timeline", text: "The 20-Minute First Look Timeline" },
      { type: "p", text: "Give the moment twenty real minutes on the day-of schedule, and hide the buffer honestly: tell everyone the photo buffer is fifteen, then actually let the couple have their ten undisturbed. Here's the block that has worked every time: minute 0, she's set and his approach is walked once; minute 2, he arrives and the cover happens; minutes 3–6, the reaction frames (turn, faces, hug); minutes 7–10, quiet and details; minute 12, family peek if it's planned; minute 15, the laugh and the walk-away; minute 18, everyone is moved before the corridor fills." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They build the first look around the venue's prettiest backdrop and it fills with people — the quietest rooms are quiet because everyone's at catering. They zero-buffer the timeline, which forces the photographer to call cut on the hug mid-hug. They rehearse the hands-over-eyes for hours and plan nothing for the two seconds after — the plan should cover the approach, not the reaction, because the reaction is the only part you can't practice. And they bring the whole wedding party as audience, which turns a private minute into a performance. You get one take of real. Protect the room." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The strongest first look frames I've made came from the boring hallway with the closed door, not the grand staircase with the views. The moment outruns scenery every time, and a room that can stay empty beats a room that photographs pretty and fills fast. If your only quiet option is genuinely ugly, shoot tighter — faces and hands don't know what wall they're in front of." },
      { type: "p", text: "What I'd do differently after all these years: I used to start shooting the approach from far away to get the wide. Now the photographer stands within arm's reach of her from minute one — the frames that matter happen in a three-foot zone the instant her hands drop. Distance is for the hug; intimacy is a focal-length decision made before anyone arrives." },
      { type: "quote", text: "A first look is two people and ten minutes. Everything else on this page is just clearing the room so those ten minutes can happen.", cite: "Harper" },
      { type: "faq", items: [
        { q: "How long should a first look take on the wedding day schedule?", a: "Block 20 minutes and protect them. The genuine moment is about ten — cover, turn, faces, hug, quiet, walk-away — and the other ten is travel, one approach rehearsal, and the buffer that keeps nobody watching the clock. Under-blocked first looks are visible in the frames: the last ten percent of the reaction gets cut off by the next timeline item." },
        { q: "Where is the best place for a first look at a venue?", a: "The quietest spot with a clear ten-to-twenty-foot approach — a closed-end corridor, a garden gate away from foot traffic, an empty classroom. Pick by sound and sightlines, not scenery; emotion is the picture and it doesn't need a famous backdrop. Walk it the morning of the wedding, because venue traffic patterns shift once catering arrives." },
        { q: "Should we do a first look if we want the aisle to feel like a surprise?", a: "A first look moves the reveal to a private hour and replaces the public one with a shared walk — you enter the aisle already married to the moment. If the surprise is sacred to you or your families, skip it and give the ceremony its full weight instead; either choice photographs well, and the album shows which felt like you." },
        { q: "What should the groom do with his hands during the first look?", a: "Nothing choreographed — that's why you plan the ten seconds before. His hands go to his face, her shoulders, or her waist depending entirely on the reaction; forcing a pose kills it. What you can set: shoes on or off, boutonniere pocketed, and where he stops on the mark, so the walk toward her is the only motion the frame carries." },
        { q: "Can we include our parents or kids in the first look?", a: "Yes — with a sequence. Give the couple ten private minutes first, then bring family around for a group frame while the faces are still soft. Splitting the order (parents first) is lovely too but costs fifteen extra minutes and a second spot. What never works is a crowd at the reveal; that's a performance, not a first look." },
        { q: "What happens if it rains on the first look?", a: "You need a Plan B inside the same building, scouted on the walk-through and kept on the schedule — not improvised during a downpour, when every dry corner is suddenly claimed. A narrow stairwell landing with a window works beautifully: soft light, zero audience. The reaction photographs identically in any weather." },
      ]},
      { type: "leadMagnet", title: "The First Look Planning Card", subtitle: "The spot checklist, the 20-minute block, and the frame list — one card for you and your photographer.", bullets: ["Walk-through checklist for the quiet-spot hunt", "The 20-minute timeline, minute by minute", "The 10 frames your photographer can plan around"], cta: "Get the First Look Card" },
      { type: "shop", section: "props", items: [
        { label: "Ceremony-day timeline prints", store: "Etsy", href: "#" },
        { label: "Soft light reflector (photographer's call)", store: "Outdoor", href: "#" },
        { label: "Wedding day emergency kit", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The last one I planned this way was a Tuesday courthouse wedding — tile walls, no views, one door propped open at each end so nobody could wander in. He turned, she watched his face watch her, and somewhere in minute six he said something so quiet the camera missed the words but got the answer. They sat on the steps after, heads together, gone from the day. The corridor is in every print, which is the point: the place was a wall, and the picture was them." },
      { type: "keepReading", items: [
        { label: "Wedding Day Checklist: 47 Photo & Logistics Details", to: "/wedding-day-logistics/wedding-photo-checklist", note: "Where the first look block actually fits on the timeline" },
        { label: "Camera-Shy Engagement Poses", to: "/engagement-photo-poses/camera-shy-engagement-poses", note: "The task method behind calm, watched faces" },
        { label: "Engagement Photo Albums", to: "/engagement-photo-prints/engagement-photo-albums", note: "What the day-of frames deserve to live in" },
      ]},
    ],
  },
];
