import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const HOLIDAY_POSTS: Post[] = [
  {
    slug: "holiday-engagement-photos",
    title: "Holiday Engagement Photos: 15 Ways to Capture the Season (Without the Cheese)",
    seoTitle: "Holiday Engagement Photos: Festive Without the Cheese",
    seoDescription:
      "Holiday engagement photos that feel like your December, not a greeting card: your traditions, colors that never date, and festive light without the kitsch.",
    excerpt:
      "They wanted Christmas photos — just not the matching-sweater kind. The session that worked captured their real December 24th: hot chocolate, their tree, their kitchen. Here are 15 ways to make holiday engagement photos feel like your season, not a catalogue.",
    category: "ideas",
    date: "2026-09-09",
    dateModified: "2026-09-09",
    featuredImage: IMAGES.hero,
    featuredAlt: "holiday engagement photos couple with warm string lights and cocoa in december",
    tags: ["holiday", "christmas", "winter", "festive", "traditions"],
    author: harper,
    primaryKeyword: "holiday engagement photos",
    cluster: "engagement-photo-ideas",
    relatedPosts: ["winter-engagement-photo-ideas", "classic-engagement-photos", "black-and-white-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-ideas/winter-engagement-photo-ideas", anchor: "winter engagement photo ideas" },
      { url: "/engagement-photo-ideas/romantic-engagement-photo-ideas", anchor: "romantic engagement photo ideas" },
      { url: "/engagement-photo-ideas/classic-engagement-photos", anchor: "classic engagement photos" },
      { url: "/engagement-photo-ideas/black-and-white-engagement-photos", anchor: "black and white engagement photos" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.hero, overlayText: "Festive, Not Cheesy", pinTitle: "Holiday Engagement Photos: Festive Without the Cheese", pinDescription: "Your real December, photographed: traditions, warm colors that never date, and festive light that doesn't need a single ugly sweater. Save these 15 ideas." },
      { image: IMAGES.classicDip, overlayText: "3 Colors That Never Date", pinTitle: "The 3 Holiday Colors That Never Date", pinDescription: "Burgundy, pine green, matte gold — the holiday palette that looks as good in twenty years as it does now. Skip the neon red and green. Save the palette." },
      { image: IMAGES.galleryRing, overlayText: "Your Traditions, Photographed", pinTitle: "Your Traditions, Photographed: Holiday Ideas That Work", pinDescription: "Hot chocolate rituals, cookie baking, tree decorating — the holiday engagement photos that feel like your family, not a greeting card. Save your plan." },
    ],
    blocks: [
      { type: "p", text: "They told me they wanted Christmas photos — then, quickly, that they didn't want to look like everyone else's Christmas photos. No matching sweaters. No posing stiffly in front of a decorated tree. So I asked what their December actually looks like, and it turned out their December was perfect: hot chocolate on the 24th, the same recipe his mother taught him, their tree with the ornaments they've collected for years, the kitchen that smells like cookies by mid-afternoon. That's where we shot. Two hours later they had holiday photos that looked like their family, not a catalogue — and not a single matching sweater in sight. Holiday engagement photos fail when they try to be Christmas in general. They work when they're your Christmas, specifically." },
      { type: "keyTakeaways", items: [
        "Holiday ≠ kitsch — shoot your real traditions, not the greeting-card version.",
        "Deep burgundy, pine green and matte gold never date; neon red and green do.",
        "Warm light is the whole holiday look: candles, lanterns, string lights.",
        "One or two festive touches beat a fully decorated set.",
      ]},
      { type: "h2", id: "why-holiday-photos-fail", text: "Why Holiday Photos Often Fail (and How Yours Won't)" },
      { type: "p", text: "Three traps catch almost every couple trying for festive photos. First, the clichés — matching sweaters, stiff poses in front of the tree, the forced jolly laugh. They read as Christmas in general, which means they could be anyone's, which means they're no one's. Second, the neon colors: bright primary red and fluorescent green photograph loud and date fast, while the real colors of the season — deep burgundy, pine green, matte gold, ivory — look as good in twenty years as they do now. Third, over-decorating: a set drowning in ornaments and garland stops being about the two of you. The fix for all three is the same: photograph what you actually do in December, in the colors the season actually wears, with one or two festive touches instead of fifty." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "the-15-ways", text: "The 15 Ways" },
      { type: "h3", id: "burgundy-pine", text: "1. Burgundy + Pine Green (Deep, Not Neon)" },
      { type: "p", text: "The season's real palette is deep, not bright: burgundy against pine green, both grounded in cream or charcoal. These tones photograph rich against bare branches and grey skies, and they'll still look like the season in twenty years — neon red and green will look like a costume by then." },
      { type: "h3", id: "matte-gold", text: "2. Matte Gold + Ivory (Elegant, Not Glitter)" },
      { type: "p", text: "Matte gold against ivory reads as candlelight and quiet, not party glitter. One gold touch — a wrap, a ribbon, a single strand of lights — against ivory knits gives the whole set a warm, expensive calm without a single sparkle." },
      { type: "h3", id: "navy-burgundy", text: "3. Navy + Burgundy (Sophisticated, Not Primary)" },
      { type: "p", text: "For couples who find red and green too loud, navy and burgundy are the sophisticated answer: deep, wintery, and impossible to date. Against a stone wall or bare trees, the combination looks like a classic film still." },
      { type: "h3", id: "hot-chocolate", text: "4. Your Hot Chocolate Ritual" },
      { type: "p", text: "If there's a drink you make every December — his mother's recipe, the cocoa with the extra marshmallow he insists on — that's the photo. Two mugs, your kitchen, steam in the light from the window. It's the tradition itself, not a prop pretending to be one." },
      { type: "h3", id: "cookie-baking", text: "5. Cookie Baking (Your Recipe, Your Mess)" },
      { type: "p", text: "Flour on the counter, one of you tasting the dough, the recipe card that's been in the family for years. Shoot the doing, not the finished cookies — the mess is the memory, and nobody's checking whether the cookies are perfect." },
      { type: "h3", id: "tree-decorating", text: "6. Tree Decorating (Your Tree, Your Ornaments)" },
      { type: "p", text: "Not a styled tree — your tree, with the ornaments you've collected for years, the crooked one included. Shoot the reaching, the debating, the stepping back to look. The ornaments tell your story; the tree is just the frame." },
      { type: "h3", id: "gift-wrapping", text: "7. Gift Wrapping (Your Method, Your Paper)" },
      { type: "p", text: "One of you is precise with the tape; the other is chaos with the ribbon. That's a two-person story with built-in comedy, and the wrapping paper adds color without a single decoration on set. Shoot from across the table." },
      { type: "h3", id: "tree-farm", text: "8. The Tree Farm (Not the Living-Room Tree)" },
      { type: "p", text: "Choosing the tree is its own December tradition, and a tree farm gives you rows of green against winter light with room to breathe. Carry the chosen tree to the truck together — the carrying is the photo, every time." },
      { type: "h3", id: "holiday-market", text: "9. The Holiday Market (Not the Mall)" },
      { type: "p", text: "A real holiday market — the little wooden stalls, the string lights, the cold air — has warmth a shopping mall can't fake. Wander it slowly with a warm drink, and let the lights blur into bokeh behind you." },
      { type: "h3", id: "cabin-retreat", text: "10. The Cabin Retreat (Not the Decorated House)" },
      { type: "p", text: "A rented cabin with a wood stove and a window full of trees beats a fully decorated house for photos, because it's quiet. Wood smoke, wool blankets, one lamp on — the cabin gives you cozy without trying." },
      { type: "h3", id: "snowy-park", text: "11. The Snowy Park (Not the Garland Garden)" },
      { type: "p", text: "A park after snowfall is the simplest festive set there is: white ground, dark branches, soft grey light. No decorations needed, and the snowflakes catching the light do the festive work all by themselves." },
      { type: "h3", id: "coordinated-not-matching", text: "12. Coordinated, Not Matching" },
      { type: "p", text: "Two or three tones shared between you — burgundy on one, pine on the other, cream underneath both — reads as a couple, not a uniform. Matching sweaters say 'we planned a bit'; coordinated tones say 'we just are this way.'" },
      { type: "h3", id: "minimal-festive-props", text: "13. Minimal Festive Props (One, Not Ten)" },
      { type: "p", text: "One branch of pine, one candle, one strand of lights — a single festive touch reads as intention. A set drowning in garland and ornaments reads as a set, and the two of you become scenery in your own photos." },
      { type: "h3", id: "warm-light", text: "14. Warm Light (Lanterns, Candles, String Lights)" },
      { type: "p", text: "Warm light is the entire holiday look. A lantern in hand, candles on the sill, a strand of warm-white lights behind you — any one of them turns an ordinary December evening into the season. Cool white LED reads as office; stay warm, around 2700K." },
      { type: "h3", id: "holiday-black-white", text: "15. Black & White (The Season, Minus the Dates)" },
      { type: "p", text: "When in doubt, go black and white. Monochrome strips the colors that date a holiday photo and leaves only the two of you and the light — a December photo that looks as good in fifty years as it does the week you took it." },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "The matching sweaters are the obvious one — they photograph as a bit, and a bit is funny for a year and dated in five. The decorated-tree backdrop is the second: it's the most clichéd frame in holiday photography, and the couple in front of it always looks posed. The neon red and green is third — they're loud on camera and read as costume colors, not season colors. And the deepest miss is ignoring your actual traditions in favor of generic festive ones: the couple whose December is hot chocolate and cookie baking will always photograph better doing those than doing anyone's idea of Christmas. Your traditions are the content. Everything else is decoration." },
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "harpers-tips-holiday", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Shoot the traditions you already have, in the order you already do them. The December 24th couple got their best frames because we followed their actual evening — cocoa first, tree after — instead of inventing a festive scene." },
      { type: "p", text: "If your home feels 'too small' or 'too messy' for festive photos, shoot the one corner that feels like December: the tree corner, the kitchen counter, the window with the lights. One honest corner beats a decorated house that doesn't feel like yours." },
      { type: "quote", text: "The best holiday photos aren't about Christmas. They're about your family's particular way of doing December.", cite: "Harper, from 400+ sessions" },
      { type: "faq", items: [
        { q: "How do we make holiday engagement photos not look cheesy?", a: "Photograph your real traditions instead of generic festive scenes — the hot chocolate you actually make, the tree you actually decorate, the cookies your family bakes. One or two festive touches beat a fully decorated set, and deep season colors beat neon every time." },
        { q: "What colors work for holiday engagement photos?", a: "Deep burgundy, pine green, matte gold and ivory — the colors the season actually wears, and the ones that still look like the season in twenty years. Skip bright primary red and fluorescent green; they photograph loud and date fast." },
        { q: "Do we need a decorated tree for holiday photos?", a: "No — and a generic decorated tree is one of the most clichéd backdrops in holiday photography. Your tree with your own ornaments, or a tree farm while you choose one, tells your story. A tree isn't required at all if your traditions live elsewhere." },
        { q: "Should we wear matching sweaters?", a: "They photograph as a bit that's funny for a year and dated in five. Coordinated tones — burgundy on one, pine on the other, cream underneath both — read as a couple instead of a uniform, and they'll still look like you in twenty years." },
        { q: "When is the best time to shoot holiday engagement photos?", a: "Early to mid-December, on a weekday, in the last hour of light or just after dark when warm lights read best. Shooting before the 24th means your actual holiday evening stays yours, instead of becoming the shoot." },
        { q: "Can we do holiday photos if there's no snow?", a: "Yes — snow is the least necessary ingredient. Warm light, deep colors, and your real traditions carry the whole season. A grey December day with candles and cocoa looks more like the holidays than a sunny day with a fake tree." },
      ]},
      { type: "leadMagnet", title: "The Holiday Session Style Guide", subtitle: "The palette that never dates, the traditions worth shooting, and the one-festive-touch rule — one card for your December session.", bullets: ["The 3-color holiday palette that never dates", "Your-tradition audit: 8 questions to find your content", "The one-festive-touch rule for every set"], cta: "Get the Holiday Session Style Guide" },
      { type: "shop", section: "gifts", items: [
        { label: "Warm-white string lights (2700K)", store: "Home store", href: "#" },
        { label: "Beeswax pillar candles", store: "Home store", href: "#" },
        { label: "Burgundy & pine knitwear", store: "Clothing", href: "#" },
      ]},
      { type: "p", text: "It's the 24th again, a year later, and the cocoa is on the stove — same recipe, same two mugs, the crooked ornament already back on the tree. She looks at the framed pair from last December on the counter and says the same thing every couple says eventually: they look like us. That's the whole trick. Not Christmas in general. Your Christmas. That's the one worth keeping." },
      { type: "keepReading", items: [
        { label: "Winter Engagement Photo Ideas", to: "/engagement-photo-ideas/winter-engagement-photo-ideas", note: "The season beyond the holidays — cold, quiet, beautiful" },
        { label: "Classic Engagement Photos", to: "/engagement-photo-ideas/classic-engagement-photos", note: "The colors and compositions that never date" },
        { label: "Black and White Engagement Photos", to: "/engagement-photo-ideas/black-and-white-engagement-photos", note: "The season, minus everything that dates" },
      ]},
    ],
  },
];
