import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const MOUNTAIN_POSTS: Post[] = [
  {
    slug: "mountain-engagement-photos",
    title: "Mountain Engagement Photos: 10 Ways to Shoot Big Land Without the Postcard",
    seoTitle: "Mountain Engagement Photos: 10 Ways to Go Big",
    seoDescription:
      "Mountain engagement photos that read as the two of you against big land: scale, altitude light, and the timing & safety logistics nobody thinks about.",
    excerpt:
      "A mountain does the framing for you and that's the trap — stand anywhere, shoot the peak, and you've got a postcard, not an engagement session. The good frames came from thinking about scale, the thin high light, and getting off the ridge before dark. Here are 10 ways to shoot big land without the postcard.",
    category: "locations",
    date: "2026-10-20",
    dateModified: "2026-10-20",
    featuredImage: IMAGES.gallerySilhouette,
    featuredAlt: "mountain engagement photos tiny couple on a ridge against huge layered peaks",
    tags: ["mountain", "outdoor", "golden hour", "scale", "hiking", "logistics"],
    author: harper,
    primaryKeyword: "mountain engagement photos",
    cluster: "engagement-photo-locations",
    relatedPosts: ["outdoor-engagement-photo-locations", "winter-engagement-photo-ideas", "cozy-engagement-photos", "at-home-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-locations/outdoor-engagement-photo-locations", anchor: "outdoor light" },
      { url: "/engagement-photo-ideas/winter-engagement-photo-ideas", anchor: "cold-weather shoots" },
      { url: "/engagement-photo-ideas/cozy-engagement-photos", anchor: "layering up warm" },
      { url: "/engagement-photo-locations/indoor-engagement-photos", anchor: "a warm backup spot" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.gallerySilhouette, overlayText: "Big Land, Two People", pinTitle: "Mountain Engagement Photos: 10 Ways to Go Big", pinDescription: "Scale, altitude light, and the timing nobody thinks about — 10 ways to shoot mountain engagement photos that read as your session, not a postcard. Save these." },
      { image: IMAGES.hero, overlayText: "Small Couple, Huge Frame", pinTitle: "The Scale Trick: Small Couple, Huge Mountain", pinDescription: "Go wide and let them be tiny against the land — the scale IS the photo. Step back further than feels right, then once more. Save the framing rule." },
      { image: IMAGES.galleryRing, overlayText: "Light Is Thinner Up There", pinTitle: "High-Altitude Light: Why It Flatters and How to Use It", pinDescription: "The same golden hour hits harder at 7,000 feet. Here's how to time a mountain session to the light, and get off the ridge before dark. Save the timing." },
    ],
    blocks: [
      { type: "p", text: "Here's the mountain problem: a big peak is so impressive that couples stop thinking. They hike up, stand in front of the highest thing they can see, shoot the standard pose, and end up with the exact postcard a thousand other people took from the same overlook that same afternoon. The landscape was never going to be the hard part. The hard part is putting the two of you inside it in a way that's about them, not just the mountain. That means scale (people small, land huge), the peculiar light up at altitude, and — the part no engagement Pinterest pin ever warns you about — timing and safety on a ridge. This is a location that rewards planning far more than a city rooftop does." },
      { type: "keyTakeaways", items: [
        "Scale is the whole shot — go wide, make them small, then step back once more.",
        "Altitude light hits harder and fades faster: shoot the first and last hour of the day.",
        "Layered ridges and haze give depth a single peak can't.",
        "Time the hike to the light, not to lunch — and never pose at the edge for it.",
      ]},
      { type: "h2", id: "the-postcard-trap", text: "The Postcard Trap (Why Mountains Go Wrong)" },
      { type: "p", text: "Mountains photograph themselves so easily that people assume that's the job. It isn't. A frame where the couple is an afterthought at the base of a giant peak looks like a landscape you happened to bring someone to — and it's the same frame everyone gets, because everyone stops at the same overlook. The other failure mode is riskier: couples step out onto a rocky edge or a switchback to get the drop behind them, and the picture shows it. Both problems have the same root — the mountain is treated as a backdrop instead of a design problem. Solve scale, solve the light, and mind the ground under your feet, and the postcard disappears into something that's yours." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "what-mountains-need", text: "What Mountain Frames Need: Scale, Light, Depth" },
      { type: "p", text: "Three things separate a session from a snapshot. Scale means the couple is small in the frame on purpose — the land's whole point is to make you feel its size, so let it. Light means altitude light specifically: thinner air, harder golden hour, faster dusk than at sea level, and a cooler shadow tone. Depth means using the layers mountains give you free — ridge behind ridge fading into blue haze — so the frame reads as three-dimensional instead of a cutout pasted on a wall. Get those three and you've used the location; get only the view and you've just stood in front of it." },
      { type: "table", caption: "Sea-level light vs. mountain light", headers: ["At low elevation", "At altitude", "What to change"], rows: [
        ["Golden hour lingers ~30 min", "Fades in ~15 min", "Start earlier, shoot tight"],
        ["Warm, soft shadows", "Cooler, bluer shadows", "Embrace the cool, or go B&W"],
        ["One plane of background", "Layered receding ridges", "Include 2–3 ridges for depth"],
        ["Haze flattens distance", "Clarity carries miles", "Shoot wide to show reach"],
      ]},
      { type: "h2", id: "the-10-ways", text: "The 10 Ways" },
      { type: "p", text: "Ten moves that turn big land into a portrait session instead of a travel brochure. The first is the single most important." },
      { type: "h3", id: "go-wide", text: "1. Go Wider Than Feels Right" },
      { type: "p", text: "The scale IS the photo, and you only get it by backing off. Frame the couple small — a tenth of the height — with the land swallowing the rest. Step back further than your instinct says, then once more. I shot wide on a Rockies overlook and the couple joked I was too far away; the print on their wall is now the first thing every guest stops at." },
      { type: "h3", id: "first-last-light", text: "2. First and Last Light Only" },
      { type: "p", text: "Midday up high is a flat, harsh mess — the sun bleaches color and carves black shadows under eyes. The whole mountain game is played in the first hour after sunrise and the last hour before sunset, when light rakes across ridges and turns stone gold. Plan the entire session around one of those two windows and let the rest of the day be a hike." },
      { type: "h3", id: "receding-ridges", text: "3. Use the Layered Ridges" },
      { type: "p", text: "Mountains give depth for free — ridge behind ridge, each one paler and bluer as the haze eats the distance. Compose so you catch two or three layers behind the couple and the frame suddenly has air in it. A single flat peak reads as a wall; a stack of them reads as the whole West." },
      { type: "h3", id: "switchback-road", text: "4. The Switchback Road" },
      { type: "p", text: "A mountain road curving in on itself is a leading line you'd have to fake anywhere else. Stand the couple on a bend and let the asphalt draw the eye up the frame to them. It's dynamic, it's unmistakably a road trip, and it photographs whether the day is bright or moody." },
      { type: "h3", id: "timberline-meadow", text: "5. The Timberline Meadow" },
      { type: "p", text: "Where the trees break and the meadow starts, you get a peak rising out of grass and wildflowers — the softness and the scale in one frame. Shoot low so the flowers fill the foreground and the mountain towers above them. This is the single most flattering mountain setting for a couple who wants warmth, not just grandeur." },
      { type: "h3", id: "mirroring-lakes", text: "6. The Mirroring Lake" },
      { type: "p", text: "A still alpine lake doubles the whole scene and doubles the effect. Get the couple at the waterline in the dead-calm first light and the peak reflects perfectly under them. It's the most dramatic frame in mountain photography and it only exists in the first twenty minutes of the morning, before the wind comes up." },
      { type: "h3", id: "overcast-drama", text: "7. Cloud, Not Bluebird" },
      { type: "p", text: "People pray for clear skies; I'd take clouds. A bruised, storm-gathering sky over a ridge gives mountains drama and lets soft light flatter faces. A clear blue sky at noon is exactly the postcard everyone has. Come rain or shine, a moody sky is worth more than a clear one." },
      { type: "h3", id: "wind-hair", text: "8. Let the Wind Do Something" },
      { type: "p", text: "Up high there's almost always wind, so use it. A dress moving, hair lifted, a scarf caught mid-air — motion is the one thing a mountain can't give you and the one thing wind solves. Don't fight it or fight the flyaway hair; shoot into it. Half the life in my mountain frames is the wind doing what the landscape can't." },
      { type: "h3", id: "wardrobe-for-cold", text: "9. Dress for the Temperature Drop" },
      { type: "p", text: "It can be twenty degrees cooler at the trailhead than in town, and colder still once the sun goes. Bring real layers — a wool wrap, a jacket for between setups, warm shoes for standing still on stone. A couple shivering and miserable photographs that way, and a thick coat hidden in the car saves the last twenty minutes when the light is at its most flattering." },
      { type: "h3", id: "never-edge-it", text: "10. Don't Climb for the Shot" },
      { type: "p", text: "I will not put you on a loose edge, an outcropping, or a fence rail to get the drop behind you. A picture isn't worth a fall, and a nervous couple looks nervous anyway. The safest flat ground with good scale beats a death-defying frame every time — and when the ground matters more than the view, I'd rather find a warm indoor corner and wait out the weather than gamble it." },
      { type: "gallery", images: [
        { src: IMAGES.hero, alt: "mountain engagement photos wide frame of a small couple before layered receding ridges" },
        { src: IMAGES.galleryTwirl, alt: "mountain engagement photos dress and hair caught by wind against an alpine lake" },
        { src: IMAGES.galleryRing, alt: "mountain engagement photos couple on a switchback road at first golden light" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "logistics-timing", text: "The Logistics Nobody Mentions" },
      { type: "p", text: "A mountain session is half shoot, half field trip, and the field-trip part is where photos live or die. Check permits — many state parks and national lands require them for professional shooting, and nothing ruins golden hour like a ranger asking you to move. Scout the actual pull-off the day before; overlooks fill up fast and the good stretch of road is first-come. Time the hike to the light, not to your schedule: if sunset is 6:40, you're on the ridge by 5:30, not starting a climb at 6:15. Bring water, headlamps for the walk down, and a full battery (cold drains it). And leave the drone at home unless you've cleared it — most mountain parks ban them outright." },
      { type: "quote", text: "A mountain forgives a lot, but it does not forgive being late. The light is up there for twenty minutes, and then it's gone behind the ridge.", cite: "Harper, from 400+ sessions" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They plan the session around lunch instead of around light, arrive midday, and wonder why everything looks flat and harsh. They pick the most famous overlook because it's on the map, and stand in the exact spot ten thousand tourists stand. They wear a gown and heels to a gravel trail and spend the shoot watching their footing instead of each other. And they climb too close to the edge for the shot, which shows in their face even when it doesn't show in the frame. Every one of these is a planning miss, not a talent miss. Come early or late, go a mile off the famous spot, wear shoes the trail approves of, and keep two careful feet on solid ground. The mountain will still do its part." },
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "harpers-tips-mountains", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The strongest mountain frames I've made came from backing up, not pushing in. Beginners get close to make the couple matter; mountains reward the opposite — pull the camera back until the land is enormous and trust that the two people in it still read, because scale is the emotion here. And if weather closes in, don't cancel; a storm rolling over a ridge beats a flat blue day, and worst case you've learned where your warm backup spot is." },
      { type: "p", text: "Here's what I'd do differently after all these years: I used to hike to the hardest viewpoint for the biggest payoff. Now I shoot a quiet pull-off with good layers and save the big climb for the couple who actually wants it. Half of a session is energy management, and a rested, warm couple at a modest overlook photographs better than an exhausted one at the summit." },
      { type: "quote", text: "You're not photographing a mountain. You're photographing two people standing in front of one — and only one of those things is going to move.", cite: "Harper" },
      { type: "faq", items: [
        { q: "When is the ideal time of day for mountain engagement photos?", a: "The first hour after sunrise and the last hour before sunset, without exception. Midday sun at altitude bleaches color and drops black shadows under your eyes. The light is at its warmest and most raking at the edges of the day, and up high that window is shorter than it feels — arrive on the ridge well before it opens, not as it's fading." },
        { q: "What should we wear for mountain engagement photos?", a: "Earth tones that suit the land, and — non-negotiable — shoes the trail approves of. Bring real layers too: it can be twenty degrees cooler up there, and colder still once the sun drops. A hidden wool wrap and a jacket in the car save the last twenty minutes of light, when a shivering couple otherwise starts to show it." },
        { q: "How do we make mountains look big in the photos?", a: "Back the camera up. Scale only reads when you're small in the frame on purpose, so stand farther from the couple than feels natural and let the land fill the shot. A wide lens at the right distance makes the ridge enormous and the two of you a human anchor inside it. Step back once more than you think you need to." },
        { q: "Is it safe to do engagement photos on a mountain?", a: "Yes, with sense. Stay on solid ground, keep well back from loose edges and outcroppings, and never climb onto a fence or rock to gain a drop behind you. I will not put a couple somewhere I wouldn't stand myself. Weather changes fast at altitude too, so check the forecast, bring layers, and know how you'll get down before the light does." },
        { q: "Do we need a permit to photograph on a mountain?", a: "Often, yes. Many state parks and all national parks require a photography permit for a professional session, and a ranger will stop you without one. Check the land's rules before you drive up, apply if it's easy, and if you're unsure, keep gear minimal and poses casual until you've confirmed — nothing ends golden hour faster than being asked to move." },
        { q: "What if it's cloudy or the weather turns bad?", a: "Cloud cover is usually a gift, not a problem. A moody, storm-lit sky gives mountains drama and softens faces better than a flat blue day ever does. If it truly closes in, switch to a sheltered pull-off or a warm indoor stop nearby and reshoot the light later. Some of my strongest frames were made ten minutes before rain." },
      ]},
      { type: "leadMagnet", title: "The Mountain Session Planning Card", subtitle: "The light-window timeline, the permit checklist, and the safe-spot rules — one card before you drive up.", bullets: ["Time your ridge for the light, hour by hour", "Permit & park rules to check before you go", "Wardrobe & gear for the altitude temperature drop"], cta: "Get the Mountain Planning Card" },
      { type: "shop", section: "location-accessories", items: [
        { label: "Wool wrap / field blanket", store: "Outdoor", href: "#" },
        { label: "Grip trail shoes", store: "Outdoor", href: "#" },
        { label: "Reusable hand warmers", store: "Outdoor", href: "#" },
      ]},
      { type: "p", text: "We were on the ridge with twenty minutes of light left, hair going every direction, her wrap caught like a sail, and neither of them laughing anymore — just looking out at the same blue layer of ridges, standing close because it had gotten cold. I took two frames. They're not postcards. You can tell it's the two of you up there, which is the only kind of mountain photo worth framing. Then we got our heads up and hiked down before the dark did." },
      { type: "keepReading", items: [
        { label: "Outdoor Engagement Photo Ideas", to: "/engagement-photo-locations/outdoor-engagement-photo-locations", note: "The light and timing behind every mountain frame" },
        { label: "Winter Engagement Photo Ideas", to: "/engagement-photo-ideas/winter-engagement-photo-ideas", note: "Cold, altitude, and how to keep shooting in both" },
        { label: "Cozy Engagement Photos", to: "/engagement-photo-ideas/cozy-engagement-photos", note: "The warm backup plan when the ridge closes in" },
      ]},
    ],
  },
];
