import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const NATURAL_POSES_POSTS: Post[] = [
  {
    slug: "natural-engagement-photo-poses",
    title: "Natural Engagement Photo Poses: 12 Moves That Make the Camera Disappear",
    seoTitle: "Natural Engagement Photo Poses: 12 Unposed Looks",
    seoDescription:
      "Natural engagement photo poses that don't feel posed: the task method, where hands go, and 12 specific moves — each with the direction that makes it land.",
    excerpt:
      "The reason natural-looking engagement photos aren't natural is that someone gave a direction — a task, a tiny action, a job for the hands — and the pose happened on its own. I never say 'look natural'; I say 'fix his collar' and photograph the two seconds after. Here are 12 moves I've used across 400+ sessions, with the exact direction for each and the hand logic underneath all of them.",
    category: "poses",
    date: "2026-09-22",
    dateModified: "2026-09-22",
    featuredImage: IMAGES.posesCover,
    featuredAlt: "natural engagement photo poses, couple mid-laugh as she fixes his collar, her hand on his chest",
    tags: ["poses", "natural", "camera-shy", "direction", "hands", "candid"],
    author: harper,
    primaryKeyword: "natural engagement photo poses",
    cluster: "engagement-photo-poses",
    lsiKeywords: ["unposed engagement photos", "candid couple posing", "hand placement", "photographer direction", "awkward couple photos", "task method"],
    searchIntent: "Informational",
    relatedPosts: ["camera-shy-engagement-poses", "how-to-smile-naturally-in-photos", "scenario-based-engagement-poses", "ring-engagement-photo-poses"],
    internalLinks: [
      { url: "/engagement-photo-poses", anchor: "the full pose hub" },
      { url: "/engagement-photo-poses/camera-shy-engagement-poses", anchor: "camera-shy" },
      { url: "/engagement-photo-poses/how-to-smile-naturally-in-photos", anchor: "the smile problem" },
      { url: "/engagement-photo-poses/scenario-based-engagement-poses", anchor: "story-driven sets" },
      { url: "/engagement-photo-poses/ring-engagement-photo-poses", anchor: "the ring close-up" },
      { url: "/engagement-photo-poses/outdoor-engagement-photo-poses", anchor: "sun, wind and walls" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.posesCover, overlayText: "Tasks, Not Statues", pinTitle: "Natural Engagement Photo Poses: 12 Unposed Looks", pinDescription: "Every natural-looking photo came from a direction, not a pose. 12 moves with the exact words a photographer says — fix his collar, share a bad joke. Save for your session." },
      { image: IMAGES.galleryLaugh, overlayText: "The Two Seconds After", pinTitle: "Why the Best Photos Come After the Pose Settles", pinDescription: "Hold a pose ten seconds: three stiff, seven gold. The settle-in frames are the keepers — here's the timing rule for every natural engagement photo. Pin this." },
      { image: IMAGES.casualCafe, overlayText: "Give the Hands a Job", pinTitle: "The Hand Rule Behind Every Natural Couple Photo", pinDescription: "Awkward photos are hands with nothing to do. Collar, waist, coffee cup, his ring — 12 poses where every hand already has its assignment. Save before your shoot." },
    ],
    blocks: [
      { type: "p", text: "Here's the open secret behind every 'natural' engagement photo you've ever saved on Pinterest: it was directed. Someone said 'walk toward me and argue about where to eat' and the camera caught the two seconds after the acting stopped. Nobody arrives already knowing how to stand in a field being watched. What people do know is how to do small tasks — fix a collar, share a whisper, steal a fry — so the method is giving your bodies a job and photographing the result. The 12 moves below are the jobs, each with the exact direction that makes it land, because the direction is the pose; the body just follows." },
      { type: "keyTakeaways", items: [
        "A pose is a starting position; the photo is the two seconds after it settles — hold ten, shoot the last seven.",
        "Awkward frames are almost always hands with nothing to do — give every hand a job.",
        "Movement beats stillness: walk, turn, sway — the camera forgives motion, not freezing.",
        "Talk to each other, not the lens; the audience is the couple, and the camera is furniture.",
        "Steal from real life: the hug you actually give, the lean you already do on the couch.",
      ]},
      { type: "h2", id: "what-natural-means", text: "What 'Natural' Actually Means on Camera" },
      { type: "p", text: "Natural is a direction, not a vibe. A photo reads as natural when the couple's attention is somewhere other than the camera — on each other, on a task, on a joke — and when the body is mid-motion rather than holding a shape. Frozen and aware reads as stiff in exactly one second; moving and absorbed reads as real in every frame. That's the entire science of it. The 12 moves work because each one gives attention a place to go and a body something to be doing while it goes there." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "the-task-method", text: "The Task Method (How I Actually Direct Couples)" },
      { type: "p", text: "In roughly nine of ten sessions I shot, the keeper frames came from a task, never a held pose. The method is three sentences: tell them what to do, tell them the point, stop talking and shoot what happens. The task has to be small enough to actually do while being watched — 'fall in love again' is not a task, 'whisper the worst joke you know' is. And it must give both people's hands an assignment, because idle hands become camera-aware hands, which is what awkward looks like." },
      { type: "table", caption: "Held pose vs. task — what the camera sees", headers: ["Held pose", "The same frame as a task", "What changes"], rows: [
        ["Stand close, smile", "Fix his collar, then look up at him", "Face relaxes into real attention"],
        ["Walk together, look at camera", "Walk and argue about dinner, glance back once", "Legs mid-stride, laugh arriving late"],
        ["Foreheads together, eyes closed", "Count your five favorite trips out loud", "Blink, smile, lean in — three frames"],
        ["Hold hands at your sides", "Stack both hands over his heart", "Sleeves align, rings catch light"],
      ]},
      { type: "h2", id: "the-12-moves", text: "The 12 Moves" },
      { type: "p", text: "Twelve tasks I've run ten thousand times, in the order a session actually needs them — warming up with the small ones, ending on the big motion. Each is written with the direction to say out loud, because the words are the point." },
      { type: "h3", id: "move-collar", text: "1. The Collar Fix" },
      { type: "p", text: "Her hands on his collar, straightening it, and her face doing the thing it does when she's pretending to be annoyed about nothing. It lasts four seconds and produces three frames. Harper's Tip: have her fix it for a full ten seconds past the point it needs fixing — the actual annoyance that shows around second six is the one you came for." },
      { type: "h3", id: "move-whisper", text: "2. The Bad-Joke Whisper" },
      { type: "p", text: "He leans in and whispers his worst joke; she doesn't have to laugh, she just has to hear it. The half-suppressed snort is the single most reliable natural frame in couple photography, and it works on the most camera-shy person alive. Aim the camera for her face; his follow-up grin is free." },
      { type: "h3", id: "move-walk", text: "3. The Walk-and-Glance-Back" },
      { type: "p", text: "Walk toward me like we're late for dinner — and on my count, one of you looks back at the camera and the other doesn't. The turn delivers her hair, his double chin disappears into motion, and nobody remembers the lens for exactly two steps. Shoot it three times; the third is always the loosest." },
      { type: "h3", id: "move-foreheads", text: "4. Foreheads Together" },
      { type: "p", text: "Eyes closed, foreheads touching, and both of you counting your five favorite trips out loud. The frame is geometry — two symmetric profiles and the negative space of the almost-kiss — and the counting keeps their minds off the camera. When she opens her eyes before he does, that's the print." },
      { type: "h3", id: "move-handstack", text: "5. The Hand Stack" },
      { type: "p", text: "Both hands, hers under his, resting flat on his chest — 'show me how you actually do this at home.' It's the natural answer to the question nobody knows the answer to: where the hands go. Sleeves align at the wrist, rings sit in frame, and the faces float above a gesture that already means something." },
      { type: "h3", id: "move-lean", text: "6. The Lean-and-Laugh" },
      { type: "p", text: "Back against a wall, shoulders angled toward each other, and she tells the story of the worst apartment you ever had. Leaning photographs as closeness — all the intimacy of the hug, none of the coordination. Angle both feet inward; a body pointed at the camera reads as audience, pointed at each other reads as couple." },
      { type: "h3", id: "move-slowdance", text: "7. The Bad Slow Dance" },
      { type: "p", text: "Slow-dance with no music, badly, in whatever you're standing near. Two hands on the small of her back, her chin on his shoulder, the terrible sway is the whole point — it makes both of you laugh at the absurdity and the guard drops completely. I've never met a couple who could slow-dance sincerely and still be camera-aware." },
      { type: "h3", id: "move-jacket", text: "8. The Jacket Borrow" },
      { type: "p", text: "She steals his jacket — zipped wrong, sleeves too long, looking entirely pleased with herself. It's a frame with a story built in (it's cold, he's a gentleman, she's a thief) and the oversized sleeve gives her hands a job. Keep the camera up for the moment he gets it back." },
      { type: "h3", id: "move-coffee", text: "9. The Two-Mug Moment" },
      { type: "p", text: "Both holding coffee, mid-sip, eyes meeting over the rims like they're sharing a joke about the barista. It reads as the two of you on a real Saturday, which is the feeling every couple says they wanted and almost no styled pose delivers. The mug is also a legitimate third hand for both of you — nobody is holding anything awkwardly." },
      { type: "h3", id: "move-point", text: "10. The Shared Point" },
      { type: "p", text: "He spots something off-camera — a dog, a disaster, something suspicious down the shore — points, and she looks where he's looking. Two faces in three-quarter, attention pointed at the same place, is the cheapest intimacy frame in the language. It's also the rescue move when a location is too busy to fight: the crowd becomes their subject." },
      { type: "h3", id: "move-stride", text: "11. The Mid-Stride Handhold" },
      { type: "p", text: "Cross the frame left to right, hands joined between you, and don't coordinate your steps. Uncoordinated walking is the texture of real couples rushing somewhere together; marching is the texture of a stock photo. Shoot from slightly low and the stride does what no still pose can — the dress swings, the hair flies, the frame breathes." },
      { type: "h3", id: "move-hug", text: "12. The Actual Hug" },
      { type: "p", text: "Not the photo hug with space between the ribs — the real one, where her face presses into his shoulder and his chin lands on top of her head. Tell them to hug like they're saying goodbye after a long week, then photograph the back of the frame: the hands, the height difference, the fact that nobody is performing. It's the last move here because it's the one everything else warms up to." },
      { type: "quote", text: "A pose is a starting position — the photographs you love are the two seconds after it settles. Hold ten seconds, shoot the last seven.", cite: "Harper, from 400+ sessions" },
      { type: "gallery", images: [
        { src: IMAGES.posesCover, alt: "natural engagement photo poses, her hands on his collar mid-fix, both faces unguarded" },
        { src: IMAGES.casualCafe, alt: "natural engagement photo poses, the two-mug moment with eyes meeting over the rims" },
        { src: IMAGES.galleryLaugh, alt: "natural engagement photo poses, mid-stride handhold crossing the frame laughing" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "hands", text: "The Hand Rule (Why Awkward Photos Are a Hands Problem)" },
      { type: "p", text: "Ninety percent of what couples call awkward is their hands — hanging, hovering, or one hand doing a weird claw at the hip. The fix is never 'relax your hands' (impossible command) but a destination: a collar, a waist, a mug, the stack over the heart. When you plan your own shots, put a job on both hands first and the pose solves itself. I read a couple's comfort from their wrists — engaged hands mean move to the wide frames, searching hands mean time for the whisper, not the sunset." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They practice. I say this kindly but honestly: couples who rehearse poses at home arrive performing them, and a performed pose is a held pose, which the camera reads instantly. They freeze on the count of three when the real photos happen between counts. They look at the lens because that's where the attention is, when the lens is furniture and the subject is the other person. And they try to be sincere on camera, which is a contradiction — sincerity is what shows after the effort stops. All of it is a language problem, not a personality problem. Change what's said, and the two of you already in there shows up." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "What most people miss about natural-looking frames is that the couple never hears the direction. From across the park it looks like a stolen moment; on set it was 'go argue about the group chat' and four frames of continuous shooting. If you're planning your own phone set for an announcement, give each other tasks out loud too — the result is identical from either side of the lens." },
      { type: "p", text: "Here's what I'd do differently after all these years: I used to explain every pose. Now I explain none of them — 'foreheads together, count your trips' with zero preamble, because the explanation gives people time to notice they're being photographed and the noticing is contagious. Task first, talk later. The quietest approach on my checklist changed my galleries more than any lens did." },
      { type: "quote", text: "You're not photographing two people standing nicely. You're photographing what two people do for the four seconds after someone tells them to do something.", cite: "Harper" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "How do we pose naturally if we're awkward in front of a camera?", a: "Stop posing and start doing — small tasks with real attention. Fix his collar, whisper your worst joke, argue about dinner while walking toward the lens. The task method is the entire fix for camera-shy couples because a brain doing something is a brain not performing. It works in roughly nine of ten sessions." },
        { q: "What do we do with our hands in engagement photos?", a: "Give them jobs. A hand with a destination — his collar, her waist, a coffee mug, the stack on his chest — looks natural; a hand at rest looks lost. If nothing else fits, hold hands between you at mid-stride. Stiff engagement photos are mostly two idle pairs of hands." },
        { q: "How long should we hold one pose?", a: "About ten seconds — and tell your photographer to shoot the whole sequence. The first frames are the pose settling; the last seven are you stopping the performing. Almost every keeper in my galleries came from the back half of a hold, which is why counting to ten fixes more sessions than counting to three." },
        { q: "Should we look at the camera or at each other?", a: "At each other by default; the camera gets maybe one in five frames, and it should be a chosen one, not a reflex. Faces turned toward each other tell the story of two people; faces turned toward the lens tell the story of a session. The best 'at camera' shot happens when one of you turns because the other pointed at something off-frame." },
      ]},
      { type: "leadMagnet", title: "The Pose Cheat Sheet: 12 Tasks, Word for Word", subtitle: "The exact directions for all 12 moves — hand them to your photographer or run them yourselves.", bullets: ["The 12 moves with the spoken direction for each", "The hand-job map: every hand's destination", "The ten-second rule for every hold"], cta: "Get the Pose Cheat Sheet" },
      { type: "shop", section: "props", items: [
        { label: "Two matching ceramic mugs", store: "Etsy", href: "#" },
        { label: "Oversized flannel (the jacket borrow)", store: "Amazon", href: "#" },
        { label: "Printed pose-card deck", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "One of my favorite sessions was a couple who both swore they were the worse-looking half of the pair. We ran the list — collar, whisper, walk, stack — and by the bad slow dance they'd forgotten my camera existed. The frame that made their announcement was the goodbye-hug from move twelve: her face buried, his chin on her head, both hands flat and still. Two people everyone called awkward, photographed doing the least awkward thing there is." },
      { type: "keepReading", items: [
        { label: "Camera-Shy Engagement Poses", to: "/engagement-photo-poses/camera-shy-engagement-poses", note: "The task method for people who hate being watched" },
        { label: "How to Smile Naturally in Photos", to: "/engagement-photo-poses/how-to-smile-naturally-in-photos", note: "The face half of every move above" },
        { label: "Ring Engagement Photo Poses", to: "/engagement-photo-poses/ring-engagement-photo-poses", note: "When the hands are finally the subject" },
      ]},
    ],
  },
];
