import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const NIGHT_POSTS: Post[] = [
  {
    slug: "night-engagement-photo-ideas",
    title: "Night Engagement Photos: 12 After-Dark Setups the Blue Hour Was Made For",
    seoTitle: "Night Engagement Photos: 12 After-Dark Setups",
    seoDescription:
      "Night engagement photos beat sunset when you know the window: 12 after-dark setups, the three lights worth carrying, and what goes wrong first.",
    excerpt:
      "Night is a medium, not a location. Twelve setups split by the two windows that matter — blue hour and after dark — with the three rules of night light and the twenty minutes the whole day hides inside.",
    category: "ideas",
    date: "2026-10-01",
    dateModified: "2026-10-01",
    featuredImage: IMAGES.gallerySilhouette,
    featuredAlt: "night engagement photo ideas, couple rimmed by a single porch light at blue hour, the sky still keeping its blue",
    tags: ["night", "blue hour", "low light", "sparklers", "string lights", "after dark"],
    author: harper,
    primaryKeyword: "night engagement photos",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["blue hour portraits", "after dark session", "artificial light couple photos", "sparkler photos", "string lights", "moody engagement photos", "city lights bokeh"],
    searchIntent: "Informational",
    relatedPosts: ["candid-engagement-photo-ideas", "black-and-white-engagement-photos", "cozy-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-locations/urban-engagement-photo-ideas", anchor: "what the street does after dark" },
      { url: "/engagement-photo-ideas/candid-engagement-photo-ideas", anchor: "how candids work by one light" },
      { url: "/engagement-photo-ideas/cozy-engagement-photos", anchor: "the warm-side twin of this page" },
      { url: "/engagement-photo-ideas/black-and-white-engagement-photos", anchor: "the edit that saves a flat night frame" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.gallerySilhouette, overlayText: "Twenty Minutes of Blue", pinTitle: "12 Night Engagement Photo Setups, Split by Light", pinDescription: "Night isn't a location — it's a medium. The blue-hour six and the after-dark twelve, with the three rules that keep faces warm and skies alive. Save this before you plan an evening shoot." },
      { image: IMAGES.hero, overlayText: "The Sky Isn't Black", pinTitle: "Blue Hour Engagement Photos: What the Calendar Won't Tell You", pinDescription: "The most flattering light of your whole wedding year lasts about twenty minutes after sunset — and it's the window most couples photograph past. Twelve setups for it. Pin it." },
      { image: IMAGES.galleryRing, overlayText: "One Warm Light, Both Faces", pinTitle: "The Sparkler, the Lantern, the Porch Light: Night Props Under $25", pinDescription: "Everything a night session needs fits in one bag and costs less than dinner: sparklers, a battery lantern, a dollar-store strand of lights. The twelve setups they each unlock. Save for your shoot." },
    ],
    blocks: [
      { type: "p", text: "Night engagement photos are the frames that look expensive and cost one box of sparklers — but only when you understand that night is a medium, not a location. There are two windows and nothing in between does much: blue hour, the roughly twenty minutes after sunset when the sky is still keeping its color, and after dark, when every face in your gallery is lit by something you chose. Get those two windows right and the darkness works for you instead of against the camera. Twelve setups, split by window, plus the three rules that keep the other ninety percent of night photos from going muddy." },
      { type: "h2", id: "why-night-works", text: "Why Night Is a Medium, Not a Location" },
      { type: "p", text: "A dark background solves the hardest problem in engagement photography: there's too much to look at. After sunset the world falls away and the two faces are all that's left — every light in the frame is one you chose, which is the difference between a snapshot and a photograph of you two." },
      { type: "p", text: "The second thing people miss is that couples relax after dark. Fewer passersby, date-night energy, and no squinting into a low sun. In eight of ten of my night sessions, the couple forgot the camera faster than at noon — and night candids run on that forgetting." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-questions", text: "Before You Book: Two Questions" },
      { type: "p", text: "One: is there a warm light source near your face? A streetlight makes a green ghost; the frame needs a lamp, a window, a fire, a lantern — something within arm's reach. Two: does your photographer shoot after dark? Ask the technical version: what they shoot with wide open and what ISO they're willing to print at. Modern bodies and a fast prime handle night the way they handle overcast; a shooter who has never done it will tell you night \"isn't ideal.\" That's the real answer you needed." },
      { type: "keyTakeaways", items: [
        "Night has two windows: blue hour (about twenty minutes) and after dark. Plan for both, in that order.",
        "Every face needs a warm source within arm's reach — streetlight makes ghosts.",
        "One light is one setup. The night session is short because the battery is the shutter.",
        "Blue hour flatters everything; the sky goes black before you think it does.",
        "Pick three setups from this list, not twelve, and shoot them at the top of the window.",
      ]},
      { type: "h2", id: "blue-hour-six", text: "The Six Blue-Hour Frames" },
      { type: "p", text: "Shoot these the moment the sun is gone but the sky still has color. There is no second one — you get the window once." },
      { type: "list", items: [
        "The window-and-sky — one of you lit by the warm interior lamp, the other looking at them against the deep blue behind the glass; the blue outside is free, the gold inside is the choice.",
        "The porch-light lean — both faces under the front-porch bulb, foreheads angled in; the single most flattering lamp in photography costs nothing because it's already on your house.",
        "The first-lights walk — on a block where the streetlamps come on at dusk, you two walk into the first pool of them; motion plus the new lights is the frame, and it photographs like a movie nobody notices.",
        "The headlight halo — parked car, one headlight on, you two stood just off its edge; the rim light carves both outlines while the sky keeps its last blue. The driver's seat is the second photographer.",
        "The horizon silhouette — dark figures, lit sky, no faces required; save it for the couple that hates smiling at cameras, because a silhouette is the one frame nobody can look awkward in.",
        "The fire-pit opening — light the pit while the sky is still blue, not after; warm faces over a living flame with a blue horizon behind is the night version of golden hour, and it's the keeper of the set.",
      ]},
      { type: "h2", id: "after-dark-six", text: "The Six After-Dark Frames" },
      { type: "p", text: "Once the sky is black, everything is a choice. One warm source on both faces, a background with something in it, and you two holding still a half-breath longer than feels natural." },
      { type: "list", items: [
        "The sparkler circle — six sparklers, one each, a slow count out loud so the drawing matches the shutter; the amber on your faces is the point, the shapes are the excuse.",
        "The string-light alley — one battery strand hung at face height between two posts, two faces close behind it; the lights go soft in the background and warm on the skin.",
        "The lantern walk — one of you carries a lit lantern low and between you, and the light moves with the faces because it's attached to the person.",
        "The storefront glow — a closed shop window at night is a softbox someone else paid for; stand off-center so the glass reflects the street and your faces get the interior light.",
        "The city-bokeh overlook — forty feet from a skyline or parking-lot row, lens wide open, the lights turn into coins behind you; faces need any small warm source, the background handles itself.",
        "The neon booth — a diner window or laundromat sign, faces lit by the color of the sign, reflection optional; it reads moody instead of cute, which is exactly the trade.",
      ]},
      { type: "p", text: "Three setups, not twelve — the night session is short because the batteries, your hands and the cold are all running the same clock." },
      { type: "quote", text: "You don't photograph after dark. You photograph the one light you brought and the two faces you pointed it at.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "three-rules", text: "The Three Rules of Night Light" },
      { type: "p", text: "One warm source on the faces, a background that isn't black, and a body that acts like a tripod. That's the whole craft of night, and every frame on this list obeys all three. When night photos go wrong — and the flat ones you've seen did — it's always a violation of one, not the camera failing." },
      { type: "table", caption: "The night's three windows, and what each one is for", headers: ["Window", "The sky", "Shoot this for"], rows: [
        ["Golden hour's last ten minutes", "Warm, glowing", "Wide environmental frames while there's still depth"],
        ["Blue hour (~20 min)", "Deep blue, alive", "Every portrait where you want the face to be the light"],
        ["Early dark (~1 hr)", "Black with a hint of city glow", "Sparklers, lanterns, string lights — small sources, close faces"],
        ["Full dark", "Fully black", "One neon sign or one fire; everything else turns to noise"],
      ]},
      { type: "p", text: "The holding-still part is technical for a reason: at night the shutter is slower than your heartbeat. Exhale, brace an elbow somewhere, and fire three or four frames — the roll beats the single, which is the same lesson every candid photographer learned the hard way." },
      { type: "h2", id: "the-bag", text: "What to Bring (The Bag Is Small)" },
      { type: "p", text: "Six sparklers, a battery lantern, a dollar-store strand of lights, and a jacket — that's the kit, and the whole of it comes in under $25. The jacket is not a comfort item: cold gives you goosebumps and a tight face, and a tight face is the one thing night can't fix. Check local fire rules before you buy anything that sparks, because some coasts and cities ban them outright; the lantern never gets banned." },
      { type: "h2", id: "goes-wrong", text: "When Night Goes Wrong" },
      { type: "p", text: "Three failures, in order of how often I met them. Muddy frames: the camera hunts for focus it can't find in the dark — the fix is a flashlight on the face for the first half-second, or your shooter going manual on the contrast they can see. Green-yellow faces: a bare streetlight doing what streetlights do — ask for a warm source instead, or let the edit pull the skin back. And the dead moment: everything was great at eight and flat at nine-thirty, because cold people hold still too well. The structural fix for all three is the same: shoot the blue-hour six first and let the dark be a bonus, not a deadline." },
      { type: "gallery", images: [
        { src: IMAGES.gallerySilhouette, alt: "night engagement photo ideas, the headlight halo rimming both outlines while the sky keeps its last blue" },
        { src: IMAGES.hero, alt: "night engagement photo ideas, amber sparkler light on two laughing faces, the shapes as the excuse" },
        { src: IMAGES.galleryRing, alt: "night engagement photo ideas, the string-light alley, one battery strand at face height behind two close faces" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Night" },
      { type: "p", text: "They tack night onto the end of a golden-hour shoot as an afterthought, which spends the entire blue window on cleanup. They light everything at once — two lamps, a ring light, a car — and flatten the mystery they drove out for. They hold the smile instead of holding still; at night the body matters more than the face, because the face is being lit by fire. And they arrive expecting the sky to wait. It waits about twenty minutes. Plan around that and the evening takes care of itself." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "My favorite frame from all those sessions is a couple under a porch light in a blue-black August, her forehead angled into his, both faces lit by a bulb nobody paid for. I shot it at the very end of blue hour — the one minute where the sky matches the lamp instead of fighting it. Here's the thing about night light: there is never too little of it, only too much of it in the wrong place." },
      { type: "p", text: "What I'd do differently: I used to schedule night as the tail of an evening shoot and rush the blue window to get to sparklers — the exact backwards order. Now the calendar is explicit: blue hour for the faces, one warm source, a short list; after dark only for the two setups the couple actually cares about. The batteries last. The couple lasts longer. Twelve setups, two windows, one rule that matters — a night photo is a choice of lights, and the sky is only ever the free one." },
      { type: "quote", text: "A dark background isn't the absence of light. It's the most generous light there is — it makes two faces the whole subject.", cite: "Harper" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "Do night engagement photos need a fancy camera?", a: "No, but they need a fast lens. Modern mirrorless bodies with a prime at f/1.8 shoot clean night at ISO 3200 — that's not fancy, that's the last five years of cameras. A phone's night mode handles one face beautifully and two faces less well. The gear question is really a booking question: ask your photographer what they shoot after dark, not what you need to buy." },
        { q: "Is blue hour really only twenty minutes?", a: "At mid-latitudes, roughly — a little longer in winter, shorter near the equator in summer. It starts the moment the sun is gone and ends when the sky loses its color, not when it gets \"dark,\" which you will not notice in time. Plan two setups for it, have the locations scouted in daylight, and let your photographer watch the sky because you two will be busy being in love." },
        { q: "Do sparklers make the photos worse?", a: "Only if you don't count out loud. A sparkler burns in about twelve seconds; a slow drawn shape with a counted start is what makes it read as motion instead of a white smear. The amber on the faces is the actual photograph — the shapes are the excuse for standing still. Buy a six-pack more than you need, check local fire rules, and let the failed ones happen off-camera." },
        { q: "What should we wear for night engagement photos?", a: "Texture and a little sheen, because flat cotton disappears under low light. Deep colors read rich against black backgrounds; all-black against a black sky deletes you. One warm or light element — a cream coat, a tan jacket — keeps a face separated from the dark. And bring the jacket anyway: goosebumps are not a mood, they're a tell." },
        { q: "Should we do night photos or golden hour for our session?", a: "Both, and they don't compete for the same frames. Golden hour gives the day its wide environmental shots — depth, texture, the location looking like itself. Blue hour gives the faces their portraits, and after dark is where the sparklers live. The same evening hands you all three if you start wide and never once look at a clock while the sky is doing its thing." },
      ]},
      { type: "leadMagnet", title: "The Night Light Card", subtitle: "Both windows, the twelve setups, and what to ask your photographer before you agree to shoot after dark.", bullets: ["The blue-hour six, in shooting order", "The three rules on one side of a card", "The exact gear question to ask at booking"], cta: "Get the Night Light Card" },
      { type: "shop", section: "props", items: [
        { label: "Sparklers, 36-count pack (buy the big box; the failed ones are off-camera)", store: "Amazon", href: "#" },
        { label: "Battery string lights, 100-ft warm white (no outlet, no permission)", store: "Amazon", href: "#" },
        { label: "Rechargeable camp lantern with a low glow setting", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "The last night session I ever shot professionally ended exactly when the sky gave out: a porch light, a blue hour that ran four minutes longer than the calendar promised, and a couple mid-forehead-rest who asked, afterward, whether we'd gotten anything. We had the whole gallery. The night engagement photo that looks like a chosen thing was, on the file, the one that happened while you two forgot the light was doing the work." },
      { type: "keepReading", items: [
        { label: "Candid Engagement Photo Ideas", to: "/engagement-photo-ideas/candid-engagement-photo-ideas", note: "The same forgetting, in daylight" },
        { label: "Urban Engagement Photo Ideas", to: "/engagement-photo-locations/urban-engagement-photo-ideas", note: "Neon, brick and what the city lights do" },
        { label: "Black & White Engagement Photos", to: "/engagement-photo-ideas/black-and-white-engagement-photos", note: "The edit that saves a flat night frame" },
      ]},
    ],
  },
];
