import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const OUTDOOR_POSES_POSTS: Post[] = [
  {
    slug: "outdoor-engagement-photo-poses",
    title: "Outdoor Engagement Photo Poses: 12 Frames Built Around Sun, Wind and Walls",
    seoTitle: "Outdoor Engagement Photo Poses: 12 Light-Smart Frames",
    seoDescription:
      "Outdoor engagement photo poses that work with real light: 12 lean, sit and walk frames keyed to sun position, wind and terrain — plus the silhouette and golden-hour plans.",
    excerpt:
      "Indoors, the room poses you. Outdoors, the light and the terrain do the work — a wall to lean on, a stair to sit on, a low sun to stand in front of. Here are 12 outdoor engagement photo poses keyed to what the location gives you, with the golden-hour and silhouette plans that make the rest of the list look easy.",
    category: "poses",
    date: "2026-10-06",
    dateModified: "2026-10-06",
    featuredImage: IMAGES.gallerySilhouette,
    featuredAlt: "outdoor engagement photo poses, couple forehead-to-forehead silhouetted against golden dusk light",
    tags: ["poses", "outdoor", "golden hour", "silhouette", "backlight", "location"],
    author: harper,
    primaryKeyword: "outdoor engagement photo poses",
    cluster: "engagement-photo-poses",
    lsiKeywords: ["outdoor couple poses", "golden hour poses", "silhouette couple photo", "backlit engagement photos", "nature poses for couples", "leaning poses"],
    searchIntent: "Informational",
    relatedPosts: ["natural-engagement-photo-poses", "scenario-based-engagement-poses", "ring-engagement-photo-poses", "how-to-smile-naturally-in-photos"],
    internalLinks: [
      { url: "/engagement-photo-poses", anchor: "the full pose hub" },
      { url: "/engagement-photo-poses/natural-engagement-photo-poses", anchor: "the task method" },
      { url: "/engagement-photo-locations/outdoor-engagement-photo-locations", anchor: "where to shoot outdoors" },
      { url: "/engagement-photo-poses/camera-shy-engagement-poses", anchor: "camera-shy" },
      { url: "/engagement-photo-ideas", anchor: "more session concepts" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.gallerySilhouette, overlayText: "The Light Does the Posing", pinTitle: "12 Outdoor Engagement Photo Poses Built for Real Light", pinDescription: "Walls to lean on, stairs to sit on, a low sun to stand in front of. 12 outdoor couple poses keyed to the terrain — with golden-hour and silhouette plans. Save for your session." },
      { image: IMAGES.galleryTwirl, overlayText: "Golden Hour Plans", pinTitle: "Outdoor Couple Poses That Use the Sun, Not Fight It", pinDescription: "Front-lit for faces, backlit for halos, sunset for silhouettes. The sun-position rule behind every great outdoor engagement photo. Pin this before your shoot." },
      { image: IMAGES.classicDip, overlayText: "Wind Is a Prop", pinTitle: "The Outdoor Pose Secret: Movement Beats Muscle", pinDescription: "Hair, hems and jacket laps do more for an outdoor photo than any held pose. 12 frames where the weather is the third person in the relationship. Save it." },
    ],
    blocks: [
      { type: "p", text: "A studio has no opinions; the outdoors has several. The sun decides where your faces work, the wind decides what your hair does, and a wall, a stair or a fence decides how your body is allowed to stand — which is why outdoor posing looks effortless when it's done right. The trick is using the location instead of fighting it. Every pose below is keyed to something the outdoors gives you for free: a lean, a sit, a walk, a low sun. The camera just has to be polite enough to stand where the light is." },
      { type: "keyTakeaways", items: [
        "Outdoor posing is terrain-first: lean on walls, sit on stairs, stand in doorways — surfaces relax shoulders instantly.",
        "Sun position decides the face: front-lit before 10am and after 4pm, backlit only at the golden ends of the day.",
        "Wind and water are free props — one steady pose plus moving hair reads as alive, not as messy.",
        "The silhouette is the easiest great outdoor photo: sunset, meter for the sky, hold still.",
      ]},
      { type: "h2", id: "outdoor-is-different", text: "Why the Outdoors Poses For You" },
      { type: "p", text: "Indoors, two people in an empty room have nothing to do with their bodies, so they brace — locked knees, held smiles, stiff posture waiting to be told what to do. Outdoors, the environment hands you jobs: lean here, sit there, watch the step, hold the hat. That's the difference, and why I build outdoor sessions around the location's furniture before the couple's faces. A wall takes 40 percent of your weight off the shot; a stair gives your legs something to fold; a handrail gives your hands a permanent assignment. Take the location away and the same couple goes rigid." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "read-the-light", text: "Read the Light Before You Read the Pose" },
      { type: "p", text: "A great pose in flat midday light is a snapshot; a simple lean in a low sun is a portrait. Before any of the 12 below, check where the sun is. Front-lit means the light hits your faces — safe, flattering, works any hour that isn't noon. Backlit puts the sun behind you — the hair-glow frames that define golden hour, and only work when the sun is genuinely low. And metering for the sky while you sit in shade gets you the silhouette — the one outdoor 'pose' that's almost impossible to ruin. The table is the whole cheat sheet; the poses come after." },
      { type: "table", caption: "Sun position versus what it does to a pose", headers: ["Sun position", "What you get", "Best for"], rows: [
        ["Front-low (before 10am, after 4pm)", "Even faces, soft catchlights, easy smiles", "Lean-in and forehead poses"],
        ["Behind you, low", "Hair rim, golden halo, glowing edges", "Walks, dips, the twirl"],
        ["High overhead (11am–3pm)", "Raccoon-eye shadows, squint foreheads", "Avoid, or move into open shade"],
        ["Sky-metered, you in shade", "Pure shape, zero face detail", "Silhouettes at sunset"],
      ]},
      { type: "h2", id: "the-12-poses", text: "The 12 Poses" },
      { type: "p", text: "Each names the terrain it needs and the direction that lands it. Find the feature first — wall, stair, bench, water, sun — and the body follows." },
      { type: "h3", id: "pose-wall-lean", text: "1. The Wall Lean" },
      { type: "p", text: "Back against a stone or brick wall, ankles crossed, her forearms resting on his upper arms wherever they happen to land. Lean in until the wall takes the weight and the shoulders drop — a body at 45 degrees cannot look stiff. The direction that finishes it: 'read each other's faces, slowly.' The wall does 40 percent of the work; the sun does the rest, so face the lean toward the light." },
      { type: "h3", id: "pose-stair-sit", text: "2. The Stair Sit" },
      { type: "p", text: "Two or three steps down: him on the higher tread, her on the lower, knees between his, her hands flat on the step beside her hip. Stairs give legs a folding problem to solve, which removes the locked-knee issue entirely. Shoot it slightly from above and the frames read as intimate instead of posed. Old town staircases, stadium steps, a park amphitheater — any steps on the route become a set." },
      { type: "h3", id: "pose-doorway", text: "3. The Doorway Frame" },
      { type: "p", text: "Stand in an open doorway or a stone arch, him leaning the frame with one shoulder, her half-turned to the light outside. Architecture gives a photo its composition for free — the frame-in-frame makes even a simple 'look at each other' read as deliberate. Bonus: the shade inside versus the bright outside gives you natural drama on the face without any editing." },
      { type: "h3", id: "pose-forehead-open", text: "4. The Forehead in Open Light" },
      { type: "p", text: "The most outdoor-friendly version of the classic: stand in the middle of an open field, nothing behind you but sky, foreheads together, eyes down or closed. No wall needed because the horizon is doing the posing — all weight on the back foot, front foot lightly touching his. The direction: 'say the thing you'd only say at a funeral.' It lands quiet every time, and the sky behind makes the frame feel like a promise." },
      { type: "h3", id: "pose-wind", text: "5. The Wind Check" },
      { type: "p", text: "Gusty day? Good. Face each other, her hair upwind, and let one frame catch the wind mid-pass across her face — her hand comes up to fix it, his hands stay on her waist, both laughing at the rescue attempt. Wind is the free prop photographers pray for: hair and hems moving over a still couple reads as alive, not messy. Shoot burst mode and pick the one frame where the hair is half-ruined and the faces are entirely ruined by love." },
      { type: "h3", id: "pose-walk", text: "6. The Walk-Through" },
      { type: "p", text: "A path — gravel, boardwalk, mown grass between rows — and you walk toward the camera at your actual speed, mid-conversation, hands free because they have nothing to hold. Walk-in is the single most flattering outdoor pose that exists: legs elongate mid-stride, chins drop naturally, and nobody can hold a fake while covering ground. The direction that sells it: 'tell me the story you've told me four hundred times, walk as you tell it.' Thirty feet of path becomes twenty keepers." },
      { type: "h3", id: "pose-golden-hour", text: "7. The Golden-Hour Halo" },
      { type: "p", text: "The last forty-five minutes of light: put the sun directly behind you two, faces turned toward each other rather than the camera, and let the light rim your hair and shoulders gold. This is the backlit-pose trade — you lose the catchlights, you gain the glow — and it's why sessions bill the hour before sunset. The direction: 'hold still, eyes on each other, ten seconds.' The light is moving, so shoot every eight or nine minutes and watch the whole frame turn amber." },
      { type: "h3", id: "pose-silhouette", text: "8. The Sunset Silhouette" },
      { type: "p", text: "Twenty minutes of color after the golden hour ends: meter for the sky, stand your couple in the shade of a hill or building, and shoot their profiles as a dark pair of shapes — separate, then approaching, then foreheads touching, then the almost-kiss. A silhouette forgives everything: no bad hair day, no awkward angle, no wardrobe worry, just shape and story. The direction: 'make yourself tall and lean toward each other.' The two of you become the whole horizon line." },
      { type: "h3", id: "pose-bench", text: "9. The Park-Bench Share" },
      { type: "p", text: "Sit at one end of a bench, not both ends — knees touching, his forearm along the backrest behind her, her legs crossed at the ankle toward the camera. The bench is an honesty device: it compresses the space the way a real conversation does. Shoot from the far end of the bench at an angle and the frame reads as stolen rather than staged. Empty bench, full sunset: even simpler, one person per end, leaning toward the middle until the gap closes." },
      { type: "h3", id: "pose-fence", text: "10. The Fence Perch" },
      { type: "p", text: "Her on the rail — hip on a low fence or garden wall, him standing in the crook of her legs, foreheads together. Perching is the outdoor version of the kitchen-counter lean: elevation does the talking, and a fence at hip height exists in every town on earth. One safety rule: the photographer checks the rail, not the couple, so nobody learns about loose boards mid-frame. Back at the car after, this pose is where the quiet frames happen." },
      { type: "h3", id: "pose-water", text: "11. The Water's Edge" },
      { type: "p", text: "Lake, riverbank, tide line — feet close to the water, both turned slightly away from the camera toward the view, her head on his shoulder, his hand visible on her waist. Water gives a photo its depth and its sound, and the turned-away posture kills lens awareness instantly. The direction: 'point at something in the distance, argue about what it is.' Bonus on open water: the reflected light acts as a giant free fill panel on the face." },
      { type: "h3", id: "pose-blanket", text: "12. The Blanket Sit" },
      { type: "p", text: "A blanket on grass, legs stretched or crossed, her back against his chest, his arms around both of you, one knee up to hold the coffee. Ground-level poses read as private because that's where real couples sit — no performance angle exists when you're at the grass. Shoot low, eye-level with the couple, and include something that lives there: the mug, the dog, the bag of groceries you pretended this was. The last frame of a session belongs on a blanket." },
      { type: "quote", text: "Outdoors, the location is the third photographer. Your only job is agreeing with it — same direction as the light, same angle as the wall.", cite: "Harper" },
      { type: "gallery", images: [
        { src: IMAGES.galleryTwirl, alt: "outdoor engagement photo pose, the twirl frozen mid-turn with backlit golden hour rim light" },
        { src: IMAGES.classicDip, alt: "outdoor engagement photo pose, the classic dip at the water's edge with the sun low behind" },
        { src: IMAGES.posesCover, alt: "outdoor engagement photo pose, couple mid-laugh on a sunlit field during the walk-through" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "ruiners", text: "Hard Sun, Wind and the Things That Ruin Frames" },
      { type: "p", text: "Three ruiners, all fixable. Noon sun: raccoon-eye shadows and squint foreheads — move into open shade under a tree or a building, where the sky becomes a softbox. Wind too strong for the hair: own it — a hand over the head and both of you doubled over beats a rescue attempt, so shoot the losing. And the one nobody expects: wet grass. If the shoes matter, park the blanket first; the pose plan survives to frame twelve." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong Outdoors" },
      { type: "p", text: "They find the scenic spot and turn their backs to the sun — instinct says put the view behind the couple, and it should, but the light has to hit the faces; rotate ninety degrees and check. Second, they stand in the middle of the open and hold: no wall, no stair, no rail — locked knees within four seconds. Third, they hold the pose too long; outdoors, light moves, so the same lean is a different photograph nine minutes later — shoot the series, not the one. Fourth, they treat wind and water as problems instead of the texture indoor sessions pay to fake." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Scout for surfaces, not backdrops. A wall, a stair, a rail and a bench buy six poses a couple can hold through a full sunset without thinking about it; a famous view buys you one photo everyone else has. When in doubt: lean something, and face the couple toward the light and away from the lens." },
      { type: "p", text: "What I'd do differently after 400+ sessions: I used to chase the best light and forget to watch the ground. Now I check the terrain first — what's behind the feet, how the couple's shoes handle grass, where they can sit when the sun dips — and the light chases me into the frame instead. The outdoors doesn't cooperate on anyone's schedule, but it has never once produced a boring photograph." },
      { type: "quote", text: "Every great outdoor photo is one of two things: a lean with a glow, or a walk with a story. Everything on this list is that with extra steps.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What is the best time of day for outdoor engagement photos?", a: "The last hour before sunset — golden hour — wins, with the first hour after sunrise as the under-used twin. Mid-morning before ten is the respectable third option. The actual rule: the sun has to be low enough that it hits your faces while sitting behind something, and that window only exists at the two ends of the day." },
        { q: "How do you pose for outdoor photos without looking awkward?", a: "Put the body on a surface — a wall to lean against, a stair to sit on, a rail to hold — because a supported couple cannot lock their knees. Then give the hands a job and the conversation a topic. The awkwardness you're worried about is just unsupported standing, and the outdoors is full of things to lean on." },
        { q: "What are good poses for tall couples outdoors?", a: "Asymmetry is the gift. Stairs — taller partner sits a step up, or both sit and the height problem evaporates. Leans: her back to a wall, him caging the wall beside her head, heads tilting. And the dip exists for exactly this photo, so use it once at sunset when the silhouette hides the geometry anyway." },
        { q: "Do you need props for outdoor engagement photos?", a: "You need terrain, which is free. The location's furniture — bench, blanket, railing, coffee cup — does more than any prop crate. If you bring one thing, make it a blanket, because it turns grass into a seating area and saves the shoes that keep the whole golden-hour plan honest." },
        { q: "Can you take good outdoor photos on a cloudy day?", a: "Clouds are the world's largest softbox — flat, forgiving light that makes lean-in and forehead poses their best, with zero squinting. You lose the golden glow and the silhouette, so trade the light show for the face show: closer crops, more eye contact, longer holds, and one wide shot against the dramatic gray that sunny days never get." },
      ]},
      { type: "leadMagnet", title: "The Outdoor Light & Terrain Cheat Sheet", subtitle: "The sun-position table as a phone card, plus the 12 poses sorted by what the location gives you — wall, stair, field, fence or water.", bullets: ["Sun position → pose match, one page", "The 12 poses, sorted by terrain", "The golden-hour and silhouette timing rules"], cta: "Get the Light Cheat Sheet" },
      { type: "shop", section: "location-accessories", items: [
        { label: "Compact tripod with phone mount", store: "Amazon", href: "https://www.amazon.com/s?k=compact+tripod+phone+mount" },
        { label: "5-in-1 reflector (fill & backlight control)", store: "Amazon", href: "https://www.amazon.com/s?k=5+in+1+reflector+photography" },
        { label: "Picnic blanket, sand-proof backing", store: "Amazon", href: "https://www.amazon.com/s?k=picnic+blanket+waterproof+backing" },
      ]},
      { type: "p", text: "My favorite outdoor photo isn't on the list. A couple in a corn-field session: I said 'lean against the tailgate and forget I'm here' — forty seconds of arguing quietly about a dog we hadn't picked yet, her boot on his bumper, her knee his table for the water bottle. Every frame of it is imperfect light on perfect faces. That's the argument for the whole outdoors: the setting can't be staged, so neither can you." },
      { type: "keepReading", items: [
        { label: "Natural Engagement Photo Poses", to: "/engagement-photo-poses/natural-engagement-photo-poses", note: "The task method — indoors or out" },
        { label: "Scenario-Based Engagement Poses", to: "/engagement-photo-poses/scenario-based-engagement-poses", note: "When the story poses you" },
        { label: "Outdoor Engagement Photo Locations", to: "/engagement-photo-locations/outdoor-engagement-photo-locations", note: "Where the light and terrain live" },
      ]},
    ],
  },
];
