import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const PARK_POSTS: Post[] = [
  {
    slug: "park-garden-engagement-photo-ideas",
    title: "Park & Garden Engagement Photos: 12 Green Setups Without the Postcard Look",
    seoTitle: "Park & Garden Engagement Photos: 12 Green Setups",
    seoDescription:
      "Park and garden engagement photos stop looking like postcards with three moves: the far end of the park, the open-shade canopy, and a bloom calendar.",
    excerpt:
      "Managed green — free city parks and paid botanical gardens — photographed so it looks like a session, not a vacation. Twelve setups, the sprinkler truth, and the green-cast fix.",
    category: "locations",
    date: "2026-10-22",
    dateModified: "2026-10-22",
    featuredImage: IMAGES.galleryTwirl,
    featuredAlt: "park engagement photos, a twirl at the end of a rose arch at the quiet hour, canopy light soft on both faces",
    tags: ["park", "garden", "botanical", "open shade", "permits", "bloom calendar"],
    author: harper,
    primaryKeyword: "park engagement photos",
    cluster: "engagement-photo-locations",
    lsiKeywords: ["botanical garden engagement photos", "garden session", "canopy open shade", "green color cast", "sprinkler schedule", "manicured hedges", "seasonal blooms"],
    searchIntent: "Informational",
    relatedPosts: ["mountain-engagement-photos", "beach-engagement-photo-ideas", "outdoor-engagement-photo-locations"],
    internalLinks: [
      { url: "/engagement-photo-locations", anchor: "the locations desk — scout by light first" },
      { url: "/engagement-photo-locations/outdoor-engagement-photo-locations", anchor: "the wide-open terrain this page keeps company with" },
      { url: "/engagement-photo-locations/at-home-engagement-photo-ideas", anchor: "the backyard version of the garden" },
      { url: "/engagement-photo-locations/mountain-engagement-photos", anchor: "when green goes wild" },
      { url: "/engagement-photo-ideas/classic-engagement-photos", anchor: "the style that ages best on a bench" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryTwirl, overlayText: "The Far End of the Park", pinTitle: "12 Park & Garden Engagement Photo Setups That Skip the Postcard", pinDescription: "Parks photograph like vacations unless you shoot the far end at the quiet hour. Twelve green setups, the sprinkler truth and the bloom calendar. Save this before you scout." },
      { image: IMAGES.hero, overlayText: "Canopy Is a Softbox", pinTitle: "The Light Trick Behind Every Great Garden Engagement Photo", pinDescription: "Open shade under a tree is the largest softbox your city maintains for free. The green-cast fix, the dappled-light rule, and twelve setups that use both. Pin it." },
      { image: IMAGES.classicDip, overlayText: "$0 Park, $20 Garden", pinTitle: "Park vs Botanical Garden for Engagement Photos: the Real Decision", pinDescription: "Free and public means crowds and sprinklers; paid and manicured means a bloom calendar and a nine a.m. window. The comparison table plus twelve setups. Save for planning." },
    ],
    blocks: [
      { type: "p", text: "Park engagement photos are the most common gallery on earth and the most likely to look like everyone else's — the fountain dead center, the couple small in front of the sign, the noon sun through the oak. The problem was never the green; it's that managed green comes pre-composed for tourists, and a photograph you take from the postcard spot is a photograph of the postcard. The twelve setups below walk the edges of that problem: where to stand, when to show up, which park rules actually matter, and the one light trick — open shade — that makes any garden read as a session instead of a vacation." },
      { type: "h2", id: "postcard-problem", text: "Why Parks Photograph Like Postcards" },
      { type: "p", text: "A park's famous corner is famous because a thousand cameras found it first. Center the fountain, and your engagement photos join that crowd whether you meant to or not — the location becomes the subject and you two become the props. The fix starts with a rule every location desk on this site repeats: scout by light, not scenery." },
      { type: "p", text: "The second half is the hour. Parks are busiest at the pretty times and emptiest at the photographable ones; the seven a.m. park is a different place than the eleven a.m. one, with the same trees. In roughly half the park sessions I ever shot, the couple's own favorite frame came from the unglamorous edge — the maintenance gate, the back of the hedge, the path nobody photographs — precisely because nothing there was asking to be recognized." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-questions", text: "Before You Go: Two Questions" },
      { type: "p", text: "One: public park or paid garden? A city park is free and flexible but keeps its crowds, its sprinklers and its tripod rules; a botanical garden charges admission — call it $15 to $25 for two — and in exchange hands you the manicured version with people trained to move. Two: what's the calendar doing? Green is seasonal twice over — leaves and blooms. A garden's famous walk is a ten-day window in most climates; a park's canopy is a June-through-September promise. Check the venue's bloom report; it exists, and it will tell you what the photographs will look like before you book the hour." },
      { type: "keyTakeaways", items: [
        "The postcard spot photographs the postcard — shoot the far end of the park instead.",
        "Open shade under canopy is the largest softbox your city maintains for free.",
        "Botanical gardens trade admission for control: crowds move, hedges hold.",
        "Sprinklers run at dawn somewhere in every park. The schedule is the scout.",
        "Green bounces green onto skin — white faces or a white wall break the cast.",
      ]},
      { type: "h2", id: "six-park", text: "The Six Park Setups" },
      { type: "p", text: "Free terrain, found corners. All six work in a park you already drive past." },
      { type: "list", items: [
        "The canopy path — walk the shaded side of the trees at mid-morning, sun above and behind the leaves, faces lit by the open sky ahead; the whole path is one long softbox and the frames match.",
        "The far-end bench — every park has a bench nobody sits on because it's not the feature; shoot the couple on it with the depth of the park behind them and the postcard disappears into blur.",
        "The fountain, from behind it — skip the front and stand where the spray sits between the camera and the couple; backlit mist becomes a glow nobody photographs because it's a hassle to reach.",
        "The meadow edge — where the mowed grass stops and the tall grass starts; six inches of unmaintained greenery is the difference between a picture of a park and a picture of a field with a couple in it.",
        "The maintenance gate — the ugly metal fence at the service road; green lock, chain link, both of you leaning like you're waiting for someone; it reads like a real place, which is what \"authentic\" keeps costing money to fake.",
        "The bridge — low stone or wooden, shoot from below and off-axis so the arch frames two faces and the water carries the rest of the composition; bridges are the one postcard feature that flatters the couple instead of itself.",
      ]},
      { type: "h2", id: "six-garden", text: "The Six Garden Setups" },
      { type: "p", text: "Paid terrain, borrowed perfection. These use the garden's money — the architecture someone else maintains." },
      { type: "list", items: [
        "The arch walk-through — rose or wisteria trellis, you two passing under it at the quiet hour, camera waiting at the far side; the petals frame the faces for free and the walk keeps the hands honest.",
        "The greenhouse door — the frame of a glasshouse entrance is the most underrated composition in garden photography: structure around the faces, green through the glass behind, light from every direction at once.",
        "The reflecting pool — shoot low so the water doubles the couple and the sky; a garden pond at dawn is a free mirror and the wind hasn't started yet.",
        "The hedge row — one clipped wall of green as a background, you two a full thirty feet in front of it; distance plus a wide lens turns leaves into velvet, and no tourist walks into frame at that compression.",
        "The bloom row — tulips or sunflowers in their ten-day window, camera on the far side shooting across the field so the flowers lead to the faces; shoot across, never within, because trampled rows are how couples end up in the staff's memory.",
        "The maple corner — one Japanese maple in its color week, the whole frame in red or orange with two small faces inside it; single-tree gardens photograph better than forest ones because the color has an edge.",
      ]},
      { type: "quote", text: "A garden is a photograph someone else composed years before you arrived. Your job is just to walk into it quietly.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "light-in-green", text: "The Light in Green Places" },
      { type: "p", text: "Open shade is the entire craft of park photography: stand under a canopy where the trees hold the sun off but the sky still pours light down, and you're inside the biggest softbox in town. The catch people learn the hard way is dapple — sun leaking through leaf gaps in spots. A dappled face photographs as a second couple painted onto yours: move three steps until the patches merge, or open the lens wide enough to smear them. The other catch is color: green bounces onto skin, and a face in deep shade next to a lawn goes faintly swamp-side. One white element — a shirt, a wall, a reflector the photographer holds — puts the warmth back. It's the single most common edit a park gallery needs and the one nobody budgets for." },
      { type: "table", caption: "The two greens, honestly compared", headers: ["", "City park", "Botanical garden"], rows: [
        ["Cost", "Free; tripods may need a permit", "$15–25 admission; early hours may cost extra"],
        ["Crowd control", "You dodge it; it does not dodge you", "Staff move people; paid mornings are near-empty"],
        ["Guarantee of green", "Canopy from June; everything else is luck", "Hedges hold; glasshouses run in any weather"],
        ["Bloom calendar", "Whatever the rain decided", "Published online, and it is worth reading"],
        ["Weather backup", "None — the sprinklers are the forecast", "The glasshouse is the reason for the ticket"],
      ]},
      { type: "h2", id: "the-rules", text: "The Rules of Managed Green" },
      { type: "p", text: "Three rules do almost all the work. Tripods and commercial shoots trigger permits in many city parks — a couple and a handheld camera rarely does, but ask the venue in writing when it's a garden with a website. Second: flowers belong to everyone and to no one, which is photographer-speak for don't pick, don't lean, don't let hands end up in the bloom beds where the signage isn't. And third: the sprinklers. Every park runs a schedule, dawn usually, and the greenest grass in town is also the wettest at the hour you wanted to be alone in it. Call the parks office, ask for the irrigation times, and build the session around the dry hour. It is the cheapest scouting report there is and almost no couple makes the call." },
      { type: "h2", id: "goes-wrong", text: "When Green Goes Wrong" },
      { type: "p", text: "Four ways, in order of surprise. Wet grass ruins the shoes and the mood by frame six — go barefoot on purpose and it becomes a photo. Dappled light puts leaves on faces, and the couple assumes the camera broke — it's the light, and it's three steps to the left. The green cast goes ghost-pale on skin in deep shade — that's the white-element fix from above. And the crowd: a Saturday picnic circle forms exactly behind the one clean background, and the shoot drifts into apologizing. The structural move for all four is the same — parks reward the couples who leave the famous corner. Go to the unphotographed edge and the day recovers in ten minutes." },
      { type: "gallery", images: [
        { src: IMAGES.hero, alt: "park engagement photos, the canopy path at mid-morning, open shade softbox on both faces" },
        { src: IMAGES.galleryLaugh, alt: "park engagement photos, the barefoot meadow edge after the sprinkler surprise, one laugh deciding it" },
        { src: IMAGES.galleryTwirl, alt: "park engagement photos, the arch walk-through at the quiet hour, petals framing two faces" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Green" },
      { type: "p", text: "They plan for the feature and shoot the background — the fountain, the sign, the plaque — and the album reads like the park's. They wear their colors to match the lawn, then hand the photographer a green bounce they can't undo, and two faint faces float in a sea of the same tone. They book the Saturday-afternoon slot because it's convenient, and spend the session apologizing to strangers between frames. And they treat the garden as decoration instead of logistics: the bloom window closes in days, the glasshouse closes in storms, and the sprinkler doesn't care about the deposit you put down. One hour, one white shirt, one unphotographed corner. The green does the rest." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "My favorite park frame of eight years was shot by a maintenance fence, and the couple never noticed it wasn't the famous part of town. The light was open, the hedge was thirty feet back, and a groundskeeper walked right through the session waving at the dog. What nobody budgets for is the sound of a park at seven in the morning — nobody is there yet, and that's when faces do the thing you flew to a garden to buy. Harper's Tip: book the boring hour. Nine a.m. on a Tuesday is the empty botanical garden, and the ticket is the same price as the Saturday crowd you'd be fighting." },
      { type: "p", text: "What I'd do differently: I used to plan park sessions around their features — the bridge, the fountain, the signature tree — and spent the day competing with other cameras. Now I plan around the light and the dry hour, shoot the maintenance-gate green before the picnic spreads arrive, and treat the famous corner as the backup instead of the plan. The venue isn't the photo; the window is. Twelve setups, two kinds of green, one phone call to the parks office — because the strongest park photograph gets taken at the part of the park nobody has framed yet." },
      { type: "quote", text: "Every park keeps one corner no one photographs. That corner is where your engagement photos live.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "Do we need a permit to take engagement photos in a park?", a: "Usually not for a couple and one handheld camera — that's treated as personal photography in most city systems. Tripods, assistants or anything that looks like a production can cross the line into permit territory, and botanical gardens set their own rules that admission sometimes doesn't cover. When the venue has a website, the photo policy is one page deep and one email away." },
        { q: "Are botanical gardens worth it for engagement photos?", a: "For two people and a photographer, usually yes: the ticket buys you manicured green, staff who move crowds, and glasshouses that save the session when weather breaks. The real cost is the calendar — blooms last ten days — so read the bloom report before booking the hour, not after. A public park with a good light window can still beat a garden at noon." },
        { q: "What should we wear for park and garden engagement photos?", a: "One white or cream element on each of you — the green bounce is real, and light fabric next to the face breaks the cast that turns skin swamp-pale in deep shade. Wear colors that contrast the lawn, not tones that join it. And bring the shoes you don't love: grass is wet before ten a.m. and mud is a decision you'll make anyway once the sprinklers have been running." },
        { q: "What time of day is best for green locations?", a: "The hour right after the sprinklers stop and the hour right before they start. Light is soft, crowds are hypothetical and the grass is dry — that's usually early morning, with a smaller golden window at the park's closing edge. Midday green is the worst of everything: overhead sun, dapple you can't escape, and every other camera in town at the fountain." },
        { q: "How do we avoid looking touristy in a famous park?", a: "Leave the famous corner entirely. The maintenance gate, the meadow edge, the back of the hedge — the unphotographed parts of a park photograph like places, not like postcards, and nobody's camera is pointing at them. If the landmark must appear, buy it with distance: a wide lens, thirty feet of green between you and the sign, and the postcard melts into context." },
      ]},
      { type: "leadMagnet", title: "The Green Hour Card", subtitle: "The twelve setups, the sprinkler question, and the bloom-report checklist — one card before you scout.", bullets: ["The far-end-of-the-park list for any city", "The three phone calls that save a garden session", "The white-element rule for green cast"], cta: "Get the Green Hour Card" },
      { type: "shop", section: "location-accessories", items: [
        { label: "Wedge sandals that survive grass (the shoe decision, made early)", store: "Amazon", href: "#" },
        { label: "Packable blanket, low-pile (no lint for the hedge frames)", store: "Etsy", href: "#" },
        { label: "Compact white reflector disc (the green-cast eraser)", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The last park session I ever shot professionally ended where it started — at the maintenance gate, because the bride's shoe went through a wet spot at the fountain and the whole plan walked itself to the dry, ugly corner nobody books. She laughed about the shoe for the first frame and stopped laughing by the fifth; he spent the evening pretending to know what kind of fence it was. The gallery's save-the-date came off the third frame at that fence. Park engagement photos are a logistics problem you solve with a phone call and an early alarm, and then the green does what green has always done for couples who got out of the postcard." },
      { type: "keepReading", items: [
        { label: "Beach Engagement Photo Ideas", to: "/engagement-photo-locations/beach-engagement-photo-ideas", note: "Green's opposite: water, wind and tide" },
        { label: "Mountain Engagement Photos", to: "/engagement-photo-locations/mountain-engagement-photos", note: "When the grass becomes a trail" },
        { label: "At-Home Engagement Photo Ideas", to: "/engagement-photo-locations/at-home-engagement-photo-ideas", note: "The backyard version of the garden" },
      ]},
    ],
  },
];
