import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const PHOTO_BOOTH_POSTS: Post[] = [
  {
    slug: "photo-booth-strip-ideas",
    title: "Photo Booth Strip Ideas: 12 Ways to Make the Four-Frame Strip Yours",
    seoTitle: "Photo Booth Strip Ideas: 12 Frames & Print Uses",
    seoDescription:
      "Photo booth strip ideas for engagements: 12 four-frame strip concepts, the booth-vs-DIY decision, and where to use the prints — favors, cards, fridges.",
    excerpt:
      "Four frames, one vertical strip, zero formality — the photo booth strip is the print your guests actually keep and the artifact your engagement session should produce. Here are 12 strip ideas with the frame-by-frame plan for each, the booth-versus-DIY math, and the twelve ways to use the prints once they come back.",
    category: "tips",
    date: "2026-09-29",
    dateModified: "2026-09-29",
    featuredImage: IMAGES.galleryLaugh,
    featuredAlt: "photo booth strip ideas, four-frame vertical strip of a couple mid-laugh with props",
    tags: ["photo booth", "photo strip", "prints", "favors", "DIY", "props"],
    author: harper,
    primaryKeyword: "photo booth strip",
    cluster: "engagement-photo-prints",
    lsiKeywords: ["photobooth strip", "photo strip prints", "strip template", "burst mode", "strip favors", "vertical strip"],
    searchIntent: "Commercial",
    relatedPosts: ["mini-photo-print-ideas", "polaroid-style-prints", "engagement-photo-albums", "locket-photo-print-guide"],
    internalLinks: [
      { url: "/engagement-photo-prints", anchor: "what to do with your session" },
      { url: "/engagement-photo-prints/mini-photo-print-ideas", anchor: "mini photo prints" },
      { url: "/engagement-photo-prints/polaroid-style-prints", anchor: "polaroid-style prints" },
      { url: "/engagement-photo-poses", anchor: "pose ideas" },
      { url: "/save-the-date-photos/save-the-date-photo-ideas", anchor: "save the date cards" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryLaugh, overlayText: "Four Frames, Zero Formality", pinTitle: "12 Photo Booth Strip Ideas for Your Engagement", pinDescription: "Four frames, one vertical strip, zero formality. How to make photobooth-style prints from your engagement session — poses, templates and where to use them." },
      { image: IMAGES.casualCafe, overlayText: "The Favor Guests Keep", pinTitle: "The Fun Print Your Guests Will Actually Keep", pinDescription: "Photo strips as wedding favors, save-the-date inserts and fridge art. The playful artifact every engagement session should produce. Tap for the pose list." },
      { image: IMAGES.galleryTwirl, overlayText: "Template + Cheat Sheet", pinTitle: "DIY Photo Strips: Template + Pose Cheat Sheet", pinDescription: "The exact strip layout plus 12 poses that fill it with real laughs. Print them at home or order matte strips. Save this for your session day." },
    ],
    blocks: [
      { type: "p", text: "Ask anyone which print from their session actually survived the move, the years and the re-organizing, and half of them will say the strip. Not the portrait. The strip. Four frames in a vertical column is the only photo format built for motion and personality instead of posture — it catches the setup, the almost, the landing and the aftermath, which is what being in love looks like when nobody's holding still. You can rent the ritual from a booth or build it in ten minutes with a tripod, a remote and a template. Here are the 12 ideas, the frame plans, and where the prints should go after." },
      { type: "keyTakeaways", items: [
        "A strip is four frames with a story arc — setup, build, peak, aftermath — not four variations of one pose.",
        "You don't need a booth: burst mode, a tripod and a 2×6 template produces the same artifact for the cost of paper.",
        "The best strips are directed, not posed — one tiny action per frame, twenty seconds apart.",
        "Order matte: strips get handled, folded into wallets and stuck on fridges, and matte survives all three.",
      ]},
      { type: "h2", id: "why-strips-work", text: "Why the Four-Frame Strip Works" },
      { type: "p", text: "A single photo freezes one moment; a strip preserves a sequence, and sequences are where personality lives. The format comes from the arcade booths of the last century — flash, curtain, beep, four shots, twenty seconds — and that constraint is the gift. Four frames means you can't pose your way through it; you have to do something. The first frame is always stiff, the last one is always loose, and the middle two are the real you two." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "booth-or-diy", text: "The Booth or the DIY Rig: Which One You Want" },
      { type: "p", text: "There are exactly two ways to make a strip today, and they suit different people. A real photobooth — the curtained one at a bar, the roaming one at a wedding, a rental studio — gives you flash, a timer, an instant print, and a curtain that pulls even stiff couples into silly. The DIY version — tripod, a twenty-second remote or burst mode, a 2×6 template — gives you your own light, your own location, your own dog, and about forty dollars of total cost. Neither is the wrong answer; the table decides which is yours." },
      { type: "table", caption: "Real booth versus DIY strip at home", headers: ["", "Photobooth", "DIY at home"], rows: [
        ["Cost", "$15–$30 per session, or a vendor line item", "Cost of one print order"],
        ["Look", "Flat flash, high contrast, arcade energy", "Your light — window, golden hour, lamps"],
        ["Control", "Timer decides your frames", "You decide — shoot twenty in ten seconds"],
        ["Props", "A wooden box of mustaches and hats", "Everything you own"],
        ["Best for", "The night out, the wedding floor", "The engagement session, the announcement"],
      ]},
      { type: "p", text: "The honest recommendation: do both. Run the DIY rig at your session for the keeper strips, let the wedding booth make the guest ones. The formats look different on purpose — the booth is the party, the home rig is the portrait — and an album with both reads like an actual relationship." },
      { type: "h2", id: "the-12-strips", text: "The 12 Strip Ideas" },
      { type: "p", text: "Twelve strips with a frame-by-frame plan, in the order they warm a couple up. Say the beats out loud — 'one: serious, two: smirk, three: almost, four: gone' — and four frames become a story instead of four guesses." },
      { type: "h3", id: "strip-four-emotions", text: "1. The Four-Emotion Story" },
      { type: "p", text: "The classic, and the warm-up every booth run starts with: dead serious, trying not to laugh, cracking up, gone. Frame one justifies itself — the face he makes when you say no smiling allowed. The arc does the work; nobody's posing, everybody's acting, and by frame four the laugh is genuine." },
      { type: "h3", id: "strip-prop-pass", text: "2. The Prop Pass" },
      { type: "p", text: "One prop enters the strip and changes hands every frame — the oversized hat, the fake mustache. Frame one: he wears it, she disapproves. Frame two: she wears it, he's delighted. Frame three: argument. Frame four: both wearing it. Every frame gets a job and every hand something to do — the trick for couples who freeze without one. Prop strips photograph best with one thing, not a box of them." },
      { type: "h3", id: "strip-kiss-countdown", text: "3. The Kiss Countdown" },
      { type: "p", text: "Almost, almost, almost — and then the actual one lands in frame four. Lean in and stop at the last inch; four shots become held breath, and the release frame is the keeper. Do two passes: everyone performs the first, forgets the camera on the second — and that's the print." },
      { type: "h3", id: "strip-lean-in", text: "4. The Lean-In" },
      { type: "p", text: "Frame one: a foot of air between the shoulders. Frame two: she closes half of it. Frame three: he closes the rest. Frame four: foreheads, eyes on each other, nobody on the lens. Same arc as the countdown, for people who'd rather talk than perform — argue about dinner, and the strip tells the whole truth." },
      { type: "h3", id: "strip-ring-reveal", text: "5. The Ring Reveal" },
      { type: "p", text: "Three frames of ordinary — talking, laughing, looking away — and the fourth is her hand up, his face already knowing. It doubles as an announcement strip and as your ring frame that isn't a posed product shot: the ring arrives as a moment, not a prop. Shoot it facing a window; the stone catches light where it matters." },
      { type: "h3", id: "strip-swap", text: "6. The Jacket Swap" },
      { type: "p", text: "Frame one: his jacket. Frame two: the shrug. Frame three: her stealing it. Frame four: she won't give it back. A tiny costume change across twenty seconds reads as motion and story in a way no held pose can — and the oversized-sleeve frame is the one that ends up taped to the fridge. Cold-day sessions, this one is yours." },
      { type: "h3", id: "strip-dance", text: "7. The Bad-Dance Strip" },
      { type: "p", text: "No music required: slow-dance badly across four frames — hands up, dip attempted, both laughing, collapse into the hug. Blur in a portrait is a mistake; in a strip it's evidence. And this is the strip that breaks open the most self-conscious couples — you cannot be camera-aware and doing a terrible dance at the same time." },
      { type: "h3", id: "strip-silhouette", text: "8. The Silhouette Strip" },
      { type: "p", text: "Turn off the flash, face a bright window or the open sky in the last twenty minutes of light, and run the frames as a dark pair of profiles: separate, approaching, foreheads touching, almost-kissing. Flat flash gets the attention, but the silhouette strip ages better — shape and story, matching any wall for forty years." },
      { type: "h3", id: "strip-mirror", text: "9. The Mirror Strip" },
      { type: "p", text: "The zero-equipment strip: phone on the dresser, four shots of the same mirror, the outfit changing between frames — the test dress, the denim, the good jacket, the both-together answer. It's an announcement strip nobody else has, because the fourth frame of an outfit decision photographs as a life decision. Wipe the mirror first; every fingerprint prints." },
      { type: "h3", id: "strip-third-wheel", text: "10. The Third Wheel" },
      { type: "p", text: "The dog gets frame one solo, frame two judgmental, frame three with a treat between you, frame four all of you squished. Pet strips run on one rule: the frames belong to the dog; the couple just reacts. Six-foot lead, treat in sight, and accept that frames two and three will be of the ceiling — everyone keeps the strip anyway." },
      { type: "h3", id: "strip-guest", text: "11. The Guest Takeover" },
      { type: "p", text: "At the wedding booth, hand the strips to the guests: same frame plan, but now it's your best friend attempting the four-emotion story and your uncle committing fully to the mustache. Order the double-stack favor pack, let every table come through — the exit favor costs less than candles and gets taken home instead of left on the bar." },
      { type: "h3", id: "strip-blank", text: "12. The Blank Frame" },
      { type: "p", text: "Three frames of the two of you, a fourth of empty space — a hand-written date, the venue, the ring on the table. It's the strip-as-invitation — a found object instead of a card — and the version where the couple who hates cameras gets to be themselves three times instead of four." },
      { type: "quote", text: "The first frame is always stiff and the last one is always loose. The strip is the only format where the photo you want is built into the shape of the thing.", cite: "Harper" },
      { type: "gallery", images: [
        { src: IMAGES.galleryLaugh, alt: "photo booth strip idea, four frames of a couple moving from serious to mid-laugh" },
        { src: IMAGES.casualCafe, alt: "photo booth strip idea, the prop pass with an oversized hat changing hands" },
        { src: IMAGES.galleryRing, alt: "photo booth strip idea, the ring reveal landing in the fourth frame" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "make-the-print", text: "From Frames to Print: The Template, the Order, the Matte" },
      { type: "p", text: "The DIY version lives or dies on two things: the layout and the paper. The layout is a 2×6 vertical strip holding four 1.5×2.25 frames with a white border and your date on the bottom margin — template packs with pre-cut sizes exist for the printers that sell strip paper, so the assembly is drag, drop, order. The paper: strips get handled more than any other print in this cluster — wallets, book pockets, fridges — which is why matte beats glossy here. Crop tight; at strip size, a face should fill most of the frame or it reads as a smudge." },
      { type: "p", text: "If you'd rather not engineer it, order the session images as a strip multipack from a fine-art printer, or let the lab's strip preset do the rest. Either path lands you the artifact; the template path also teaches you which four frames of the twenty you actually chose — the whole session in miniature." },
      { type: "h2", id: "where-prints-go", text: "Where the Strips Should Go After" },
      { type: "p", text: "The strip is the rare print with four homes. One: the wallet — a 2×6 fits a back pocket and a passport sleeve, which is how long-distance couples keep each other. Two: the fridge — magnet-back a strip in seconds, the cheapest gallery wall there is. Three: the mail — a strip tucked into a save the date card is the announcement people text back about. Four: the album pocket, beside the formal portrait from the same day; the pair tells the truth the single portrait can't. If a frame is already headed for small-format prints, the mini print guide covers what else to order — the honest answer is always more than you think." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They pose the strip. Four versions of the same closed-lip smile, same lean, same hands — and the fourth frame is a rerun. The format is a sequence, so change something every frame. The second miss is ordering too few: strips get given away — the friend who was there wants one, the parents want two — and reprinting one strip costs more than ordering a stack at the start. Third, they print glossy, watch it glare from the fridge, and blame the photo. Fourth, they do one pass and accept it; the second and third passes are always the ones you keep." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Announce every beat before you shoot — 'frame two is the hat, frame three is the argument.' A planned strip feels like a bit you're doing together, and a bit is the only thing that beats camera awareness on twenty-second notice. From across the curtain it looks like the booth got the laugh; it was you two, agreeing on the joke in advance." },
      { type: "p", text: "What I'd do differently after years of running strips at sessions: I used to let couples pick the four frames from the burst. Now I pick them — always earlier in the sequence than they'd choose. People pick the prettiest frames; the good strip is frame one as a mistake and frame four forgiving it. That's not a photo of a couple. That's a couple, photographed." },
      { type: "quote", text: "A portrait shows who you are for one second. A strip shows what the two of you do to each other over twenty.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "How do you make photo booth strips at home?", a: "Tripod or stack of books, camera or phone on a twenty-second timer — or burst mode. Shoot five to eight frames of a small action, pick four with a story arc, and drop them into a 2×6 strip template. Order on matte strip paper and the result is indistinguishable from the arcade version, with better light." },
        { q: "What size are photo booth strips?", a: "The classic is 2 inches by 6 inches with four frames about 1.5 by 2.25 inches, white border and a date on the bottom margin. Smaller 1×4 mini strips exist for favors, and oversized 4×12 versions read as wall art — but the 2×6 is the one that fits a wallet, which is why it survives every format change." },
        { q: "Should photo strips be matte or glossy?", a: "Matte. Strips are the most handled print you'll ever order — pockets, fridges, albums, guests' hands — and matte hides fingerprints and glare while glossy shows both within a week. The flat-flash booth look was built for matte; glossy just fights the daylight a strip lives in." },
        { q: "What should we write on the bottom of a strip?", a: "The date and nothing else — a strip is a found object, and over-designing it turns it into a flyer. For an announcement or invitation strip, the blank-frame idea puts names and date inside the fourth frame, where you'll look, not in a border you'll crop off." },
        { q: "Can you use photo booth strips as wedding favors?", a: "Yes, and they out-survive every other favor. Put a booth or a strip rig at the reception, order the double-stack pack, and guests leave with a print of their own table mid-laugh. Candles get burned; strips get taped to fridges for decades, with your wedding date on the bottom margin." },
      ]},
      { type: "leadMagnet", title: "The Strip Template + Frame-Plan Cards", subtitle: "The 2×6 template for your exact printer, plus a one-line beat sheet for all 12 strips — so four frames become a story instead of four guesses.", bullets: ["Drag-and-drop 2×6 template (matte-ready)", "The 12 frame plans, one line each", "The crop rule for faces at strip size"], cta: "Get the Strip Template Pack" },
      { type: "shop", section: "prints", items: [
        { label: "Photo strip template pack", store: "Etsy", href: "https://www.etsy.com/search?q=photo+booth+strip+template" },
        { label: "Self-serve strip printer", store: "Amazon", href: "https://www.amazon.com/s?k=photo+strip+printer" },
        { label: "Matte strip print paper", store: "Amazon", href: "https://www.amazon.com/s?k=matte+photo+paper+4x6" },
      ]},
      { type: "p", text: "The strip I look at most isn't mine. A couple I shot ran the four-emotion idea in my home rig while I pretended to check a lens — frame one her mid-sentence, frame two his face doing the thing, frame three them both losing it, frame four her wiping her eye and pointing at him like it was his fault. They printed one for the album and mailed the rest to the family group chat. The portrait is what you looked like; the strip is who you are when the timer beeps." },
      { type: "keepReading", items: [
        { label: "Mini Photo Print Ideas", to: "/engagement-photo-prints/mini-photo-print-ideas", note: "The smaller sibling, for wallets and favors" },
        { label: "Polaroid-Style Prints", to: "/engagement-photo-prints/polaroid-style-prints", note: "The single-frame version of the same energy" },
        { label: "Engagement Photo Albums", to: "/engagement-photo-prints/engagement-photo-albums", note: "Where the strip and the portrait live together" },
      ]},
    ],
  },
];
