import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const ROMANTIC_POSTS: Post[] = [
  {
    slug: "romantic-engagement-photo-ideas",
    title: "Romantic Engagement Photos: 12 Frames Where You're Not Looking at the Camera",
    seoTitle: "Romantic Engagement Photos: 12 Frames",
    seoDescription:
      "Romantic engagement photos come from attention on each other, not the lens. 12 almost-kiss and embrace frames, plus the light that flatters closeness.",
    excerpt:
      "A romantic frame isn't a kiss on command — it's two faces turned toward the feeling and away from the camera. Twelve setups on the almost-kiss and the holding, the touch line, and the soft light that wraps closeness instead of splitting it.",
    category: "ideas",
    date: "2026-11-05",
    dateModified: "2026-11-05",
    featuredImage: IMAGES.classicDip,
    featuredAlt: "romantic engagement photos, the almost-kiss at the end of a shared laugh, two faces turned toward each other and away from the camera",
    tags: ["romantic", "intimate", "almost-kiss", "closeness", "soft light", "the embrace"],
    author: harper,
    primaryKeyword: "romantic engagement photos",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["intimate couple portraits", "the almost-kiss frame", "forehead to forehead", "small-of-the-back walk", "slow dance portraits", "soft window light"],
    searchIntent: "Informational",
    relatedPosts: ["elegant-engagement-photo-ideas", "cute-engagement-photo-ideas", "candid-engagement-photo-ideas"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-ideas/elegant-engagement-photo-ideas", anchor: "the quiet cousin — same faces, slower tempo" },
      { url: "/engagement-photo-ideas/cute-engagement-photo-ideas", anchor: "the playful neighbor, not the tender one" },
      { url: "/engagement-photo-ideas/candid-engagement-photo-ideas", anchor: "what happens when nobody knows they're being looked at" },
      { url: "/engagement-photo-locations/at-home-engagement-photo-ideas", anchor: "where the nowhere-to-be slow dance already lives" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.classicDip, overlayText: "Attention, Not A Pose", pinTitle: "12 Romantic Engagement Photo Frames Built on Closeness", pinDescription: "Romantic isn't a kiss on command — it's two faces pointed at the feeling and away from the lens. Twelve setups on the almost-kiss and the embrace, the touch line, and the light that flatters closeness. Save before your shoot." },
      { image: IMAGES.galleryTwirl, overlayText: "The Almost-Kiss Wins", pinTitle: "The Romantic Frame Better Than The Kiss Itself", pinDescription: "The camera can't photograph a kiss — it photographs the half-second before one. Twelve intimate setups built on the not-yet, plus how to stay tender when you hate PDA. Pin it." },
      { image: IMAGES.gallerySilhouette, overlayText: "One Soft Light", pinTitle: "Why Your Romantic Engagement Photos Look Harsh (And The Light Fix)", pinDescription: "A big soft light wraps two faces turned together; hard sun splits them in half. Twelve frames of closeness plus the one-hour window that makes them glow. Save for planning." },
    ],
    blocks: [
      { type: "p", text: "Romantic engagement photos are the ones everyone wants and almost nobody shoots well, because couples hear the word and reach for the pose — pucker, hold, look past the camera at something feeling. That's the mistake. A frame reads as romantic for exactly one reason: the two people in it are paying attention to each other and not to the lens. The setting is almost beside the point, the light only helps, and the whole craft is arranging a moment where looking at the other person is more natural than looking away. Twelve setups below are built on that one mechanism, split between the frames that are almost a kiss and the frames that are only hands." },
      { type: "h2", id: "what-reads-romantic", text: "What Actually Reads as Romantic" },
      { type: "p", text: "Directness is the tell. A photograph is romantic when the faces point at the feeling instead of at the frame — foreheads touching, eyes closed, a mouth at an ear. The camera is a witness in a romantic gallery, never a participant, and you can feel the difference across a room: the staged kiss looks at us, the real one looks at each other, and only the second one belongs on a wall." },
      { type: "p", text: "Here's the counterintuitive part that took me a hundred sessions to believe: the almost-kiss beats the kiss. The half-second before contact — noses not quite touching, one breath short — holds the whole story in suspension, and the viewer's eye leans into it. A landed kiss resolves the tension; an unfinished one keeps it, and kept tension is what you actually print. Across 400-plus sessions, the frame a couple remembered most was almost never the one where they finally kissed." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-decisions", text: "Before the Frames: Two Decisions" },
      { type: "p", text: "One: your touch line. Decide what you'll do in front of a stranger before you're asked to do it flustered — some couples kiss freely and some won't hold hands on a main street, and both can shoot a gallery that stops people mid-scroll. The tender frames below mostly don't require a public kiss; they require closeness, which is a smaller ask. Two: who's watching. Self-consciousness is the real enemy of romance, not the camera — so the first decision about location isn't prettier scenery, it's fewer witnesses. A room where nobody clocks you will give you more warmth than a landmark where everybody does." },
      { type: "keyTakeaways", items: [
        "A frame reads romantic when faces point at the feeling, not the lens.",
        "The almost-kiss beats the kiss — suspended tension is what gets printed.",
        "Pick your touch line before the shoot; tenderness is a smaller ask than PDA.",
        "Fewer witnesses, not prettier scenery: self-consciousness is the real enemy.",
        "A big soft light wraps two faces turned together; hard sun splits them apart.",
      ]},
      { type: "h2", id: "six-almost-kiss", text: "The Six Frames of the Almost-Kiss" },
      { type: "p", text: "All six live in the half-second before contact. The job is to aim the two faces at each other and photograph the way, not the arrival." },
      { type: "list", items: [
        "The almost-kiss — foreheads together, mouths a breath short, caught on the way to rather than at; nothing is resolved and that's the entire feeling.",
        "The temple nuzzle — one face into the side of the other's neck, eyes shut, the camera at three-quarter; it's the most private frame that never technically shows a kiss.",
        "The look-down — her ring hand between his, both faces angled at it and nobody at the lens; the ring is only an excuse to lean the heads the same way.",
        "The whisper — mouth to ear, the other one reacting to a secret the camera will never hear; whatever you whispered can be nonsense, the smile can't.",
        "The chin lift — a hand under the chin, faces tipping toward each other in profile; it reads as a promise because the bodies lean before the lips decide.",
        "The interruption — one of you mid-laugh, the other turning into it and cutting it off; motion plus intent, and the laugh makes the almost believable.",
      ]},
      { type: "h2", id: "six-hands", text: "The Six Frames of Hands and Holding" },
      { type: "p", text: "When lips feel performed, hands carry the frame. Every one of these keeps the faces pointed at each other and lets the contact do the talking." },
      { type: "list", items: [
        "The small-of-the-back walk — walking, one hand low on the other's back, heads turned to each other instead of forward; the direction of attention is the whole photograph.",
        "Forehead to forehead, eyes closed — no kiss at all, just the touch and the stillness; the quietest frame on this list and usually the loudest print.",
        "The coat around both — one jacket over two shoulders at a cold door, both faces inside it together; borrowed shelter does for romance what a bare wall does for restraint.",
        "The hands over hands — both pairs around a single warm mug, faces lifting up from it; the hands have the job so the faces get to relax into the looking.",
        "The few inches — one of you lifted off the ground at a wall, arms at the other's neck; contact plus unexpected weight, and nothing about it can look posed.",
        "The nowhere-to-be slow dance — forehead to forehead, swaying in a room with one light on; the most honest frame in this style and the cheapest to stage, because the song can be silence.",
      ]},
      { type: "p", text: "Twelve frames, one rule under all of them: give the eyes a job, and the job is the other person. The moment either of you has nothing to look at, the camera becomes the default — and a romantic photograph is precisely the one where the camera loses." },
      { type: "quote", text: "The camera can't photograph a kiss. It photographs the half-second before one, where the whole story is still up to them.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "the-light", text: "The Light That Flatters Closeness" },
      { type: "p", text: "Romance wants a big soft light, and for a mechanical reason. Two faces turned toward each other present a lot of angles at once — a cheek here, the back of a jaw there — and a small hard sun lights one side and strands the other in shadow, splitting the couple you're trying to bring together. A large soft source (an open shade, a bright overcast, a north window, or the last hour of low sun) wraps both faces at once and keeps them reading as one shape. Warm light helps too, but warmth rides second to size: softness is what flatters closeness, so put yourselves in front of the biggest light in the scene and let the low sun handle the mood for free." },
      { type: "table", caption: "Romantic against the three styles it gets confused with", headers: ["Style", "It borrows", "The tell"], rows: [
        ["Romantic", "Directness — the almost-kiss, the embrace", "Faces pointed at the feeling, never at the lens"],
        ["Elegant", "Subtraction — space, stillness, one beat slow", "Faces composed toward the frame, not each other"],
        ["Cute", "Play — the small gag, the game", "Heads together but laughing at something silly"],
        ["Candid", "Chance — the unposed second, caught", "Nobody in it knows they're being looked at"],
      ]},
      { type: "h2", id: "goes-wrong", text: "When It Goes Wrong: Performing for the Room" },
      { type: "p", text: "Romance dies the moment either of you remembers the audience, and the audience is the camera first. The fix is to shrink the job until the only person worth impressing is the one touching you. If a frame starts to chew scenery, move closer and lower the energy — a whisper and a forehead touch are impossible to ham up at arm's length. If the almost-kiss keeps landing on cue and going wooden, skip the kiss and go to the hands, where performance has nowhere to sit. And if the whole thing turns into a show for the bystanders, you've picked too public a stage: move somewhere emptier and the acting stops on its own, because there's no longer anyone to act at." },
      { type: "gallery", images: [
        { src: IMAGES.galleryRing, alt: "romantic engagement photos, the look-down frame, both faces angled at the ring and nobody looking at the camera" },
        { src: IMAGES.galleryLaugh, alt: "romantic engagement photos, the laugh interruption, one turning into the other and cutting the joke off" },
        { src: IMAGES.indoor, alt: "romantic engagement photos, the slow dance with nowhere to be, foreheads together in one warm light" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Romantic" },
      { type: "p", text: "They aim for the peak instead of the approach — five landed kisses, all identical, all looking past the camera at their own idea of feeling, when the frame that gets printed is the breath before. They treat romance as the opposite of funny, convinced tenderness means solemn faces; the interrupted laugh proves them wrong every time. They over-choose the place — a cliff, a rose garden, a monument — and end up photographing the postcard, because a landmark demands the couple perform for it. And they freeze the bodies while they warm the faces, forgetting that a hand at the small of the back says more than any expression you can instruct. The setting is the least romantic thing in most romantic photographs." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The thing nobody tells couples is that the two most romantic frames in my favorite galleries were shot with the two people not touching at all — one face turned toward the other across a few inches of empty air, and the whole distance bristling with the almost. Proximity sells closeness better than contact, because the eye fills in what isn't there yet. So my standing direction on a romantic set is smaller and slower, never bigger: come in a quarter step, stop the hands at the waist, and don't perform the feeling — I'm not looking for kissing faces, I'm looking for the face you only make for them. That's a face most couples are certain they don't have. They do." },
      { type: "p", text: "What I'd do differently: early on I built romantic sets around the kiss and got ten versions of the same wooden smooch, all aimed at the lens. Now the kiss is the last frame I ask for and sometimes I never ask for it at all — I fill the set with temples and hands and foreheads and whispers, and when the couple relaxes into all that closeness, the one real kiss happens between my frames, unperformed, and I catch it by leaving the shutter going. Twelve setups, two decisions, one seating rule about the light — because a romantic photograph is never the kiss, it's the story still undecided in the second before it." },
      { type: "quote", text: "You don't pose a couple in love. You point their attention at each other and get out of the way.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What's the difference between romantic and cute engagement photos?", a: "Where the attention lands. Romantic points the faces straight at the feeling — closeness, the almost-kiss, the hush. Cute points them at each other over something playful, a joke or a small gag. Same two people turned inward, different energy: one you frame, one you'd text to a friend." },
        { q: "How do we look romantic if we hate kissing in public?", a: "Skip the kiss entirely. Most of these frames never touch lips — foreheads, a temple in a neck, a hand at the small of a back, two pairs of hands on one mug. Closed eyes make a public touch feel private, and a whisper reads as intimate with no mouths near each other. Decide your line beforehand and the tenderness arrives with nothing to hide from your grandparents." },
        { q: "What's the best light for romantic engagement photos?", a: "The largest soft source you can find — open shade, bright overcast, a big window, or low sun. Two faces turned together have many angles: hard light splits them, soft light wraps them as one shape. Warmth is the bonus, not the engine. Chase size first, let a low sun add the mood, and skip the flash, which flattens the very thing you're paying for." },
        { q: "Do romantic photos have to include an actual kiss?", a: "No, and the ones without are often stronger. The camera can't photograph a kiss — it photographs the half-second before one, where the story is still undecided. The almost-kiss, the forehead touch, the chin lift that never lands all hold a tension a closed mouth releases. Let any kiss happen between cues, when nobody's performing and the shutter is already running." },
        { q: "How do we stop performing for the camera?", a: "Give the eyes a job, and the job is the other person. A frame goes wooden the instant you have nothing to look at and the camera becomes the default; keep the gaze on a face or a hand instead. Shrink and slow the movement, then end each set with one real laugh. The couple that forgets the audience beats the one that impresses it." },
      ]},
      { type: "leadMagnet", title: "The Closeness Card", subtitle: "The twelve frames, your two touch-line decisions, and the one light rule — on one card for you and your photographer.", bullets: ["The six almost-kiss and six hands frames", "How to set your line before the shoot, not during", "Why big soft light wraps two faces and hard sun splits them"], cta: "Get the Closeness Card" },
      { type: "shop", section: "props", items: [
        { label: "Battery tea-light candles, warm flicker (for the one-light slow-dance room)", store: "Amazon", href: "#" },
        { label: "A solid-color wool throw, big enough for two shoulders", store: "Etsy", href: "#" },
        { label: "A one-color bouquet, carried loosely rather than staged", store: "Amazon", href: "#" },
      ]},
      { type: "p", text: "The most romantic gallery I ever delivered was shot in a driveway, at night, after the couple's own car headlights gave the only usable light — one face turned into a shoulder, the other resting on it, neither looking anywhere near the camera I happened to be pointing. They hadn't planned it. I hadn't posed it. It landed because, for the half-second I caught, the two of them were on their own street with nowhere else to be and no one else in it. That's the whole method of romantic engagement photos in one frame: point their attention at each other, find the biggest soft light in the scene, decide your line, and stay out of the way. The rest was always going to happen without you." },
      { type: "keepReading", items: [
        { label: "Elegant Engagement Photo Ideas", to: "/engagement-photo-ideas/elegant-engagement-photo-ideas", note: "The quiet cousin — subtraction instead of closeness" },
        { label: "Cute Engagement Photo Ideas", to: "/engagement-photo-ideas/cute-engagement-photo-ideas", note: "Same faces turned inward, opposite energy" },
        { label: "At-Home Engagement Photo Ideas", to: "/engagement-photo-locations/at-home-engagement-photo-ideas", note: "Where the nowhere-to-be slow dance already lives" },
      ]},
    ],
  },
];
