import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const RUSTIC_POSTS: Post[] = [
  {
    slug: "rustic-engagement-photos",
    title: "Rustic Engagement Photos: 11 Ways Past the Barn Cliché",
    seoTitle: "Rustic Engagement Photos: 11 Ways Past the Barn",
    seoDescription:
      "Rustic engagement photos that read as honest texture, not the wedding-barn clone: weathered wood, stone, dried grass, and the light that ties it together.",
    excerpt:
      "Somewhere a venue put up string lights over a clean new barn wall, and 'rustic' became a costume everyone wears. Real rustic isn't the barn — it's texture and age: weathered wood, limestone, dried grass, rust, and low light that rakes across all of it. Here are 11 ways to get there without the clone.",
    category: "ideas",
    date: "2026-10-13",
    dateModified: "2026-10-13",
    featuredImage: IMAGES.locationsCover,
    featuredAlt: "rustic engagement photos couple against weathered wood and limestone in golden light",
    tags: ["rustic", "barn", "outdoor", "textures", "hill country", "earth tones"],
    author: harper,
    primaryKeyword: "rustic engagement photos",
    cluster: "engagement-photo-ideas",
    relatedPosts: ["cozy-engagement-photos", "winter-engagement-photo-ideas", "outdoor-engagement-photo-locations", "black-and-white-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-locations/outdoor-engagement-photo-locations", anchor: "outdoor sessions" },
      { url: "/engagement-photo-ideas/cozy-engagement-photos", anchor: "cozy indoor work" },
      { url: "/engagement-photo-ideas/winter-engagement-photo-ideas", anchor: "cold-weather textures" },
      { url: "/engagement-photo-ideas/unique-engagement-photo-ideas", anchor: "personal twists" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.locationsCover, overlayText: "Not the Barn", pinTitle: "Rustic Engagement Photos: 11 Ways Past the Barn", pinDescription: "Rustic isn't a string-lit new barn — it's weathered wood, stone, dried grass and low raking light. 11 ways to get real texture without the wedding-venue clone. Save these." },
      { image: IMAGES.galleryRing, overlayText: "Age Is the Point", pinTitle: "The Rustic Rule: Shoot the Age, Not the Theme", pinDescription: "Weathered beats new every time. Rust, cracked stone, sun-bleached wood — the marks of years are what read as rustic on camera. Save the texture list." },
      { image: IMAGES.gallerySilhouette, overlayText: "Earth Tones, Not White", pinTitle: "Rustic Wardrobe: Earth Tones, Not Wedding White", pinDescription: "Denim, linen, leather, rust, olive, ochre. Dress the frame the way the land already is. Save the palette." },
    ],
    blocks: [
      { type: "p", text: "Here's what happened to rustic. A few venues hung bulbs over brand-new barn board, the internet copy-pasted the look, and suddenly every couple in a thirty-mile radius was photographing in front of the same whitewashed wall with the same mason jars. That's not rustic — that's a theme park for one particular wedding. Real rustic is older and simpler than that: the way sun has bleached a fence rail silver, limestone pocked by a hundred winters, grass gone gold at the end of a dry season, rust blooming on an old gate. It's texture and time, and you can find it a mile from any barn. The cliché is a wall you rent. Rustic is everywhere, if you know what to look for." },
      { type: "keyTakeaways", items: [
        "Rustic is texture and age, not a themed wall — weathered always beats new.",
        "Low, raking light makes wood and stone read; flat noon light flattens them.",
        "Dress earth (denim, linen, leather, ochre, olive) — not event white.",
        "A working ranch or a roadside beats the string-lit event barn every time.",
      ]},
      { type: "h2", id: "rustic-became-a-costume", text: "How Rustic Became a Costume" },
      { type: "p", text: "The problem with the modern barn look is that it removed the age from the word rustic. A fresh-painted wall with bolted-on décor reads as a set because that's exactly what it is — a set. Once one venue nailed the formula, a hundred copied it, and the photos all came out interchangeable: the same wall, the same bulbs, the same couple standing stiffly in front of someone else's theme. The fix is to go looking for things that weren't built for the camera. Weathered wood, broken stone, old iron, dying grass — surfaces that already have a past. A frame shot against something with fifty years of weather on it doesn't need a single prop to read as honest." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "what-rustic-is", text: "What Rustic Actually Reads As on Camera" },
      { type: "p", text: "Rustic is a low-contrast world of warm neutrals and imperfect surfaces. The eye reads it through texture (grain, pitting, fraying, rust), through color (ochre, olive, rust, cream, weathered grey), and through light that comes in sideways so all that surface relief actually shows. None of those require a barn or a ranch; a crumbling wall behind a parking lot has more honest rustic character than a rented event space. Costumey rustic reaches for symbols — horseshoes, mason jars, planks nailed up to look aged. Real rustic reaches for surfaces that genuinely are aged, and lets the light do the rest." },
      { type: "table", caption: "The quick read: real rustic vs. the barn-clone", headers: ["Element", "Reads rustic", "Reads barn-clone"], rows: [
        ["Surface", "Weathered, pitted, sun-bleached", "New board painted to look old"],
        ["Light", "Low & raking (early or late)", "Flat noon, or venue bulbs"],
        ["Palette", "Ochre, olive, rust, cream, stone", "White + greenery + fairy lights"],
        ["Setting", "Working ranch, roadside, old wall", "The one event everyone rents"],
        ["Details", "Rust, fraying, cracks — left in", "Décor bolted on for the photo"],
      ]},
      { type: "h2", id: "the-11-ways", text: "The 11 Ways" },
      { type: "p", text: "Eleven surfaces and moves that pull a frame toward honest texture. Only one of them involves a building, and it isn't a barn." },
      { type: "h3", id: "weathered-wood", text: "1. Weathered Wood, Not Barn Board" },
      { type: "p", text: "Silver fence rails, a split-wood pile, a shed wall gone soft at the grain. Look for wood that's been left outside for years — the grey patina is the whole story, and it photographs with far more depth than new lumber ever does. Put them against it, shoot into the light, and let the texture fill the frame around them." },
      { type: "h3", id: "limestone", text: "2. Limestone & Caliche" },
      { type: "p", text: "Central Texas is built on pale limestone and the pale dirt they call caliche. A rough-cut wall or a rocky outcrop gives you a neutral, pitted backdrop that flatters every skin tone and never dates. It's the quietest rustic surface there is, and I lean on it constantly." },
      { type: "h3", id: "dried-grass", text: "3. Dried Grass, Not Green Lawns" },
      { type: "p", text: "A field gone gold at the end of a dry season is worth ten manicured lawns. Tall grass wraps light, throws soft shadow, and makes a couple look small against something old and unhurried. Back it with the sun low and the whole frame glows without a filter." },
      { type: "h3", id: "rust-and-iron", text: "4. Rust & Old Iron" },
      { type: "p", text: "A rusted gate, a sun-bleached truck, an abandoned something with a century of orange bloom on the metal. Rust is the richest color in the natural palette and it flatters warm skin the way nothing else does. Frame tight on the texture, pull back for the couple, and it reads like the land remembers them." },
      { type: "h3", id: "natural-fibers", text: "5. Woven & Natural Fibers on the Body" },
      { type: "p", text: "Denim, linen, corduroy, leather, raw wool — fabrics with a slub and a weave the camera can feel. A man in a worn denim jacket and a woman in a linen dress become part of the rustic frame instead of standing in front of it the way a suit and cocktail dress do." },
      { type: "h3", id: "earth-palette", text: "6. Earth Tones, Not Event White" },
      { type: "p", text: "Ochre, olive, rust, camel, cream, stone. Two or three shared earth tones between you let you disappear into the landscape rather than float above it. White reads as a wedding against a barn; the earth reads as you two living in the place." },
      { type: "h3", id: "raking-light", text: "7. Raking Light (Texture Needs It)" },
      { type: "p", text: "Rustic is texture, and texture only shows when light comes in sideways. Shoot early or late when the sun skims wood and stone and throws every grain into relief. Flat noon light erases the very things you drove out to photograph — save a noon session for a shaded porch, not an open wall." },
      { type: "h3", id: "working-ranch", text: "8. A Working Ranch, Not the Event Barn" },
      { type: "p", text: "Ask a real working place if you can shoot a corner — a stock tank, a tack room, a fence line where the day's work actually happened. Working space has the wear and clutter the styled venues sand away. A roped-off saddle and a dusty post tell a truer story than any set of props pretending to." },
      { type: "h3", id: "wildflowers-roadside", text: "9. Wildflowers & Roadside Green" },
      { type: "p", text: "Bluebonnets, Indian paintbrush, or just whatever unremarkable wildflower crowds a fence line — roadside growth has the loose, wind-tossed quality no florist bouquet can fake. Shoot low through the stems so they blur warm around the couple. The most honest floral frames I've made were on the shoulder of a county road." },
      { type: "h3", id: "overcast-softbox", text: "10. Overcast as a Softbox" },
      { type: "p", text: "Couples cancel for grey skies; I book them. An overcast day is a giant softbox — it deepens the color of wet stone and weathered wood and lets you shoot rusty iron in open detail with no harsh shadows. Moody, honest, flattering, and free. This is where rustic gets its grittiest work." },
      { type: "h3", id: "black-white-honesty", text: "11. Black & White to Kill the Costume" },
      { type: "p", text: "If a location is edging toward barn-clone, convert it to black and white. Monochrome strips the string-light sentimentality and leaves only texture, light, and the two of you — the exact things rustic is supposed to be about. It's the fastest way to rescue a set that looked a little too themed on the day." },
      { type: "gallery", images: [
        { src: IMAGES.gallerySilhouette, alt: "rustic engagement photos couple against weathered limestone in low golden light" },
        { src: IMAGES.hero, alt: "rustic engagement photos dried gold field at the edge of a working ranch" },
        { src: IMAGES.galleryLaugh, alt: "rustic engagement photos one partner in denim and linen by a rusted iron gate" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "where-to-find-it", text: "Where to Find Real Rustic (Without the Venue)" },
      { type: "p", text: "You almost never need to rent anything for this. I've shot honest rustic on county-road shoulders, at the edge of a working pecan orchard, behind a feed store, on a ranch that said sure, and against a fifty-year-old wall in the middle of town. The recipe is the same anywhere: look left for the oldest, most-weathered surface within reach. If you're anywhere near Austin, the Hill Country gives you limestone and dried grass for free — the only thing you have to avoid is the string of bulbs." },
      { type: "quote", text: "The most rustic photo I ever made had no barn in it at all — just a rusted gate, a grey sky, and two people who stopped posing the second a cow walked up.", cite: "Harper, from 400+ sessions" },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They book the venue that started the clone and think renting the look buys them the feeling — it doesn't, it buys them a wall. They show up in event clothes (white, crisp, clearly not from here) that fight the setting instead of joining it. They shoot at high noon, when flat light erases every texture they drove out to photograph. And they lean on décor — the jars, the signage, the planks — when rustic was supposed to be about the absence of that stuff. Take one honest weathered surface, put the two of you on it in their own earth-toned clothes, and wait for the light to come in sideways. The barn can keep the rest of them." },
      { type: "quote", text: "Rustic is the look of time passing on a place. You can't rent time — so go find something that's already got it.", cite: "Harper" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "How do we do rustic engagement photos without the wedding barn?", a: "Skip the string-lit venues entirely and hunt for surfaces that are already old: weathered fence rail, rough limestone, dried fields, rusted iron. Real rustic reads from texture and age, not from décor. A county-road wall with fifty years of weather beats a rented barn wall every time." },
        { q: "What should we wear for rustic engagement photos?", a: "Natural fibers and earth tones — denim, linen, corduroy, leather, wool, in ochre, olive, rust, camel, cream. Two or three tones shared between you let you settle into the landscape instead of standing above it. Avoid crisp event white and anything that looks like it came from a bridal rack." },
        { q: "Where can we find rustic locations near Austin?", a: "Mostly for free, once you look left for the oldest surface in reach. The Hill Country is all pale limestone and gold grass; county roads, working ranches, pecan orchards and feed-store back walls do the rest. The one thing worth avoiding is a venue that's clearly built the look for cameras." },
        { q: "Do we need golden hour for rustic photos?", a: "Yes, and for a specific reason. Rustic is all texture, and texture only reads when light comes in sideways and throws every grain into relief. Flat noon light erases exactly what you drove out to shoot. Early or late, and even a grey overcast sky works as a softbox that deepens stone and wood." },
        { q: "What is the difference between rustic and just 'country'?", a: "Country is a place; rustic is a texture. A brand-new barn on a horse farm is country and reads as costume. A sun-bleached rail and a rusted gate on the same farm are rustic and read as honest. You can find real rustic on a city lot, and you can find fake rustic in the middle of a ranch. Look for age, not acreage." },
        { q: "Can we do rustic engagement photos in winter or the rain?", a: "Wet, cold weather is the friend of this look, not the enemy. Rain deepens the color of stone and old wood, overcast skies soften faces while keeping detail in the rust, and winter's low light rakes clean across the texture. A grey day at a weathered wall is more honestly rustic than a bright blue one." },
      ]},
      { type: "leadMagnet", title: "The Rustic Location Card", subtitle: "Where to find real texture, the earth-tone wardrobe list, and the raking-light window — one card before you book anything.", bullets: ["The five surfaces that beat any rented barn", "Earth-tone wardrobe pairings to build from", "How to time light so texture actually shows"], cta: "Get the Rustic Location Card" },
      { type: "shop", section: "props", items: [
        { label: "Worn denim jacket", store: "Clothing / thrift", href: "#" },
        { label: "Linen & wool layering", store: "Clothing", href: "#" },
        { label: "Leather-bound field journal", store: "Props", href: "#" },
      ]},
      { type: "p", text: "There's a gate out past the pecan orchards — no venue, no bulbs, just a hundred years of orange rust and a fence line going gold into autumn. They were going to book the barn, and I talked them into fifty minutes at that gate instead. By the third frame a horse had wandered up and they'd stopped performing entirely. The pictures look like the land they actually live on. That's the whole point — not the look of a wedding set somewhere else." },
      { type: "keepReading", items: [
        { label: "Cozy Engagement Photos", to: "/engagement-photo-ideas/cozy-engagement-photos", note: "Rustic's indoor cousin — the same textures, closer in" },
        { label: "Outdoor Engagement Photo Ideas", to: "/engagement-photo-locations/outdoor-engagement-photo-locations", note: "Where the weathered surfaces actually live" },
        { label: "Black and White Engagement Photos", to: "/engagement-photo-ideas/black-and-white-engagement-photos", note: "The fastest rescue for a too-themed set" },
      ]},
    ],
  },
];
