import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const SAVE_THE_DATE_POSES_POSTS: Post[] = [
  {
    slug: "save-the-date-poses",
    title: "Save the Date Poses: 10 Card-Ready Frames That Still Look Like You Two",
    seoTitle: "Save the Date Poses: 10 Card-Ready Frames",
    seoDescription:
      "Save the date poses built for the card: 10 frames composed around text space, crop shape and the one-second rule — so your announcement lands warm, not staged.",
    excerpt:
      "A save the date is a photograph with a payroll: it has to carry your names and your date and still feel like the two of you. These 10 poses are built card-first — for the crop, for the empty space the type will sit in, and for the one honest second a held pose always gives away.",
    category: "poses",
    date: "2026-10-13",
    dateModified: "2026-10-13",
    featuredImage: IMAGES.galleryRing,
    featuredAlt: "save the date poses, couple walking away hand in hand with open sky for the card text",
    tags: ["save the date", "poses", "announcement", "card", "crop", "couples"],
    author: harper,
    primaryKeyword: "save the date poses",
    cluster: "save-the-date-photos",
    lsiKeywords: ["save the date photo poses", "announcement poses", "couple poses for cards", "save the date shoot", "negative space poses"],
    searchIntent: "Informational",
    relatedPosts: ["save-the-date-photo-ideas", "proposal-poses", "surprise-proposal-ideas", "natural-engagement-photo-poses"],
    internalLinks: [
      { url: "/save-the-date-photos", anchor: "the save the date hub" },
      { url: "/save-the-date-photos/save-the-date-photo-ideas", anchor: "choosing the shot" },
      { url: "/save-the-date-photos/proposal-poses", anchor: "proposal poses" },
      { url: "/engagement-photo-poses", anchor: "the full pose hub" },
      { url: "/engagement-photo-prints/photo-booth-strip-ideas", anchor: "strip save-the-dates" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.galleryRing, overlayText: "Leave Room for the Type", pinTitle: "Save the Date Poses: 10 Card-Ready Frames", pinDescription: "The best save the date photos are composed around the words before the shoot. 10 poses with the crop and the empty third planned in — pin this for your announcement." },
      { image: IMAGES.classicDip, overlayText: "Hold It, Then Let Go", pinTitle: "The One-Second Rule Behind Every Great Save the Date Photo", pinDescription: "Frame one is the pose, frame two is you two. The save the date card should show the second one — here are 10 poses built to produce it. Save before your shoot." },
      { image: IMAGES.galleryTwirl, overlayText: "Card-First Composing", pinTitle: "Save the Date Photos That Fit the Card, Not Just the Camera", pinDescription: "Vertical cards, square posts, wide mailers — the crop decides the pose. 10 save the date frames sorted by card shape. Pin for your announcement season." },
    ],
    blocks: [
      { type: "p", text: "Most save the date photos fail after the shoot, not during it: a lovely frame that arrives with no room for the names, or a gorgeous portrait that becomes a thumbnail-sized smudge on a vertical card. The fix is boring and it's the whole job — pick the card shape before you pick the pose, and leave the empty space on purpose. Everything below is composed for the announcement, not just the camera. Ten poses, the crop each one wants, and the one-second rule that makes any of them look like you two instead of a stock library." },
      { type: "keyTakeaways", items: [
        "Choose the card shape first: vertical cards want full-body or wide frames, squares want the couple tight and centered.",
        "Leave an honest empty third — sky, wall, water — on the side the type will sit.",
        "Shoot every pose twice: the held frame is the plan, the one after it is the card.",
        "The ring belongs in at least one save-the-date frame, small in the picture, not the whole picture.",
      ]},
      { type: "h2", id: "different-job", text: "Why a Save the Date Pose Is a Different Job" },
      { type: "p", text: "An engagement photo documents a couple; a save the date documents a couple and announces a date, which means the frame has a payroll to meet. The names go somewhere, the date goes somewhere, and if you didn't decide where before the shoot, the designer will force the type onto the one part of the photo that mattered. The other difference is duration: an announcement card lives in a kitchen window for two years, so the pose can't lean on a trend. A held, formal pose dates a card; a mid-action one — a walk, a turn, a laugh caught — stays warm for as long as the paper does." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "crop-first", text: "Crop First, Pose Second" },
      { type: "p", text: "Before any posing, decide the card — the format is the frame's skeleton. A vertical 5×7 mailer wants bodies small in a tall scene, with sky overhead for the words. A square works best with the couple centered and nothing important in the corners, because the feed eats edges. A wide mailer flips the problem: the couple to one side and the whole other half given to the typography. The table matches format to pose instinct; the ten below say which shape each one was born for." },
      { type: "table", caption: "Card format versus pose that survives it", headers: ["Format", "Pose instinct", "Why"], rows: [
        ["Vertical 5×7", "Full body, small in frame, sky above", "Leaves the top third clean for names"],
        ["Square 5×5", "Waist-up, centered, quiet background", "Feed crop can't steal the edges"],
        ["Wide mailer", "Couple right, landscape left", "Type gets its own half"],
        ["Photo strip 2×6", "Four frames, one story", "Sequence reads like a found object"],
      ]},
      { type: "h2", id: "the-10-poses", text: "The 10 Poses" },
      { type: "p", text: "Each one names the card shape it's built for and the direction that keeps it honest. Same rule for all ten: shoot the pose, then shoot the breath after the pose — the card almost always wants the second one." },
      { type: "h3", id: "pose-wide-room", text: "1. The Wide With Room" },
      { type: "p", text: "The workhorse. Full bodies, standing or walking, the couple occupying the lower right of the frame and a clean third of sky, wall or water above and beside them — that empty space is where 'Sam & Alex — June 2027' will live. Vertical cards are built on this one pose. The direction: 'stand exactly where you'd wait for a bus together.' Neutral, unhurried, room for the type. If the background is busy, move the couple closer and the shot quietly becomes pose five." },
      { type: "h3", id: "pose-walk-away", text: "2. The Walking Away" },
      { type: "p", text: "Back to camera, holding hands, mid-stride on a path or a pier — the couple small in the bottom half, the road or water leading to the horizon, and all of the top third reserved for the announcement line. It reads as 'this is where we're going' without a single word about the wedding, which is exactly what a save the date is for. Keep the stride honest: normal walking speed, not a fashion show. The photo works because nobody can see the faces trying." },
      { type: "h3", id: "pose-ring-small", text: "3. The Ring, Small in Frame" },
      { type: "p", text: "Her hand up near the middle of the frame, the stone sharp and the faces soft behind it — the ring confirmed, the couple still the subject. This is the pose for the card that needs one unmistakable 'why' at a glance without turning into a product shot. Shoot at arm's length with a wide-ish lens and let the hands do the announcing. It pairs with the wide-with-room as the flip side of the same card — announcement front, faces on the back." },
      { type: "h3", id: "pose-kitchen", text: "4. The Kitchen Coffee Two-Shot" },
      { type: "p", text: "At home, against the counter, mugs held at chest height, shoulders touching, looking at each other instead of the lens. The save the date card that reads like a Sunday morning outperforms the sunset epic for one reason: it's the two of you, and nobody questions it. Leave the counter line low in frame and the cabinet or window above clean for the names. Squares love this pose; the centered couple survives any crop." },
      { type: "h3", id: "pose-laugh-crop", text: "5. The Shared-Laugh Tight" },
      { type: "p", text: "Close enough that the faces fill the frame — foreheads not quite touching, eyes closed from laughing, her hand visible on his chest. The names go beneath the chins, so this one needs the bottom third of the card clear or the type lands on a shoulder. The tight crop is also the safest answer when the weather, the location or the schedule goes sideways; a doorway and a bad joke will produce it in ninety seconds." },
      { type: "h3", id: "pose-dip-sky", text: "6. The Dip With Sky" },
      { type: "p", text: "The one pose that's allowed to be dramatic — him dipped low at the edge of a field or a boardwalk, her hair hanging toward the ground, both of them laughing so it doesn't become a perfume ad. Shoot it low with all sky above: the couple anchors the bottom edge and the top half is a clean banner for the date. Verticals love this. If you hold the dip and the smile for a full ten seconds, frame four — the arms shaking, the collapse — is usually the keeper." },
      { type: "h3", id: "pose-twirl", text: "7. The Twirl Freeze" },
      { type: "p", text: "He holds her hand out and she turns — dress catching, blur in the hem, face toward the camera and laughing at the physics of it. Motion is the one thing a held pose can't fake, and a save the date card with a real blur in it gets texted back with exclamation points. Put her off-center, toward the top third of a vertical or the right of a wide, and leave the trailing side clean for the typography. Shoot burst; one frame in twenty catches the exact apex." },
      { type: "h3", id: "pose-distance", text: "8. The Distance Two-Shot" },
      { type: "p", text: "The couple very small — a hundred feet out on a beach, a field road, a pier — so the landscape is the card and the two of you are the detail. Then the names go in the sky, which asks nothing of them and nothing of the designer. It's the most calm save-the-date frame that exists and the only one where 'what do we do with our faces' is fully solved: nobody can see them. The catch: pick a day with texture in the light, or flat weather reads as empty." },
      { type: "h3", id: "pose-fourth-wheel", text: "9. The Fourth Wheel, On Purpose" },
      { type: "p", text: "The dog between you two or front-and-center, bandana on, sitting for exactly as long as a dog sits. Announcements with pets get kept because the card includes the whole household, and the frame comes with built-in motion — the second the treat appears, the stiff pose dies and the photo starts. A tight three-shot works for squares; for verticals, sit on the ground with the dog's head in the top half, above the type line." },
      { type: "h3", id: "pose-countdown", text: "10. The Countdown Hold" },
      { type: "p", text: "One of you holds a small sign, the other covers the other person's eyes, or the date is written on an upturned palm held toward the camera. The prop carries the news so the couple can be entirely unposed — watching each other watch the sign. This is the save-the-date version of a reveal, and like any reveal it works once: hold the palm steady, keep the faces behind it soft, and let the card do the talking. Squares and tight verticals both." },
      { type: "quote", text: "The card has a payroll. Every pose is just the couple agreeing to leave room for the check.", cite: "Harper" },
      { type: "gallery", images: [
        { src: IMAGES.galleryTwirl, alt: "save the date pose, the twirl freeze with dress caught mid-turn and clean sky above the type line" },
        { src: IMAGES.classicDip, alt: "save the date pose, the dip with sky, couple laughing at the edge of the frame" },
        { src: IMAGES.galleryLaugh, alt: "save the date pose, the shared-laugh tight crop with room below the chins for the names" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "card-is-edit", text: "The Card Is the Final Edit" },
      { type: "p", text: "A pose is only finished when the card is. The names get one line, the date gets one, and the photo keeps everything else — three competing text blocks and a couple become a flyer. If the design software is the enemy of your wide shot, the fix is in the shoot: more negative space than feels natural, because type eats emptier space than it looks like it needs. And if a plain card feels too bare for the news, the strip version solves it in one move — a 2×6 photo booth strip carrying four frames and one date is an announcement that gets taped to a fridge instead of a drawer." },
      { type: "h2", id: "what-couples-get-wrong", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They pose for the camera and not for the card — a beautiful frame that the designer has to chop into a rectangle of somebody's elbow. They treat the save the date like the wedding itself and go formal; the card is a text message with paper on it, and warmth outperforms polish. They crop tight at the shoot and leave the type nowhere to sit; give the sky a job. And they run one take of a held pose — which is how announcements end up showing the four seconds where everyone is performing. The keeper lives one frame past the pose. Shoot the second one." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "Design the card first, then shoot to it — I bring couples the actual template, names and date already laid in, so the empty third is obvious to them before the first shutter press. The moment a couple sees the card instead of the camera, the posing fixes itself; they start making space on their own." },
      { type: "p", text: "What I'd do differently after years of shooting announcements: I used to over-direct the save-the-date day. Now I shoot the poses early, put the camera down for ten minutes, and then photograph the ten minutes after — because the card is going to hang in a kitchen for two years, and what people want to see in it is not two models holding a dip. It's the two people who can't quite believe it either." },
      { type: "quote", text: "A save the date card should look like the moment you two stopped telling people and started showing them.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "What are the best poses for save the date photos?", a: "The ones with room for the words: a wide with clean sky, a walk-away on a path, or a tight laugh with space below the chins. Card-first beats camera-first every time — pick the format before the shoot, pose into the empty third, and shoot the second frame after each held pose." },
        { q: "Should save the date photos be vertical or horizontal?", a: "Decide the card, then the crop — vertical mailers want full bodies small in the frame with sky for the names, wide cards want the couple to one side, and squares want the faces centered with quiet edges. Mailing cards and Instagram announcements are different formats; shoot both crops for every pose." },
        { q: "Do save the date photos need to show the ring?", a: "No, and the cards that lead with it rarely age best. One frame with the ring small in the picture — a hand up, stone sharp, faces soft behind — confirms the news and keeps the couple the subject. The save the date is about the date; the ring got its close-up at the proposal." },
        { q: "How far in advance do you send save the dates?", a: "Six to nine months before the wedding is the standard, earlier for travel-heavy or holiday dates. That window also decides the shoot: you want the finished cards in the mail before the countdown, which means the session belongs eight to ten months out, in a season whose light suits the plan." },
        { q: "Can we take our own save the date photos?", a: "Yes — a tripod, a twenty-second timer and burst mode will produce any wide or walk-away pose on this list, and the self-timed awkwardness is honestly part of the charm. The one thing to hire out is the tight laugh frames; a stranger with a camera makes people act loose in ways a timer can't." },
      ]},
      { type: "leadMagnet", title: "The Save-the-Date Frame Planner", subtitle: "The card templates — vertical, square, wide — with the pose and the empty third already marked, so you shoot the design instead of hoping for it.", bullets: ["3 card layouts with the type zone marked", "The 10 poses sorted by format", "The shoot-the-second-frame timer card"], cta: "Get the Frame Planner" },
      { type: "shop", section: "prints", items: [
        { label: "Save-the-date card templates (editable)", store: "Etsy", href: "https://www.etsy.com/search?q=save+the+date+card+template" },
        { label: "Photo card printer, matte stock", store: "Amazon", href: "https://www.amazon.com/s?k=photo+card+printer" },
        { label: "Card stock, 110lb matte", store: "Amazon", href: "https://www.amazon.com/s?k=card+stock+matte+110lb" },
      ]},
      { type: "p", text: "The save the date I still have in my kitchen window is a wide of two people I shot a decade ago — small in the bottom corner, a whole Texas sky for the names, and you can't see their faces at all. People ask about that card every single time someone visits. Nobody has ever asked who they're posing for. That's the entire argument for the wide with room: the announcement isn't a portrait of a couple on their best behavior, it's a view of two people in the landscape where they decided yes." },
      { type: "keepReading", items: [
        { label: "Save the Date Photo Ideas", to: "/save-the-date-photos/save-the-date-photo-ideas", note: "Which shot, and the negative space rule" },
        { label: "Proposal Poses", to: "/save-the-date-photos/proposal-poses", note: "The frames before this one" },
        { label: "Photo Booth Strip Ideas", to: "/engagement-photo-prints/photo-booth-strip-ideas", note: "The strip as your announcement" },
      ]},
    ],
  },
];
