import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const SPRING_SUMMER_POSTS: Post[] = [
  {
    slug: "spring-summer-engagement-outfits",
    title: "Spring & Summer Engagement Outfits: 9 Ways to Dress for Warm Light",
    seoTitle: "Spring & Summer Engagement Outfits: 9 Warm-Weather Looks",
    seoDescription:
      "Spring and summer engagement outfits built for heat and golden light: breathable fabrics, colors that photograph, and how to stay cool and look it on your day.",
    excerpt:
      "Warm-weather shoots punish a wardrobe in ways fall never does — sweat shows, polyester traps heat, and a stiff outfit has nowhere to hide in bright sun. The couples who looked effortless had planned for the heat. Here are nine ways to dress for spring and summer sessions without sacrificing a frame.",
    category: "outfits",
    date: "2026-11-03",
    dateModified: "2026-11-03",
    featuredImage: IMAGES.outfitsCover,
    featuredAlt: "spring summer engagement outfits couple in breathable linen and a flowy dress in warm golden light",
    tags: ["spring", "summer", "outfits", "linen", "heat", "floral", "light"],
    author: harper,
    primaryKeyword: "spring summer engagement outfits",
    cluster: "engagement-photo-outfits",
    relatedPosts: ["fall-engagement-photo-outfits", "engagement-photo-color-palette", "casual-engagement-photo-outfits", "best-outfits-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-outfits/fall-engagement-photo-outfits", anchor: "cooler-season wardrobes" },
      { url: "/engagement-photo-outfits/engagement-photo-color-palette", anchor: "a shared palette" },
      { url: "/engagement-photo-outfits/casual-engagement-photo-outfits", anchor: "easy layers you can shed" },
      { url: "/engagement-photo-outfits/best-outfits-engagement-photos", anchor: "the core outfit rules" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.outfitsCover, overlayText: "Built for the Heat", pinTitle: "Spring & Summer Engagement Outfits: 9 Warm-Weather Looks", pinDescription: "Warm weather punishes a wardrobe in ways fall never does. Breathable fabrics, colors that photograph, and moves that keep you cool. Save these 9 looks." },
      { image: IMAGES.galleryTwirl, overlayText: "Let It Move", pinTitle: "Why Flowy Beats Fitted in Summer Photos", pinDescription: "A dress with movement and a breeze are the only two summer accessories that always work. Here's how to dress for it. Save this." },
      { image: IMAGES.galleryLaugh, overlayText: "Soft Spring, Bright Summer", pinTitle: "The Spring vs Summer Color Difference", pinDescription: "Spring wears muted pastels; summer can take brighter color. Same shoot, different palette. Save the season cheat sheet." },
    ],
    blocks: [
      { type: "p", text: "Fall lets an outfit cheat. A little stiffness hides inside a heavy knit, sweat doesn't happen, and grey light forgives a fabric that photographs flat. Warm weather strips all of that away. A polyester blazer at 90 degrees is a visible misery, a stiff silhouette has nowhere to hide in hard sun, and a dark or slick material throws a sheen the camera can't unsee. The couples who looked effortless in their spring and summer sessions weren't luckier with their bodies or their budget — they dressed for the two things warm weather actually demands: airflow and light. Here's how, nine moves at a time." },
      { type: "keyTakeaways", items: [
        "Breathable natural fabrics beat polyester in heat — on camera and on your skin.",
        "Loose, moving silhouettes flatter in bright sun far better than stiff, fitted ones.",
        "Spring leans muted pastel; summer can carry brighter color. The light decides.",
        "Plan for sweat and shade: light layers, a hat, and shoes the grass won't swallow.",
      ]},
      { type: "h2", id: "why-warm-weather-punishes", text: "Why Warm Weather Punishes a Wardrobe" },
      { type: "p", text: "Heat and bright light are honest in a way fall isn't. They show three things a cooler shoot hides: what a fabric is made of (polyester sheens and clings), how a body feels (sweat marks, a flushed face, a jacket that's now too much), and whether an outfit moves (stiff looks stiff when there's nothing to soften it). None of this is solved by a better camera — it's solved at the closet. Choose natural fibers that breathe, silhouettes with a little looseness so air moves, and colors set for the season's light rather than the season's mood board. Do that and the warmth stops fighting you and starts flattering you, because that's what golden-hour light is for." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "spring-vs-summer", text: "Spring and Summer Aren't the Same Palette" },
      { type: "p", text: "The single most common planning error is treating 'warm weather' as one season. It isn't. Spring light is softer and the land is green and new, which flatters muted, dusty pastels — sage, blush, pale blue, cream. Summer light is harsher and the land is gold and dry, which can carry more saturated color — terracotta, olive, a brighter coral, ivory that holds up against a bleached background. Pick your palette to the month, not just the fact that it's warm, and pull the two of you onto a shared set of tones so you read as a couple instead of a costume rack." },
      { type: "table", caption: "Dressing the two warm seasons", headers: ["", "Spring", "Summer"], rows: [
        ["Light", "Soft, green, gentle", "Hard, gold, bright"],
        ["Palette", "Dusty pastels — sage, blush, cream", "Sun-bright — terracotta, olive, ivory"],
        ["Fabric", "Cotton, light linen, soft knit", "Linen, gauze, airy chiffon"],
        ["Watch for", "Pollen on dark fabric", "Sweat, sheen, static"],
        ["Golden hour", "Earlier, cooler", "Later, warmer"],
      ]},
      { type: "h2", id: "the-9-looks", text: "The 9 Looks" },
      { type: "p", text: "Nine choices that solve what heat and light break. Fabric and silhouette do most of the work; the rest is planning around sweat and sun." },
      { type: "h3", id: "natural-fibers", text: "1. Natural, Breathable Fabrics First" },
      { type: "p", text: "Linen, cotton, and rayon let air reach your skin; polyester traps heat against it and throws a shine in direct sun. A man in a linen shirt and a woman in a cotton-linen dress will stay comfortable long enough to look natural, which is the whole game in ninety-degree light. When you plan the rest of the look around the core rules you already know, let the fabric be the first thing you pick, not the last." },
      { type: "h3", id: "loose-silhouette", text: "2. Loose Silhouettes That Move" },
      { type: "p", text: "In bright sun a fitted outfit shows every line and holds every drop of heat; a little ease around the body breathes, and a skirt or dress with movement catches the breeze and adds life to a standing frame. The wind is free on a summer shoot — dress so you can use it. A twirl or a step is a better summer motion than a held pose, and a moving fabric reads as effortless on a still day." },
      { type: "h3", id: "pastels-vs-brights", text: "3. Match Color to the Month" },
      { type: "p", text: "Dusty pastels sing against spring's soft green; sun-bright earth tones hold up against summer's bleached gold. Put a loud summer palette in a green spring field and it fights the frame; drop the same couple into sage and cream and the season starts doing the styling for you. The light and the land are the other two members of the outfit — dress to them, not around them." },
      { type: "h3", id: "one-ivory-anchor", text: "4. Anchor Everything in a Neutral" },
      { type: "p", text: "Warm color goes loud fast when two people both chase it. Give one partner the statement piece — the coral, the terracotta, the bold floral — and ground the other in ivory, oatmeal, or soft cream so the eye has somewhere to rest. A neutral anchor is the difference between a couple that looks coordinated and two outfits competing for the same frame, especially in high-key summer light where everything already trends bright." },
      { type: "h3", id: "floral-scale", text: "5. Florals at the Right Scale" },
      { type: "p", text: "A spring or summer floral is a gift — but the scale matters. A medium-sized bloom reads as texture and charm; a micro-floral breaks into noise and shimmer at print size, and a giant one swamps a face. Pick a flower pattern you'd still like in five years, keep the scale to a handful of soft shapes, and let it do the springtime work without turning the frame busy." },
      { type: "h3", id: "sleeveless-with-a-cover", text: "6. Sleeveless, Plus Something to Shed" },
      { type: "p", text: "Going sleeveless is the sensible answer to heat, but it also means bare shoulders under the sun and no place to hide a sudden cold golden-hour dip. Bring one light cover — an open linen shirt, a wrap, a soft cardigan the other can help off between frames. It gives you a second look for the evening light and saves the last half of a session that would otherwise be spent visibly shivering once the sun drops." },
      { type: "h3", id: "grass-safe-shoes", text: "7. Shoes the Grass Won't Swallow" },
      { type: "p", text: "Stiletto heels sink into soft summer turf and leave you off-balance and grimacing, which shows right in the frame. Block heels, wedges, clean flats, loafers — or simply go barefoot for the most relaxed look of the whole shoot — keep you steady on warm grass and read as carefree. Pack the nice shoes for the walk to a paved spot and kick them off the second it's just the two of you and an open field." },
      { type: "h3", id: "hat-and-shade", text: "8. A Hat for Sun and for Squinting" },
      { type: "p", text: "The single enemy of a bright-day portrait is a couple squinting into the sun. A wide-brim hat or a straw fedora fixes it on the spot — it throws a soft shadow across the eyes, keeps faces relaxed, and instantly looks like the season. If you don't wear hats normally, skip it; an outfit you're fighting reads on camera, so choose the shade only if it's really you and let a friend or the other partner hold it off-frame." },
      { type: "h3", id: "beat-the-sweat", text: "9. Plan Around Sweat, Not After It" },
      { type: "p", text: "Heat always wins, so plan for it instead of being surprised. A breathable fabric with a little ease hides marks better than a tight one. Bring a handkerchief, a spare shirt, and a cold towel for the neck between takes. Avoid a soaked-under-the-arms dark or slick fabric in midday light — move the shoot to morning or the last hour of sun, where it's cooler and the light is doing you a favor, and let the sweat stay where the camera won't." },
      { type: "gallery", images: [
        { src: IMAGES.galleryTwirl, alt: "spring summer engagement outfits flowy cotton dress catching a warm breeze in a golden field" },
        { src: IMAGES.casualCafe, alt: "spring summer engagement outfits man in a breathable linen shirt with rolled sleeves" },
        { src: IMAGES.outfitsCover, alt: "spring summer engagement outfits couple in a sun-bright earth-tone palette at dusk" },
      ]},
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "what-to-avoid", text: "What Most Couples Get Wrong" },
      { type: "p", text: "They pick the outfit they love and ignore the one the heat will survive — a blazer, a synthetic, a brand-new dark cotton that will show every mark. They match colors too tightly, so two bright pieces cancel each other out in bright light. They shoot at high noon because that's when everyone's free, when morning or dusk is cooler and kinder. And they wear a brand-new shoe on wet grass all afternoon, then wonder why every standing frame looks tense. Fix the fabric, soften the sun, give the color an anchor, and give yourselves somewhere cool to breathe between takes. Warm weather is forgiving of comfort and merciless about anything else." },
      { type: "quote", text: "In summer the outfit has to work twice — once for the photograph and once for the ninety degrees it's standing in. When it only does one of those, you can see which.", cite: "Harper, from 400+ sessions" },
      { type: "ad", slot: "before-faq" },
      { type: "h2", id: "harpers-tips-warm", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "The strongest warm-weather frames I ever shot had a loose linen shirt and a sundress and nothing else — no styling, no props, just air moving through the fabric in a late-sun field. Complexity always loses to comfort in ninety-degree heat. Give me two people who can actually breathe in what they're wearing and the pictures look like them having the time of their lives." },
      { type: "p", text: "Here's what I'd do differently: I stopped telling couples to 'beat the heat' by scheduling at 8am when the light is flat and harsh. Better to shoot at the last hour of sun, accept a little warmth, and bring the cold towel — golden light is worth far more than a cool, grey morning. Comfort serves the light, not the other way around." },
      { type: "quote", text: "The breeze is a free stylist in summer — dress so there's something for it to do.", cite: "Harper" },
      { type: "faq", items: [
        { q: "What should we wear for spring engagement photos?", a: "Natural, breathable fabrics in soft, dusty tones — sage, blush, pale blue, cream — because spring light is gentle and the land is green. Go loose and let a little air move the fabric. A medium-scale floral suits the season beautifully without turning noisy at print size. Keep one partner in a neutral to ground the other's color, and save the heavy knits for the cooler seasons instead." },
        { q: "What should we wear for summer engagement photos?", a: "Linen and airy cotton in silhouettes that move, with sun-bright earth tones — terracotta, olive, ivory — that hold up against a dry, bleached background. Sleeveless is smart for the heat; just bring one light layer to shed for the cooler golden hour. Anchor the bright color on one partner, go barefoot or block-heeled on grass, and time it late so you're shooting in warm light, not sweat." },
        { q: "What colors look good for warm-weather engagement photos?", a: "Spring flatters muted pastels — blush, sage, cream — because soft light and green grass do the styling. Summer can carry brighter saturated color because the light is harsher and the backdrop is dry gold. In both seasons, keep the two of you inside one shared, neutral-anchored palette so you read as a couple and not two competing statements. Avoid a wall of pure white, which blows out in strong sun." },
        { q: "How do we avoid sweat showing in summer photos?", a: "Choose a breathable fabric with a little ease over a tight one, and favor a color or print that hides marks. Skip slick dark fabrics that sheen under direct sun. Move the shoot to early morning or the last hour of light, where it's genuinely cooler, and keep a cold towel and a spare shirt for the neck between takes. Comfort keeps your face relaxed, and a relaxed face hides more than any outfit trick." },
        { q: "Are sleeveless outfits okay for engagement photos?", a: "Yes — in heat they're often the most comfortable and most flattering choice, and bare shoulders read as easy and summery. Just bring one light cover for shade, for the moment the sun sets, or if you'd rather not be bare-shouldered in a few frames. A linen shirt or a wrap gives you a second look for the evening light without overheating you for the whole shoot." },
        { q: "What shoes should we wear for an outdoor summer session?", a: "Pick something the grass won't punish you for — block heels, wedges, clean flats, loafers, or no shoes at all. A stiletto sinks into soft warm turf and leaves you wobbling and tense, and that shows straight through to the frame. Bring the nice pair for a paved walk and kick them off the moment it's just the two of you in an open field, where barefoot looks the most natural of everything." },
      ]},
      { type: "leadMagnet", title: "The Warm-Weather Outfit Card", subtitle: "The fabric-and-color list for spring and summer, plus the sweat-and-sun plan — one card before you pack.", bullets: ["Breathable fabric + palette by season", "The neutral-anchor rule for two people", "Sweat, shade & grass-safe shoes checklist"], cta: "Get the Warm-Weather Outfit Card" },
      { type: "shop", section: "outfits", items: [
        { label: "Breathable linen shirt (men's)", store: "Clothing", href: "#" },
        { label: "Flowy cotton-linen dress", store: "Clothing", href: "#" },
        { label: "Wide-brim straw hat", store: "Accessories", href: "#" },
      ]},
      { type: "p", text: "Late July, the sun going amber over the dry grass, his sleeves rolled and her dress catching a breeze every few seconds. She'd almost cancelled over the heat and I'd almost talked her into a morning that would've looked nothing like this. Instead they stood there with cold towels in their pockets, laughing at a gust that kept flipping the hem, and every frame looked like the exact warm evening it was. Comfortable, in the right fabric, in the right light. That's the whole summer outfit — nothing else about it matters." },
      { type: "keepReading", items: [
        { label: "Fall Engagement Photo Outfits", to: "/engagement-photo-outfits/fall-engagement-photo-outfits", note: "The cooler-season palette to swap into" },
        { label: "Engagement Photo Color Palette", to: "/engagement-photo-outfits/engagement-photo-color-palette", note: "How to anchor two outfits in shared tones" },
        { label: "Best Engagement Photo Outfits", to: "/engagement-photo-outfits/best-outfits-engagement-photos", note: "The core rules that hold in any season" },
      ]},
    ],
  },
];
