import { IMAGES } from "../lib/constants";
import type { Author, Post } from "./types";

const harper: Author = {
  handle: "harper-ellis",
  name: "Harper Ellis",
  role: "Founder & Engagement Photo Editor",
  bio: "Harper spent 8 years behind the lens shooting 400+ engagement sessions across the US before trading her camera for a keyboard. Based in Austin and married to her high school sweetheart, she writes the warm, practical guides every couple deserves.",
  avatar: IMAGES.about,
  instagram: "@tenderlight.journal",
};

const M = { adsense: true, affiliate: true, leadMagnet: true };

export const VINTAGE_POSTS: Post[] = [
  {
    slug: "vintage-engagement-photo-ideas",
    title: "Vintage Engagement Photos: 12 Borrowed Decades That Don't Look Costumed",
    seoTitle: "Vintage Engagement Photos: 12 Borrowed Decades",
    seoDescription:
      "Vintage engagement photos are a decade you borrow, not a costume you buy: 12 setups, the one-era rule, the grain question answered, and a $40 kit.",
    excerpt:
      "Vintage is time pre-installed in a frame — but the line between era and costume is one borrowed detail. Twelve setups split by what you bring and what's already frozen, with the grain question settled.",
    category: "ideas",
    date: "2026-10-08",
    dateModified: "2026-10-08",
    featuredImage: IMAGES.indoor,
    featuredAlt: "vintage engagement photos, couple in a grandmother's kitchen with a borrowed vinyl stack between them, warm light, one era only",
    tags: ["vintage", "era", "thrift", "film", "grain", "one-era rule"],
    author: harper,
    primaryKeyword: "vintage engagement photos",
    cluster: "engagement-photo-ideas",
    lsiKeywords: ["retro engagement session", "film grain portraits", "thrift-store props", "vintage diner photos", "record shop session", "grandmother's kitchen"],
    searchIntent: "Informational",
    relatedPosts: ["classic-engagement-photos", "black-and-white-engagement-photos", "rustic-engagement-photos"],
    internalLinks: [
      { url: "/engagement-photo-ideas", anchor: "the full ideas desk for this cluster" },
      { url: "/engagement-photo-ideas/classic-engagement-photos", anchor: "the timeless version of this page" },
      { url: "/engagement-photo-ideas/black-and-white-engagement-photos", anchor: "the color decision, separately" },
      { url: "/engagement-photo-ideas/rustic-engagement-photos", anchor: "the rural twin of the decade idea" },
      { url: "/engagement-photo-ideas/candid-engagement-photo-ideas", anchor: "what keeps a vintage frame honest" },
    ],
    monetization: M,
    pinImages: [
      { image: IMAGES.indoor, overlayText: "One Decade, Borrowed", pinTitle: "12 Vintage Engagement Photo Setups That Skip the Costume", pinDescription: "Vintage engagement photos work when one borrowed detail does the era-work and you two stay yourselves. The six things to bring, the six places already frozen, and the $40 kit. Save this." },
      { image: IMAGES.casualCafe, overlayText: "The Diner Knows", pinTitle: "The Six Places Already Frozen in Time for Your Engagement Shoot", pinDescription: "Red vinyl, record-shop aisles, a grandmother's kitchen — some locations just have to be photographed honestly. Six found frames plus the one-era rule. Pin it before you plan." },
      { image: IMAGES.galleryRing, overlayText: "Grain Is an Edit", pinTitle: "Film vs Digital for Vintage Engagement Photos — Settled", pinDescription: "Shoot raw, add grain at edit, keep the undo. The real answer to the film-or-digital question from a photographer who shot both for eight years. Twelve vintage setups to go with it." },
    ],
    blocks: [
      { type: "p", text: "Vintage engagement photos are the only style on this desk that borrows something for free: time. A frame with a record player in it already has a decade attached, and neither of you has to act — the era does half the work, and the camera is just the witness. But there's a line between a borrowed decade and a costume, and it's exactly one sentence long: are you wearing the vintage, or living in it? The twelve setups below keep one borrowed detail on purpose and the rest just you two, split by what you bring and what you find already frozen." },
      { type: "h2", id: "warmth-not-costume", text: "Why Vintage Reads as Warmth, Not Costume" },
      { type: "p", text: "A vintage element is a story pre-installed in the frame. The grain, the enamel, the vinyl — each carries ten thousand other photographs with it, and yours joins that line instead of standing alone. That's the warmth people name when they say they want a \"vintage feel\": the picture looks like it was kept, even the day it's shot." },
      { type: "p", text: "The line is arithmetic. One borrowed detail reads as you two; three matching ones read as a school play. Across my 400-plus sessions, the vintage galleries that survived were almost always the frames where one era-element was true and the rest of the photograph was just a couple being lazy in a kitchen. Lazy is the tell, by the way — an era you're performing in produces stiff hands, and stiff hands with a prop in them are the costume the lens finds every time." },
      { type: "ad", slot: "after-first-h2" },
      { type: "h2", id: "two-questions", text: "Before You Pick: Two Questions" },
      { type: "p", text: "One: is the decade yours? Your parents' era beats a generic 1950s because you'll actually recognize the prop when you hold it — you'll know the song before the needle drops — and recognition is what keeps the faces honest. Two: can you borrow it for under $40? Vintage is sourced, not bought. If you have to buy it new, it's a costume with a price tag, and the tag always shows." },
      { type: "keyTakeaways", items: [
        "One borrowed detail does the era-work; three matching ones make a play.",
        "Pick your parents' decade over Pinterest's — recognition keeps faces honest.",
        "Under $40: everything vintage is borrowed, thrifted or already in your house.",
        "Grain is an edit decision. Shoot raw, keep the undo, never bake a filter.",
        "The strongest vintage frames don't look old — they look like you were always there.",
      ]},
      { type: "h2", id: "six-to-bring", text: "The Six Things You Bring" },
      { type: "p", text: "These are the borrowed details, and each one is doing the time work for the whole frame." },
      { type: "list", items: [
        "The film point-and-shoot — hers from a thrift shelf, and the pose is her raising it to photograph him while the real camera photographs him posing badly on purpose.",
        "The vinyl stack — two boxes off a thrift shelf, sat on between you on the floor, arguing about track one in a decade neither of you can vote in.",
        "The paper map — the road-trip kind, spread out wrong on a hood, both of you pointing confidently somewhere wrong. Getting lost was analog once.",
        "The enamel mugs — dented, paired, coffee poured on purpose; the clink is the audio track the frame never hears but always shows.",
        "The grandfather's jacket — corduroy, sleeves a half-inch too long on her, worn over your own actual clothes so it reads borrowed, not rented.",
        "The one Polaroid — you each get a frame of the other, shot on instant film; the photo of the photo, developing in two hands, is the keeper.",
      ]},
      { type: "h2", id: "six-to-find", text: "The Six Places Already Frozen" },
      { type: "p", text: "These need one visit and zero props — the decade is load-bearing, not decorative. Scout them in daylight; at golden hour you won't see what you're walking into." },
      { type: "list", items: [
        "The diner booth — red vinyl, a sugar dispenser, the window; the vinyl cracked in the exact spot the last ten thousand couples sat is why it photographs true.",
        "The record shop aisle — the flip, the leaning, the two of you on opposite ends of one shelf calling out an artist the other doesn't know.",
        "The grandmother's kitchen — ask first, then just stand in it; small rooms with old windows do the warm-light work no lamp can fake.",
        "The flea market — forty eras at once, so shoot faces not objects; the frame is you two agreeing on one thing.",
        "The used bookstore — paperback spines as background texture, one open book each, the quiet argument of reading across each other.",
        "The twenty-year-old truck — yours if you already have one; a real car with real wear beats a rented one from a lot that charges $200 an hour for the same rust.",
      ]},
      { type: "p", text: "One era per session, and one place per idea. The map says seventies and the booth says fifties and the camera sees both of them pretending — and pretending is the one thing a photograph keeps forever, even if the couple forgets by dinner." },
      { type: "quote", text: "You don't need a decade. You need one object from it and two people who don't know they're holding it.", cite: "Harper" },
      { type: "ad", slot: "mid-article" },
      { type: "h2", id: "grain-question", text: "The Grain Question" },
      { type: "p", text: "Film or digital for the vintage look? Digital, shot raw, grain added at edit — full stop, and here's why. A filter baked in at capture can't be walked back on the one frame you actually love; grain in the edit is a slider, and your shooter will want to tune it per face and per light. Heavy preset grain also erases skin texture along with the decade, which is a strange trade: nobody misses pores, and nobody wants to look like sandpaper holding a record. If the couple genuinely wants the film experience, one roll at the session is a lovely prop-cost and a terrible dependency. The real vintage decision is texture, and texture survives being edited later." },
      { type: "table", caption: "The three styles people confuse, and what each one actually borrows", headers: ["Style", "It borrows", "It's for"], rows: [
        ["Vintage", "A decade — era-props, frozen places, one detail", "Couples with a family's story to hold"],
        ["Classic", "Nothing — it avoids dated choices", "Couples who want the frame to age slowly"],
        ["Black and white", "A color decision — line and light, not a time", "Frames built on contrast, not nostalgia"],
        ["Rustic", "A place — land, barn, work-worn material", "Couples whose era is rural, not dated"],
      ]},
      { type: "h2", id: "what-it-costs", text: "What Vintage Costs" },
      { type: "p", text: "Under forty dollars, and that's being generous. Thrift jackets run ten, records a dollar apiece, enamel mugs live in the two-dollar bin, paper maps are free at a gas station, and a roll of instant film is the price of coffee. The only thing worth renting is a place you genuinely can't find — and if you can't find a diner, a record shop or a small-windowed kitchen, the decade was never yours to borrow anyway. Note what isn't on this list: matching outfits. The uniform of a purchased era is the one line item that guarantees the costume look." },
      { type: "h2", id: "goes-wrong", text: "When Vintage Goes Wrong" },
      { type: "p", text: "The tell is simple: nobody in the frame looks like your partner. When the props win — the hats, the matching rented coats, the era spelled twice — the faces start performing the decade instead of living in it, and a performed era is a costume party the photographer wasn't invited to. I watched it happen at a whole fifties shoot, diners and all, and kept only two frames: the ones where a client's cap blew off and stopped being a costume on impact. The fix is subtraction. Remove one borrowed thing, keep the place, and ask for the frame you'd keep if every prop vanished. If the answer is \"none,\" that's the session's real problem, and the camera just found it before your album did." },
      { type: "gallery", images: [
        { src: IMAGES.casualCafe, alt: "vintage engagement photos, the diner booth, red vinyl cracked where ten thousand couples sat before" },
        { src: IMAGES.indoor, alt: "vintage engagement photos, the grandmother's kitchen, one vinyl stack doing the era-work for the whole frame" },
        { src: IMAGES.classicDip, alt: "vintage engagement photos, the paper map spread wrong on a hood, both pointing confidently somewhere wrong" },
      ]},
      { type: "h2", id: "what-couples-get-wrong", text: "What Couples Get Wrong About Vintage" },
      { type: "p", text: "They buy it new, and the price tag of a costume is the one thing a lens always reads. They stack decades — a fifties booth, seventies jackets, nineties mugs — until the frame is an estate sale with two people in it. They let the prop hold the pose, so the hands grip the vinyl and the faces go blank. And they pick an era that isn't theirs because it looked clean in a search for old photographs — which is the only way to guarantee the decade feels rented. Borrow one thing. Date it in your family. Keep the rest honest." },
      { type: "h2", id: "harpers-tips", text: "Harper's Tips & What I've Learned" },
      { type: "p", text: "My favorite vintage frame from all those sessions: her grandmother's kitchen, the old record player actually running, the two of them sitting wrong on the floor because the only chairs were \"not allowed.\" The single borrowed decade did everything; the lazy posture did the rest. That couple printed the one where he's mid-correction about the needle. Everyone should be so costumed as to be arguing about a record." },
      { type: "p", text: "What I'd do differently: I used to recommend six props to vintage clients — jackets, mugs, maps, the works — and the galleries that got printed always had one era-element in frame, never four. Now I ask a couple for one borrowed thing and one place that's already frozen, and I refuse the rest. The performance doesn't disappear; it just gets one job instead of a wardrobe to manage. Twelve setups, two questions, one arithmetic rule — because the vintage that survives is the decade you actually belong to." },
      { type: "quote", text: "Vintage is a borrowed decade. The marriage is the part you bring, and it's the part that keeps the frame.", cite: "Harper" },
      { type: "ad", slot: "before-faq" },
      { type: "faq", items: [
        { q: "Do we have to dress up for vintage engagement photos?", a: "No, and \"dress up\" is usually the costume itself. One borrowed piece — his jacket on her, the enamel mugs in hand, a record sleeve open on the couch — does more era-work than a full thrift wardrobe. The clothes you actually own keep the faces yours, and the faces are the frame. If the outfit is the subject, the wedding's in trouble." },
        { q: "Should we shoot film or digital for a vintage look?", a: "Digital, shot raw, with grain added at edit — one roll of film as a prop if the ritual matters to you. Film is a beautiful dependency for a day you can't reshoot, and grain in post is a slider you can tune per face. A filter baked in at capture is the one decision in this whole style that can't be undone after." },
        { q: "What decade should we pick?", a: "The one your families actually lived. If neither set of parents makes the prop feel like a memory, the decade is a costume you sourced instead of bought. And a decade you're too young to remember is fine — it just has to be one you can hold the object for without acting surprised by it." },
        { q: "Where do we find a vintage location?", a: "Where your parents already go. The diner they argue in, the record shop downtown, the aunt's kitchen with the small windows. Internet listings for \"vintage venues\" sell you the staged version; the found version is cheaper, more real, and someone there will tell your shooter exactly where the light hits at four." },
        { q: "Can we do vintage photos at home?", a: "The home is the best vintage studio most couples have and never consider. One room with the lights off and a single lamp, the family's records out on the floor, the grandfather's jacket on the back of a chair — that's a session. The decade was already there; you just have to stop tidying it for the camera." },
      ]},
      { type: "leadMagnet", title: "The Decade Card", subtitle: "The one-era rule, the $40 sourcing list, and the twelve setups — on one card for you two and your shooter.", bullets: ["The six things to borrow (all under $40)", "The six places already frozen, with scouting notes", "The subtraction test for any prop that wins"], cta: "Get the Decade Card" },
      { type: "shop", section: "props", items: [
        { label: "Pair of dented enamel camp mugs (the $2 clink)", store: "Amazon", href: "#" },
        { label: "Curated used vinyl bundle, one record each to argue over", store: "Etsy", href: "#" },
        { label: "Thrifted 35mm point-and-shoot, working-tested", store: "Etsy", href: "#" },
      ]},
      { type: "p", text: "The last vintage session I ever shot professionally ended where it started: on the floor of her grandmother's kitchen, the record running out, neither of them reaching for the last track because the other had claimed it ten minutes earlier. I shot the silence instead — two faces lit by one window, one borrowed decade, absolutely nobody performing. That's what vintage engagement photos are for, and the camera only had to keep its hands off it." },
      { type: "keepReading", items: [
        { label: "Classic Engagement Photos", to: "/engagement-photo-ideas/classic-engagement-photos", note: "The timeless cousin of the borrowed decade" },
        { label: "Black & White Engagement Photos", to: "/engagement-photo-ideas/black-and-white-engagement-photos", note: "Borrow a color decision, not a year" },
        { label: "Rustic Engagement Photos", to: "/engagement-photo-ideas/rustic-engagement-photos", note: "When the era is a place, not a decade" },
      ]},
    ],
  },
];
